### ISSUE TITLE
JedisCluster could't not process request when a cluster node crash？

### ISSUE THREAD

**Issue by eclipsky** [xetorthio/jedis#1020]
JedisCluster works well for 2 weeks ,but something goes wrong when one of master nodes crashed, 

 scenario brief description:
    
    public static void main(){
    ThreadPoolExecutor poolExecutor = (ThreadPoolExecutor) Executors.newFixedThreadPool(32);
    while(condition){
        // do something
        poolExecutor.execute(new BoltProcessor(){});
        int queueSize = poolExecutor.getQueue().size();
        if (queueSize > 200000) {
	    LOG.info("poolExecutor task queue size is greater than 200000 (" + queueSize + "), going to sleep for 1s.");
				Thread.sleep(1000);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
        // do something 
    }

    class BoltProcessor implements Runnable{
        public run(){
        // do something
        jedisCluster.hincrby();
       // do something
     }

    >>>>>>>>>>Exception throws when the node crashed
    -------------------------------------------------------------------------------------------------------------
  		redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:34)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:67)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:83)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:67)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:83)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:67)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:29)
        at redis.clients.jedis.JedisCluster.sadd(JedisCluster.java:551)
        at com.dataeye.redis.RedisClusterClient.sadd(RedisClusterClient.java:207)
        at com.dataeye.redis.RedisClusterClient.sadd(RedisClusterClient.java:226)
        at com.dataeye.storm.rt.online.RTRedisCalAsyncBolt$BoltProcessor.run(RTRedisCalAsyncBolt.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
    ....
    [INFO  2015-06-07 11:19:06 RTRedisCalAsyncBolt:167 BoltExecutors] poolExecutor task queue size is greater than 200000 (200001), going to sleep for 1s.
    [INFO  2015-06-07 11:19:07 RTRedisCalAsyncBolt:167 BoltExecutors] poolExecutor task queue size is greater than 200000 (200002), going to sleep for 1s.
    [INFO  2015-06-07 11:19:08 RTRedisCalAsyncBolt:167 BoltExecutors] poolExecutor task queue size is greater than 200000 (200003), going to sleep for 1s.
    [INFO  2015-06-07 11:19:09 RTRedisCalAsyncBolt:167 BoltExecutors] poolExecutor task queue size is greater than 200000 (200004), going to sleep for 1s.
    [INFO  2015-06-07 11:19:10 RTRedisCalAsyncBolt:167 BoltExecutors] poolExecutor task queue size is greater than 200000 (200005), going to sleep for 1s.

before node crashed, the poolExecutor queueSize always less then 10000,but now ,It looks like the JedisCluster could not handle the command, cause many task blocked in the queue

btw
Jedis version: 2.7.2
JedisPoolConfig maxTotal:2000
                           maxIdle:200

Redis version: 3.0.0

Thanks 
sam

**Comment by marcosnils** [comment]
@eclipsky did you have slave nodes for your cluster?.

**Comment by marcosnils** [comment]
@eclipsky I see you closed the issue, can you please tell us what ended up happening?
