### ISSUE TITLE
When trying to delete (rpop) from empty or non existing list it throws NullPointerException

### ISSUE THREAD

**Issue by yerzhik** [xetorthio/jedis#1033]
Exception in thread "Thread-10" java.lang.NullPointerException
        at java.lang.String.<init>(String.java:481)
        at redis.clients.util.SafeEncoder.encode(SafeEncoder.java:28)
        at redis.clients.jedis.BuilderFactory$5.build(BuilderFactory.java:55)
        at redis.clients.jedis.BuilderFactory$5.build(BuilderFactory.java:58)
        at redis.clients.jedis.Response.get(Response.java:27)
        at redis.clients.jedis.BinaryTransaction.exec(BinaryTransaction.java:31)

**Comment by marcosnils** [comment]
@yerzhik seems like you're using an old version of Jedis. I ran some tests and this seems to be fixed already.
