### ISSUE TITLE
`java.util.ArrayList cannot be cast to [B` after thrown exception at `RedisPubSub.onMessage`

### ISSUE THREAD

**Issue by buzztaiki** [xetorthio/jedis#1072]
Reproduction code is following:

```java
package redis.clients.jedis.tests;

import static org.junit.Assert.assertEquals;
import java.util.UUID;
import org.junit.Test;
import redis.clients.jedis.*;

public class PubSubTest {
    private static class PubSub extends JedisPubSub {
        @Override
        public void onMessage(String channel, String message) {
            throw new RuntimeException();
        }
    }

    @Test
    public void test() throws Exception {
        String channel = UUID.randomUUID().toString();

        try (Jedis jedis = new Jedis()) {
            PubSub pubsub = new PubSub();
            new Thread(() -> {
                try (Jedis j = new Jedis()) {
                    while (!pubsub.isSubscribed()) {
                        try {
                            Thread.sleep(100);
                        } catch (InterruptedException e) {
                            break;
                        }
                    }
                    j.publish(channel, "x");
                }
            }).start();

            try {
                jedis.subscribe(pubsub, channel);
            } catch (RuntimeException e) {
            }

            assertEquals("PONG", jedis.ping());
        }
    }
}
```

I got following error:
```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to [B
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:192)
        at redis.clients.jedis.BinaryJedis.ping(BinaryJedis.java:111)
        at redis.clients.jedis.tests.PubSubTest.test(PubSubTest.java:40)
```

**Comment by marcosnils** [comment]
@buzztaiki updates on this?

**Comment by marcosnils** [comment]
Closed for inactivity
