### ISSUE TITLE
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionExcepti on:

### ISSUE THREAD

**Issue by LILIDD** [xetorthio/jedis#1121]
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionExcepti
on: java.net.SocketException: Software caused connection abort: recv failed
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:
201)
        at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40
)
        at redis.clients.jedis.Protocol.process(Protocol.java:141)
        at redis.clients.jedis.Protocol.read(Protocol.java:205)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connect
ion.java:297)
        at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.jav
a:233)
        at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:226)

```
    at redis.clients.jedis.Jedis.brpop(Jedis.java:1679)
    at redis.clients.jedis.Jedis.brpop(Jedis.java:3357)
    at com.vvshop.Main.main(Main.java:78)
```

Caused by: java.net.SocketException: Software caused connection abort: recv fail
ed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:
195)
        ... 9 more

**Comment by sazzad16** [comment]
@LILIDD It seems like there were some issues in your network.
