### ISSUE TITLE
sentinel connection has not been released

### ISSUE THREAD

**Issue by ahzean** [xetorthio/jedis#1130]
Sentinel server appears a large number of semi connected, the client connection after the release, but the server side of the connection has not been released, eventually reached 10004 connections, resulting in the new client can not connect sentinel.

Caused By: redis.clients.jedis.exceptions.JedisDataException: ERR max number of clients reached
	at redis.clients.jedis.Protocol.processError(Protocol.java:113)
	at redis.clients.jedis.Protocol.process(Protocol.java:138)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:227)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:233)
	at redis.clients.jedis.Jedis.sentinelGetMasterAddrByName(Jedis.java:2692)
	at redis.clients.jedis.JedisSentinelPool.initSentinels(JedisSentinelPool.java:123)
	at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:69)
	at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:48)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.createRedisSentinelPool(JedisConnectionFactory.java:215)

**Comment by ahzean** [comment]
Proposed sentinel provides heartbeat detection parameters

Juniper shut down the client connection per 30 Minute, the keepalive of client linux closed the client connection(every 7200s+9*75 seconds), the client MasterListener repeat create connection to sentinel, the firewall close the connection of client again, and cause server increasing connection established state.

**Comment by zpsenior** [comment]
I had the same problem. How did you solved the problem?
