### ISSUE TITLE
exception  java.net.SocketTimeoutException randomly occurs at pool.getResource()

### ISSUE THREAD

**Issue by guilhermecl** [xetorthio/jedis#1138]
I have multiple Java workers which collect data from a database, create a new thread, and puts the data on redis cache.

My issue is that, on a specific worker, I randomly get a JedisConnectionException when try to obtain a resource from pool. 

I'm kinda confused with this, because since all my workers share the same code regarding Redis and receive the same amount of data, it is weird that the exception only triggers in one of them.

I'm running Jedis client 2.7.2.

My redis-related code is the following:
```java
    Redis.java
      public Redis(){
        JedisPoolConfig config = new JedisPoolConfig();
        config.setMaxTotal(9999);
        config.setTestOnBorrow(true);
        this.clientPool = new JedisPool(config,
              Constants.Redis.IP,
              Constants.Redis.PORT,
              Constants.Redis.TIMEOUT, // timeout set to 999999
              Constants.Redis.PASSWORD);
      }   

      public Jedis getClient(){
         try{
           return clientPool.getResource();
         }
         catch(){
           return null;
         }
      }

    WorkerThread.java
     Thread(){ 
       Jedis redisClient = cacheClient.getClient();
       if (redisClient == null){ return error; }
       else{ 
           // ...
           redisClient.close();
        }
      }
```

The exception is triggered randomly when clientPool.getResource() is called.

```java
    redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.util.Pool.getResource(Pool.java:50)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:88)
        at services.Redis.getClient(Redis.java:79)
        at worker$WorkerThread.run(Worker.java:260)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: connect timed out
        at redis.clients.jedis.Connection.connect(Connection.java:148)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:75)
        at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1572)
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:69)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
        at redis.clients.util.Pool.getResource(Pool.java:48)
        ... 6 more
    Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at redis.clients.jedis.Connection.connect(Connection.java:142)
        ... 13 more
```
Any help on this would be very appreciated. 
Thanks and regards.

**Comment by marcosnils** [comment]
@guilhermecl at a first glance I see that your pool configuration seems to be very inefficient. The idea of a pool is to have a pre-configured amount of re-usable objects so you can handle workloads accordingly. 

According to your configuration having a number of 9999 doesn't seem very efficient in terms of TCP connections or memory footprint. 

Now, specifically about the timeout issue, you need to make sure that your server can handle 9999 open connections. If you're running redis in a *nix system it's likely that you're running out of file descriptors as the default open files is usually way lower than that. 

What I presume it's happening is that the OS is holding the `connect` call because all the other connections are taken and eventually you hit the 999999 timeout. Does it take a while for the application to start throwing that exception or it does it as soon as you start it?

**Comment by guilhermecl** [comment]
@marcosnils  thanks for your response.

You mean, my pool configuration is inefficient because of the settings config.setMaxTotal(9999) and Timeout 99999 ?
I just set these for testing purposes, since I wasn't expecting to reach these amount of connections right now. I will set it to a real-world value and see how it'll work, thanks for the tip.

About the timeout issue, it is really weird because I use the same settings in three different workers, and it only occurs in one of them.
Sometimes as soon as the application starts it throws exceptions, but the most commom scenario is to take a while, throw a few exceptions, works normally for a while, throw a few exceptions again, and so on. 

I'll start with setting the pool configuration with decent values and see how the application behaves. 
Thanks again for your attetion.
Regards.

**Comment by marcosnils** [comment]
@guilhermecl if only one of the workers is having problems then I believe the first to look into is the things around that specific worker like CPU / memory / iowait / steal time / etc. Remember that anything that makes the application hang will probably cause a Socketconnection exception.

**Comment by guilhermecl** [comment]
@marcosnils yes, I'll do that. Since the VM share the same settings, I'll focus on the slightly differences between the workers. The processes are pretty much equal, but I'll profile it and see if I can find something. 
I'll let you know when I find the root cause and solution.
Thanks for the help

**Comment by marcosnils** [comment]
Closing. Please re-open if you find anything that leads the problem to Jedis
