### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by PriyankaRanjan** [xetorthio/jedis#1143]
Hi,

I have just started with redis and jedis. I have installed redislabs-4.2.1-30.rhel7.x86_64 on my vm hosted on my laptop. i am trying to access that redis server through jedis 2.4.2

   Jedis jedis = new Jedis("192.168.235.129", 6379);
         jedis.set("key","value");
         System.out.println("Value is :-" + jedis.get("key"));

but i am getting 
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: connect timed out
	at redis.clients.jedis.Connection.connect(Connection.java:142)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:75)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:83)
	at redis.clients.jedis.BinaryClient.set(BinaryClient.java:92)
	at redis.clients.jedis.Client.set(Client.java:23)
	at redis.clients.jedis.Jedis.set(Jedis.java:53)
	at JedisClient.main(JedisClient.java:8)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at redis.clients.jedis.Connection.connect(Connection.java:137)
	... 6 more

Thanks in advance for your help,

**Comment by marcosnils** [comment]
@PriyankaRanjan please post this issue in the mailing list here: http://groups.google.com/group/jedis_redis. This doesn't refers to a design / code issue.
