### ISSUE TITLE
java.lang.ClassCastException by RedisInputStream.ensureFill() read data

### ISSUE THREAD

**Issue by ruanjf** [xetorthio/jedis#1144]
![image](https://cloud.githubusercontent.com/assets/509251/10996954/237397ec-84c4-11e5-8e6f-b6d4b5787cce.png)
I can't find the reason why it happened.
Use jedis 2.7.2 and jedisPool

There is data in the InputStream has not been read before I think

buf data in RedisInputStream
```
$24
http://192.168.4.166/pmc
:1

```

Exception
``` java
java.lang.ClassCastException: [B cannot be cast to java.lang.Long
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:213)
	at redis.clients.jedis.Jedis.expire(Jedis.java:247)
	at com.rongji.dfish.cache.meta.BaseMeta$2.act(BaseMeta.java:104)
	at com.rongji.dfish.cache.meta.BaseMeta$2.act(BaseMeta.java:102)
	at com.rongji.dfish.cache.RedisProvider.doAction(RedisProvider.java:96)
	at com.rongji.dfish.cache.RedisProvider.doAction(RedisProvider.java:81)
	at com.rongji.dfish.cache.meta.BaseMeta.doJedis(BaseMeta.java:138)
	at com.rongji.dfish.cache.meta.BaseMeta.expire(BaseMeta.java:102)
	at com.rongji.sso.core.security.impl.SessionServiceRedisImpl.updateExpire(SessionServiceRedisImpl.java:275)
	at com.rongji.sso.core.filter.SessionFilter.doFilter(SessionFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:745)
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.rongji.sso.server.BaseServlet.doPost(BaseServlet.java:61)
	at com.rongji.sso.server.BaseServlet.doGet(BaseServlet.java:38)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.rongji.cms.commons.filter.DispatchFilter.doFilter(DispatchFilter.java:159)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.rongji.sso.core.filter.SessionFilter.doFilter(SessionFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to [B
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:207)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:196)
	at redis.clients.jedis.Jedis.lindex(Jedis.java:925)
	at com.rongji.dfish.cache.meta.ListMeta$5.act(ListMeta.java:83)
	at com.rongji.dfish.cache.meta.ListMeta$5.act(ListMeta.java:81)
	at com.rongji.dfish.cache.RedisProvider.doAction(RedisProvider.java:96)
	at com.rongji.dfish.cache.RedisProvider.doAction(RedisProvider.java:81)
	at com.rongji.dfish.cache.meta.BaseMeta.doJedis(BaseMeta.java:138)
	at com.rongji.dfish.cache.meta.ListMeta.get(ListMeta.java:81)
	at com.rongji.sso.core.security.impl.SSOServiceImpl.getAccessHosts(SSOServiceImpl.java:30)
	at com.rongji.sso.server.SSOWebServlet.canRedirect(SSOWebServlet.java:403)
	at com.rongji.sso.server.SSOWebServlet.setLogin(SSOWebServlet.java:370)
	... 25 more

```

**Comment by marcosnils** [comment]
@ruanjf is there a chance you can provide a snippet to reproduce the error?

**Comment by ruanjf** [comment]
@marcosnils I do not know how this error occurs, there will be a period of time after starting the application.
It seems to occur when the network is unstable.
It has the opportunity to network when you close and reopen.

**Comment by marcosnils** [comment]
@ruanjf are you sure there's no possibility that the Jedis instance is being used by another thread accidentally?. I've experienced network instability in the past and usually when that happens I get connection exceptions but not ClassCast. 


TCP usually takes care of packet re transmission so that shouldn't be a problem. 

I'd be nice to see what "buf" is returning. Maybe that will be us a clue why something else is coming in the buffer.

**Comment by marcosnils** [comment]
@ruanjf ping?

**Comment by ruanjf** [comment]
@marcosnils I still can not find why it happened

**Comment by ruanjf** [comment]
@marcosnils code snippet

```java
public interface RedisOper<T> {
	T act(Jedis jedis);
}
```

```java
public static <T> T doAction(RedisOper<T> oper, JedisPool jedisPool) {
		if (oper != null && jedisPool != null) {
			Jedis jedis = jedisPool.getResource();
			if (jedis != null) {
				try {
					return oper.act(jedis);
				} finally {
//					getJedisPool().returnResource(jedis);
					if (jedis != null) {
						jedis.close();
					}
				}
			}
		}
		return null;
	}

public Long expire(final Integer seconds) {
		return doJedis(new RedisOper<Long>() {
			public Long act(Jedis jedis) {
				return jedis.expire("id", seconds);
			}
		});
	}
```

Use Case
```java
xxx.expire(100);
```

**Comment by ruanjf** [comment]
@marcosnils it not cleanup `count` and `limit` after Exception

**Comment by marcosnils** [comment]
@ruanjf could you reproduce the error again?. Did you see what the "buf" variable was holding?

**Comment by ruanjf** [comment]
@marcosnils I can‘t reproduce the error again.  now i run it in the dev environment. holp it happen.
it was happened in produce environment. not in dev

**Comment by ruanjf** [comment]
@marcosnils is the code snippet wrong?.

**Comment by marcosnils** [comment]
I'll close this issue until it can be reproduced.

**Comment by minazali** [comment]
I'm facing similar problem - 
[debug] - application - java.lang.Long cannot be cast to [B

In Connection.java
public Long getIntegerReply() {
        this.flush();
        --this.pipelinedCommands;
        return (Long)Protocol.read(this.inputStream); // Throws ClassCastException
}

Sometime Protocol.read(this.inputStream) returns byte[], And hence throws ClassCastException.

**Comment by spccold** [comment]
`socket.setReuseAddress(true) ???`
