### ISSUE TITLE
JedisException: Could not return the resource to the pool

### ISSUE THREAD

**Issue by icoderman** [xetorthio/jedis#1153]
Hi, I'm investigating how to use Redis for caching, but stuck with a problem in the [simple app](https://github.com/icoderman/SpringExamples/tree/master/SpringCaching_RedisCacheManager). I'm not sure that my configuration is correct, but the app works fine with jedis 2.6.3 and doesn't work on latest versions (2.7.2, 2.7.3). Thanks.

jedis 2.7.3:
```
Exception in thread "main" redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:90)
	at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:111)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:126)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:12)
	at org.springframework.data.redis.connection.jedis.JedisConnection.close(JedisConnection.java:257)
	at org.springframework.data.redis.core.RedisConnectionUtils.releaseConnection(RedisConnectionUtils.java:206)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:205)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:153)
	at org.springframework.data.redis.cache.RedisCache.put(RedisCache.java:140)
	at org.springframework.data.redis.cache.RedisCache.put(RedisCache.java:125)
	at org.springframework.cache.interceptor.CacheAspectSupport$CachePutRequest.apply(CacheAspectSupport.java:459)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:226)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:181)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:60)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy18.findOne(Unknown Source)
	at com.icoderman.app.Main.main(Main.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:643)
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:88)
	... 22 more
```
Jedis 2.7.2:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:252)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:58)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:128)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:91)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:78)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:178)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:153)
	at org.springframework.data.redis.cache.RedisCache.get(RedisCache.java:104)
	at org.springframework.data.redis.cache.RedisCache.get(RedisCache.java:90)
	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:308)
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:279)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:201)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:181)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:60)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy18.findOne(Unknown Source)
	at com.icoderman.app.Main.main(Main.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.NullPointerException
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:452)
	at org.springframework.data.redis.connection.jedis.JedisConnection.<clinit>(JedisConnection.java:108)
	... 23 more
```

**Comment by HeartSaVioR** [comment]
@icoderman 
Hi! Could you file a issue to Spring Data Redis - https://jira.spring.io/browse/DATAREDIS, too?
I feel it is not just Jedis bug, since we didn't see that issue earlier.

**Comment by icoderman** [comment]
Hi @HeartSaVioR, thank you for quick response. Looks like the problem was really with Spring Data Redis - I have used old version 1.5.0 in my project, but after updating to 1.6.1 everything works correctly. Thank you!
