### ISSUE TITLE
Could not get a resource from the pool

### ISSUE THREAD

**Issue by ankitbhatia8993** [xetorthio/jedis#1159]
Couldn't resolve the issue by given solutions. Please help. Tried increasing timeout, still facing same issue.

-------------------------------------------------------------------------------------------------------------------------------------------
**redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool**
	at redis.clients.util.Pool.getResource(Pool.java:50)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:86)
	at com.abc.commons.cache.redis.RedisWithFailoverCacheManager.switchMaster(RedisWithFailoverCacheManager.java:133)
	at com.abc.commons.cache.redis.RedisMonitor.run(RedisMonitor.java:46)
**Caused by: java.lang.IllegalStateException: Pool not open**
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:662)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:412)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:48)
	... 3 more
**23-Nov-2015 18:27:55.811 INFO [Thread-8] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.abc.commons.cache.redis.RedisWithFailoverCacheManager$RecoveryThread]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.abc.commons.cache.redis.RedisWithFailoverCacheManager$RecoveryThread]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.**
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1313)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at com.abc.commons.cache.redis.RedisWithFailoverCacheManager.switchMaster(RedisWithFailoverCacheManager.java:161)
	at com.abc.commons.cache.redis.RedisMonitor.run(RedisMonitor.java:46)

**Comment by liujg** [comment]
i guess your code may close() the pool before you borrow()

**Comment by marcosnils** [comment]
@ankitbhatia8993 as @liujg says, seems like you're closing the pool somewhere and after that you're trying to obtain a new instance from the closed pool. Unfortunately we can't provide further help as you gave us very little info to work with. Please provider further info (ideally a reproducible scenario) so we can assist.

I'll close the issue and reopen whenever you update it

**Comment by likaiqing** [comment]
I also have the case when I reused a cleared pipeline by accident with redis server version 2.8.19, but with redis server version 2.8.22 it is sucessful

**Comment by tongweitao** [comment]
I have meet  this error twice，when my application is starting , but there is no log for me to find the place where close this pool , i am sure there is no code in my application closing the pool。 My solution is restart the application, and then run normally
