### ISSUE TITLE
redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool

### ISSUE THREAD

**Issue by henry20100102** [xetorthio/jedis#1163]
redis server is redis3.0.5,   jedis version is 2.7.2： 

redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:85)
	at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:98)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:113)
	at redis.clients.jedis.JedisClusterConnectionHandler.returnConnection(JedisClusterConnectionHandler.java:20)
	at redis.clients.jedis.JedisClusterCommand.releaseConnection(JedisClusterCommand.java:95)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:85)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:29)
	at redis.clients.jedis.JedisCluster.hincrBy(JedisCluster.java:381)
	at cn.com.carsmart.obd.common.cache.redisimpl.DataAcquireCacheManagerImpl.notifyGps(DataAcquireCacheManagerImpl.java:232)
	at cn.com.carsmart.obd.gps.GpsDataController.processGpsData(GpsDataController.java:159)
	at cn.com.carsmart.iobd.parser.C1DataParser.parseGpsData(C1DataParser.java:930)
	at cn.com.carsmart.iobd.parser.C1DataParser.parseData(C1DataParser.java:252)
	at cn.com.carsmart.iobd.message.MessageConsumer.receiveMessage(MessageConsumer.java:238)
	at cn.com.carsmart.obd.handler.KafkaPlatformHandler$ProcessDataThead.run(KafkaPlatformHandler.java:57)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:643)
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:83)
	... 16 more

**Comment by marcosnils** [comment]
@henry20100102 please check https://github.com/xetorthio/jedis/search?q=%22not+currently+part+of+this+pool%22&type=Issues&utf8=%E2%9C%93 and reopen after investigating with further information to assist you. We can't do much with just a stacktrace, we need to understand how you're using jedis / jedispool in your app to give some useful feedback.
