### ISSUE TITLE
Getting Exception in Jedis

### ISSUE THREAD

**Issue by JinuSanthRose** [xetorthio/jedis#1184]
I am getting the following exceptions while accessing Jedis sometimes.
Exception 1:
java.lang.ClassCastException: java.lang.Long cannot be cast to [B
at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:204)
at redis.clients.jedis.Connection.getBulkReply(Connection.java:193)
at redis.clients.jedis.Jedis.get(Jedis.java:89)
Exception 2:
redis.clients.jedis.exceptions.JedisDataException: ERR Protocol error: invalid bulk length
at redis.clients.jedis.Protocol.processError(Protocol.java:113)
at redis.clients.jedis.Protocol.process(Protocol.java:131)
at redis.clients.jedis.Protocol.read(Protocol.java:200)
at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:285)
at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:204)
at redis.clients.jedis.Connection.getBulkReply(Connection.java:193)
at redis.clients.jedis.Jedis.get(Jedis.java:89)
Can anyone help me to resolve this?

**Comment by marcosnils** [comment]
@JinuSanthRose this type of problem has been reported several times and it's usually because users don't read the documentation. Please look for error in the Jedis repo and mailing list and you'll find tons of information about how to diagnose / fix.

https://github.com/xetorthio/jedis/search?utf8=%E2%9C%93&q=%22cannot+be+cast+to%22+is%3Aclosed&type=Issues
