### ISSUE TITLE
SocketTimeoutException using jedis 2.7.2

### ISSUE THREAD

**Issue by ishare** [xetorthio/jedis#1190]
I use jedis 2.7.2, and call `pool.getResource();` to get jedis, and close after using it. 
But I met SocketTimeoutException exception, happened about 0.5% possibility. There might not be network problem, because using other language driver didn't meet this exception.
Could you help me solve it? 

The pool configurations as bellow.
TIME_OUT=6
```
JedisPoolConfig poolConfig = new JedisPoolConfig();
poolConfig.setMaxTotal(2048);
poolConfig.setMaxIdle(512);
poolConfig.setMaxIdle(1024);
pool = new JedisPool(poolConfig, HOST, PORT, TIME_OUT);
```

```
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:201)
        at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
        at redis.clients.jedis.Protocol.process(Protocol.java:132)
        at redis.clients.jedis.Protocol.read(Protocol.java:196)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:288)
        at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:207)
        at redis.clients.jedis.BinaryJedis.get(BinaryJedis.java:157)
        at org.elasticsearch.linkedin.nativescript.relation.MyRedisPool.getBytes(MyRedisPool.java:103)
        at org.elasticsearch.linkedin.nativescript.relation.Relationship.getFriendScore(Relationship.java:301)
        at org.elasticsearch.linkedin.nativescript.script.PeopleRankingScript.run(PeopleRankingScript.java:136)
        at org.elasticsearch.script.AbstractSearchScript.runAsDouble(AbstractSearchScript.java:142)
        at org.elasticsearch.common.lucene.search.function.ScriptScoreFunction.score(ScriptScoreFunction.java:100)
        at org.elasticsearch.common.lucene.search.function.FunctionScoreQuery$FunctionFactorScorer.innerScore(FunctionScoreQuery.java:170)
        at org.elasticsearch.common.lucene.search.function.CustomBoostFactorScorer$AnyNextDoc.score(CustomBoostFactorScorer.java:133)
        at org.elasticsearch.common.lucene.search.function.CustomBoostFactorScorer.score(CustomBoostFactorScorer.java:71)
        at org.apache.lucene.search.ScoreCachingWrappingScorer.score(ScoreCachingWrappingScorer.java:49)
        at org.elasticsearch.common.lucene.MinimumScoreCollector.collect(MinimumScoreCollector.java:56)
        at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:193)
        at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:163)
        at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:35)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:621)
        at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:491)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:448)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:281)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:269)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:157)
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:301)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:312)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.net.SocketInputStream.read(SocketInputStream.java:127)
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:195)
        ... 34 more
```

**Comment by varrix** [comment]
```
poolConfig.setMaxIdle(512);
poolConfig.setMaxIdle(1024);
```

Why twice? Also, the `timeout` is in milliseconds as far as I know. Try using `2000` which is 2 seconds. This is the default, if it is not long enough, increase it until working and within acceptable timeout range.

**Comment by ishare** [comment]
setMaxIdle twice is by mistake, but not matter because the latter would overwrite. 
Thanks, I'll try increase timeout, mistake by `public Jedis(final String host, final int port, final int timeout)` http://stackoverflow.com/questions/14993644/configure-jedis-timeout

**Comment by varrix** [comment]
Any update?

**Comment by jesicacornejo** [comment]
Any solution?

**Comment by ishare** [comment]
@varrix is right, increase the timeout would be fine, `timeout is in milliseconds` at this point.

**Comment by ishare** [comment]
@varrix is right, increase the timeout would be fine, timeout is in milliseconds at this point.

**Comment by tain198127** [comment]
I got the same issue,  so, is there any solution? And how you overcome this problem?

**Comment by ggivo** [comment]
@tain198127 
A SocketTimeoutException: Read timed out means the client sent a request, waited up to the configured timeout, and didn’t receive a reply in time.

In this particular issue, the root cause was a misconfigured timeout: TIME_OUT = 6 was interpreted as 6 milliseconds, which is far too low and caused the timeouts. Increasing the timeout resolved it.

Note that this report is from a very old Jedis version that is no longer maintained. If you are seeing something similar, please upgrade to the latest Jedis release and use a reasonable timeout.
