### ISSUE TITLE
JedisPool Cannot Get Resource

### ISSUE THREAD

**Issue by 20zinnm** [xetorthio/jedis#1196]
I'm writing a Spigot Plugin, but for some weird reason I'm getting this error:
```
me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at me.meyerzinn.buildaprefix.shaded.redis.clients.util.Pool.getResource(Pool.java:50) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.JedisPool.getResource(JedisPool.java:99) ~[?:?]
	at me.meyerzinn.buildaprefix.database.Redis.setPrefix(Redis.java:15) ~[?:?]
	at me.meyerzinn.buildaprefix.listeners.ChatListeners.onPlayerInFactoryChatEvent(ChatListeners.java:47) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	... 11 more
Caused by: me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Can't assign requested address
	at me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.Connection.connect(Connection.java:164) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.BinaryClient.connect(BinaryClient.java:80) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1676) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:87) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:836) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:434) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.util.Pool.getResource(Pool.java:48) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.JedisPool.getResource(JedisPool.java:99) ~[?:?]
	at me.meyerzinn.buildaprefix.database.Redis.setPrefix(Redis.java:15) ~[?:?]
	at me.meyerzinn.buildaprefix.listeners.ChatListeners.onPlayerInFactoryChatEvent(ChatListeners.java:47) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	... 11 more
Caused by: java.net.ConnectException: Can't assign requested address
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_65]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_65]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_65]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_65]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_65]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_65]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.Connection.connect(Connection.java:158) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.BinaryClient.connect(BinaryClient.java:80) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1676) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:87) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:836) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:434) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.util.Pool.getResource(Pool.java:48) ~[?:?]
	at me.meyerzinn.buildaprefix.shaded.redis.clients.jedis.JedisPool.getResource(JedisPool.java:99) ~[?:?]
	at me.meyerzinn.buildaprefix.database.Redis.setPrefix(Redis.java:15) ~[?:?]
	at me.meyerzinn.buildaprefix.listeners.ChatListeners.onPlayerInFactoryChatEvent(ChatListeners.java:47) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	... 11 more
```
when using this code:
```
@Override
	public String getPrefix(String uuid) {
		Jedis jedis = null;
		try {
			jedis = pool.getResource();
			jedis.auth(auth);
			return (jedis.hget("bap", uuid) == null)
					? ChatColor.translateAlternateColorCodes('&', getPlugin().getConfig().getString("default"))
					: ChatColor.translateAlternateColorCodes('&', jedis.hget("bap", uuid));
		} finally {
			jedis.close();
		}
	}
```
```
pool = new JedisPool(new JedisPoolConfig(), plugin.getConfig().getString("database.redis.ip"),
				plugin.getConfig().getInt("database.redis.port"));
```
No errors until I try to create a resource. I've confirmed that I can connect via ```redis-cli```.

**Comment by 20zinnm** [comment]
Oh, also there's a NPE before that but I omitted that because it's not the root cause.

**Comment by 20zinnm** [comment]
!I was dumb and in the YAML put an integer in quotes. Not a Jedis issue, a dummy issue.
