### ISSUE TITLE
[jedis v2.7.3/commons-pool2 v2.4.1] JedisConnectionException: Could not get a resource from the pool 

### ISSUE THREAD

**Issue by varrix** [xetorthio/jedis#1198]
Hi, I currently make use of `Jedis` within my team to use Redis as a message broker for cross-machine/network communication.

Here's info on the project's dependencies related to Jedis:
> // Java Redis client
> 'redis.clients:jedis:2.7.3'
> // Apache Commons-Pool2 for Jedis pooling
> 'org.apache.commons:commons-pool2:2.4.1'

I use `JedisPool` with the following configuration:
```
# Jedis related properties
jedis:
  # Pool related properties
  pool:
    # Timeout for connections in milliseconds
    timeout: 6000
    # The cap on the number of "active" instances in the pool.
    max-total: 8
    # The minimum number of "idle" instances in the pool.
    min-idle: 1
    # The cap on the number of "idle" instances in the pool.
    max-idle: 4
    # Specifies the minimum amount of time that an object may sit idle in the pool before it is eligible for eviction
    # due to idle time. Apache default = 1800000 (30 min), our default = 900000 (15 min).
    min-evictable-idle-time-millis: 900000
    # Indicates how long the eviction thread should sleep before "runs" of examining idle objects.
    time-between-eviction-runs-millis: 30000
    # Sets whether the pool has LIFO (last in, first out) behaviour with respect to idle objects.
    lifo: false
    # Sets whether to block when borrowing from the pool if the pool is exhausted.
    block-when-exhausted: true
    # Any testing settings
    tests:
      # The max number of objects to examine during each run of the idle object evictor thread (if any).
      # When a negative value is supplied, ceil(getNumIdle())/abs(getNumTestsPerEvictionRun()) tests will be run.
      # When the value is positive, the number of tests actually performed in each run will be the minimum of this
      # value and the number of instances idle in the pool.
      num-tests-per-eviction-run: -1
      # Sets whether objects borrowed from the pool will be validated before being returned borrowing.
      on-borrow: false
      # Sets whether objects created for the pool will be validated before being returned from borrowing.
      on-create: false
      # Sets whether objects borrowed from the pool will be validated when they are returned to the pool.
      on-return: false
      # Sets whether objects sitting idle in the pool will be validated by the idle object evictor.
      while-idle: false
```
I have a state dumper and config dumper that has helped me confirm that the above is in fact in memory and being used by the `JedisPool` (I do this via `JedisPoolConfig`).

I have set the `timeout` to 6000 in hopes to solve my issue, although it has done nothing. On our `DEV` network we pull around `0ms-1ms` entry creations, retrievals, and deletions. On our `LIVE` network, we get roughly the same give or take `1-2ms` (I have never seen it go higher than `2ms`). We pull messages asynchronously every `1s` and then process them accordingly.

That's the background of our setup for one of our instances. Now, here's the issue I'm running into.

On our `DEV` network- which is an isolated machine connecting to its local database (redis), I can not reproduce this. On our `LIVE` network I get the issue more often than not, but it still doesn't _always_ happen. I have not encountered this after any long running applications, only immediately after startup (so I don't believe its a long running issue).

Calling `Jedis jedis = pool().getResource()` (even in a try-with-resource) sometimes at the start of one of our instances it generates the following:
```
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:50)
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:99)
    at <private>.Private.retrieveEntry(Private.java:331)
    at <private>.Private.retrievePayload(Private.java:199)
    at <private>.Private.getAllPayloads(Private.java:246)
    at <private>.PrivateHandler.pullAndCacheForServerOn(PrivateHandler.java:259)
    at <private>.PrivateHandler.pullAndCacheAll(PrivateHandler.java:239)
    at <private>.PrivateHandler$PrivateSyncTask.onInterval(PrivateHandler.java:367)
    at <private>.RepeatingTaskHandler.run(RepeatingTaskHandler.java:94)
    ... 5 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: connect timed out
    at redis.clients.jedis.Connection.connect(Connection.java:164)
    at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:82)
    at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1641)
    at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:85)
    at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
    at redis.clients.util.Pool.getResource(Pool.java:48)
    ... 13 more
Caused by: java.net.SocketTimeoutException: connect timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at redis.clients.jedis.Connection.connect(Connection.java:158)
    ... 20 more
```

From what I can tell, it does not connect in time? Although I did not have this issue before... Which is why it's strange. If there's anything odd with my configuration please let me know. As well, if anyone could give me any advice on the situation.

Let me know if you require any code- please be as specific as you can if you don't mind (ie: show me the methods you use to pull, show me the task you use you call the pull method etc) as the source is closed and I need to be selective with what I display.

**EDIT 01/21/2016 @ 9:36pm EST**
Might I add that there are roughly `21` machines where 8 run roughly 1 instance with high load (but run the exact same code perfectly) and the rest run _more_ instances with less connection load spread across but have the above issue.

Each instance connects to the same database hosted on one of those 21 machines (essentially our monolith- but not really).

**EDIT 01/21/2016 @ 10:22pm EST**
`Jedis` instances are all retrieved from the `JedisPool` via `try-with-resource` statements in `Java 8`.

**EDIT 01/22/2016 @ 2:31am EST**
Updated issue; dropped mention of error reoccurring as that is a given when the task that generated the error is continuing to run (not the solution- just clarification). The error happens when calling `Jedis jedis = pool().getResource()` (even in a try-with-resource).

**Comment by varrix** [comment]
Resolved. Ended up being an `ip-tables` issue.
