### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException: no reachable node in cluster

### ISSUE THREAD

**Issue by wenxuanguan** [xetorthio/jedis#1201]
I have 3 nodes redis cluster, and I send command exist several times in the application, one of these requests throws  exception:
~~~
redis.clients.jedis.exceptions.JedisConnectionException: no reachable node in cluster
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:46)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:45)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:71)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:32)
	at redis.clients.jedis.JedisCluster.exists(JedisCluster.java:72)
	at util.JedisClusterUtil.exists(JedisClusterUtil.java:59)
~~~
what confuse me most is **other requests before and after it get response from cluster**
I have check the redis log and found nothing

### env:
Jedis 2.5.1
redis 3.0.3

Thanks!

**Comment by marcosnils** [comment]
@wenxuanguan can you please try with latest jedis version 2.8.x?
