### ISSUE TITLE
Jedis Connection Unavailable exception

### ISSUE THREAD

**Issue by rajasuba** [xetorthio/jedis#1212]
## Scenario:

Consider a server X with redis cache and A,B,C are the clients accessing data from X's redis cache. The Client C frequently gets "Jedis Connection Unavailable" exception. 

### Client configurations to access X's redis cache:

1. redispool = poolname
2. maximum_active_connection = 8 [We had 8 initially then we increased it to 16 after client C facing this exception but still we are facing this]
3. readtimeout = 2000 milliseconds 

Kindly help me to resolve the following exception with jedis.

### Exception : 

```

 Exception : Jedis Connection Unavailable
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:42)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:84)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:10)
	at com.xyz.cache.cg.RedisConnectionPoolHandler.getRedisConnection_(RedisConnectionPoolHandler.java:121)
	at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at com.xyz.instrument.InstrumentValve.invoke(InstrumentValve.java:55)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:394)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
 org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:447)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361)
	at 

 redis.clients.util.Pool.getResource(Pool.java:40)
```

PS: Clients A, B, and C have their own redis cache.

**Comment by marcosnils** [comment]
@rajasuba is client C the only one getting this exception?. If it does, I guess there should be a problem with that client specifically.

**Comment by varrix** [comment]
Please make sure that if the client's are on different machines they are whitelisted in the host (`iptables` etc).

**Comment by rajasuba** [comment]
@marcosnils The other clients(A,B) do not face this issue. The server X (whose get/set call in redis is more than client C) gets this exception in very meager amount whereas client C (performs only get) faces this exception often.

**Comment by rajasuba** [comment]
@varrix The client's are different servers and they run on different machine.

**Comment by marcosnils** [comment]
@rajasuba have you consider that it's maybe a problem related to client C machine?. Can you try running C on a different machine to see if that improves the situation?

**Comment by rajasuba** [comment]
@marcosnils The Client C which is a server runs on different machines and they face this problem.

**Comment by sheinbergon** [comment]
@rajasuba how did this end up. Was this issue resolved ?

**Comment by marcosnils** [comment]
I'll close due to inactivity

**Comment by rajasuba** [comment]
@sheinbergon The issue didn't get solved yet. Have tried increasing the maximum_active_connection from 8 to 16 for client C. But still I'm getting the above exception.

**Comment by huantt** [comment]
@rajasuba ra did you close the resource?

**Comment by rajasuba** [comment]
yes I do @huantt .

**Comment by huantt** [comment]
@rajasuba can you send to me your project?

**Comment by marcosnils** [comment]
It's likely that the problem relies somewhere in the code which is not returning the borrowed objects correctly.
