### ISSUE TITLE
redis.clients.jedis.exceptions.JedisMovedDataException: MOVED

### ISSUE THREAD

**Issue by yin-bp** [xetorthio/jedis#1245]
jedis to operate a redis shared cluster：
  
```
List<JedisShardInfo> jedisClusterNode = new ArrayList<JedisShardInfo>();
	    jedisClusterNode.add(new JedisShardInfo("10.0.15.134", 6379));
	    jedisClusterNode.add(new JedisShardInfo("10.0.15.134", 6380));
	    jedisClusterNode.add(new JedisShardInfo("10.0.15.134", 6381));
	    jedisClusterNode.add(new JedisShardInfo("10.0.15.134", 6382));
	    jedisClusterNode.add(new JedisShardInfo("10.0.15.160", 6379));
	    jedisClusterNode.add(new JedisShardInfo("10.0.15.160", 6380));
	    jedisClusterNode.add(new JedisShardInfo("10.0.15.160", 6381));
	    jedisClusterNode.add(new JedisShardInfo("10.0.15.161", 6379));
	    jedisClusterNode.add(new JedisShardInfo("10.0.15.161", 6380));
	    jedisClusterNode.add(new JedisShardInfo("10.0.15.161", 6381));
    ShardedJedisPool pool = new ShardedJedisPool(config, jedisClusterNode);
    ShardedJedis jedis = pool.getResource();
    jedis.set("foo", "bar");
    jedis.set("test", "value");
    assertEquals("bar", jedis.get("foo"));
    jedis.close();
    pool.destroy();
```

when run test code，some exception is received：

```
redis.clients.jedis.exceptions.JedisMovedDataException: MOVED


 6918 10.0.15.161:6380
	at redis.clients.jedis.Protocol.processError(Protocol.java:110)
	at redis.clients.jedis.Protocol.process(Protocol.java:152)
	at redis.clients.jedis.Protocol.read(Protocol.java:206)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:309)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:236)
	at redis.clients.jedis.Jedis.set(Jedis.java:130)
	at redis.clients.jedis.ShardedJedis.set(ShardedJedis.java:41)
	at org.frameworkset.nosql.redis.RedisHelper.set(RedisHelper.java:78)
	at org.frameworkset.nosql.RedisTest.get(RedisTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:44)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
	at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
 
#### Jedis version:build from master after v2.8.1 
use default cluster config

**Comment by HeartSaVioR** [comment]
You should use JedisCluster for Redis Cluster, not SharedJedis(Pool).

**Comment by yin-bp** [comment]
cluster nodes
```
127.0.0.1:6379> cluster nodes
f41ab30c901ad1ab6d4e4576a6085790ea0d16a4 10.0.15.160:6379 myself,master - 0 0 10 connected 813-4112 8192-8208 12288-12304
5ddac28085678b00a04e89fa5a0b3d49b23af278 10.0.15.134:6382 master - 0 1458811307527 11 connected 0-812 4113-4924 8209-9020 12305-13116
76dfbbd882835f2b7b461bb209e2d2a05975125d 10.0.15.160:6381 master - 0 1458811308028 3 connected 13117-16383
2bd3334769e2b045c5a606a8bb0f75d445b9752e 10.0.15.134:6380 slave e0403cc75795a7a58559474b370c53c29a786d1f 0 1458811308530 8 connected
293f74ac1a62a732d6491d25fee74285f8ce1842 10.0.15.134:6381 slave 5ddac28085678b00a04e89fa5a0b3d49b23af278 0 1458811307028 11 connected
ee4dfa29b3ef50e60a782b733901c3b8160133db 10.0.15.161:6379 slave f41ab30c901ad1ab6d4e4576a6085790ea0d16a4 0 1458811308530 10 connected
2d144266da8fab7a9a9b928812a0262f8aa4e6b6 10.0.15.161:6381 slave 76dfbbd882835f2b7b461bb209e2d2a05975125d 0 1458811307028 7 connected
0e97f14811ccb0ddb5ee1d74d6877e536d74b092 10.0.15.160:6380 slave 51c73a40c3145fbc163b1f31a3575f5621eda333 0 1458811308028 6 connected
51c73a40c3145fbc163b1f31a3575f5621eda333 10.0.15.134:6379 master - 0 1458811307628 4 connected 9021-12287
e0403cc75795a7a58559474b370c53c29a786d1f 10.0.15.161:6380 master - 0 1458811309030 2 connected 4925-8191
```
I have used JedisCluster for Redis Cluster ,and that's ok:
```
GenericObjectPoolConfig config = new GenericObjectPoolConfig();
    config.setMaxTotal(30);
    config.setMaxWaitMillis(2000);
    Set<HostAndPort> jedisClusterNode = new HashSet<HostAndPort>();
    jedisClusterNode.add(new HostAndPort("10.0.15.134", 6379));
    jedisClusterNode.add(new HostAndPort("10.0.15.134", 6380));
    jedisClusterNode.add(new HostAndPort("10.0.15.134", 6381));
    jedisClusterNode.add(new HostAndPort("10.0.15.134", 6382));
    jedisClusterNode.add(new HostAndPort("10.0.15.160", 6379));
    jedisClusterNode.add(new HostAndPort("10.0.15.160", 6380));
    jedisClusterNode.add(new HostAndPort("10.0.15.160", 6381));
    jedisClusterNode.add(new HostAndPort("10.0.15.161", 6379));
    jedisClusterNode.add(new HostAndPort("10.0.15.161", 6380));
    jedisClusterNode.add(new HostAndPort("10.0.15.161", 6381));
    JedisCluster jc = new JedisCluster(jedisClusterNode, config);
    jc.set("foo", "bar");
    jc.set("test", "value");
    jc.set("52", "poolTestValue2");
    jc.set("53", "poolTestValue2");
    System.out.println(jc.get("52")); 
    System.out.println(jc.get("53")); 
    jc.close();
```
Thanks.but Why can not use SharedJedis.

**Comment by HeartSaVioR** [comment]
ShardedJedis was introduced before Redis Cluster.
You can refer the introduction to ShardedJedis here: https://github.com/xetorthio/jedis/wiki/AdvancedUsage#shardedjedis

**Comment by MrZENGLINGZHANG** [comment]
redisCluster is a single Thread to handler redis-cluster.but I  want to user thread pool to handler my redis-cluster,how to do it?

**Comment by sagarsitap596** [comment]
redisCluster is single threaded?? So Do I have to create new redisCluster instance for every thread for performance ?
