### ISSUE TITLE
ERR wrong number of arguments for 'spop' command

### ISSUE THREAD

**Issue by chuanqi** [xetorthio/jedis#1247]
### Expected behavior
I hope get the three records from the collection. and delete the three.
 
 ex:
`Set<String> removes=jedis.spop("test:set",3);`

``redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'spop' command

	at redis.clients.jedis.Protocol.processError(Protocol.java:117)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233)
	at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:226)
	at redis.clients.jedis.Jedis.spop(Jedis.java:1114)`

**Comment by marcosnils** [comment]
@chuanqi can you please provide a complete example?

Tried to reproduce this using your example but it worked as expected. It's also tested here in the Jedis test suite: 
https://github.com/xetorthio/jedis/blob/master/src/test/java/redis/clients/jedis/tests/commands/SetCommandsTest.java#L135-L167

**Comment by chuanqi** [comment]
Thanks @marcosnils .
I get it from [redis](https://github.com/MSOpenTech/redis/issues/433)
The count argument will be available in a later version and is not available in 2.6, 2.8, 3.0

**Comment by sazzad16** [comment]
It is the issue of Redis version.

In [SPOP](https://redis.io/commands/spop)
> The count argument is available since version 3.2.
