### ISSUE TITLE
Getting redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 8985 172.17.1.193:3002

### ISSUE THREAD

**Issue by Annapoornar** [xetorthio/jedis#1255]
I am using JedisPool to get the resource . The JedisPoolConfig is created as below.

	JedisPoolConfig poolConfig = new JedisPoolConfig();
		poolConfig.setMinIdle(1);
		poolConfig.setMaxIdle(5);
		poolConfig.setMaxTotal(5);
		poolConfig.setMaxWaitMillis(30000);
		return new JedisPool(172.17.0.93, 4001, 30000);

When set method is invoked on the Jedis instance (pool.getResource), its throwing the below exception

redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 14452 172.17.0.93:4003
	at redis.clients.jedis.Protocol.processError(Protocol.java:109)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:196)
	at redis.clients.jedis.BinaryJedis.set(BinaryJedis.java:120)
	at com.altisource.realdoc.capture.common.service.RedisRespository.store(RedisRespository.java:64)
	at com.altisource.realdoc.capture.common.service.CaptureDocumentRepository.editPage(CaptureDocumentRepository.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.altisource.realdoc.capture.common.service.aop.JuggernautServiceProfiler.profile(JuggernautServiceProfiler.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy45.editPage(Unknown Source)
	at com.altisource.realdoc.capture.preprocess.common.ServiceUtils$4.doWithRetry(ServiceUtils.java:194)
	at com.altisource.realdoc.capture.preprocess.common.ServiceUtils$4.doWithRetry(ServiceUtils.java:1)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:263)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:154)
	at com.altisource.realdoc.capture.preprocess.service.PreprocessService.saveEnhancedImages(PreprocessService.java:403)
	at com.altisource.realdoc.capture.preprocess.service.PreprocessService.enhanceImage(PreprocessService.java:192)
	at com.altisource.realdoc.capture.preprocess.service.PreprocessService.preprocess(PreprocessService.java:116)
	at com.altisource.realdoc.capture.preprocess.resource.PreprocessResource.processRequest(PreprocessResource.java:127)
	at com.altisource.realdoc.capture.preprocess.resource.PreprocessResource.preprocessDocument(PreprocessResource.java:87)
	at com.altisource.realdoc.capture.preprocess.endpoint.mq.RabbitMQMessageConsumer.getDocMessage(RabbitMQMessageConsumer.java:27)
	at com.altisource.realdoc.capture.preprocess.endpoint.mq.RabbitMQMessageConsumer.onMessage(RabbitMQMessageConsumer.java:23)
	at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.onMessage(MessageListenerAdapter.java:357)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:650)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:576)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:78)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:161)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1177)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:559)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:950)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:934)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$600(SimpleMessageListenerContainer.java:78)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1045)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Annapoornar** [comment]
Its a cluster setup. Please help. Thanks in advance

**Comment by Spikhalskiy** [comment]
You need to work with JedisCluster object, not pure JedisPool.

**Comment by Annapoornar** [comment]
Thanks. It worked with jediscluster

Regards
Annapoorna

On Apr 13, 2016 4:31 PM, "Dmitry Spikhalskiy" <notifications@github.com>
wrote:
>
> You need to work with JedisCluster.

object, not pure JedisPool.
