### ISSUE TITLE
REDIS CLUSTERING under failure

### ISSUE THREAD

**Issue by castroflavio** [xetorthio/jedis#1270]
I'm trying to run YCSB using JEDIS CLUSTER to benchmark redis under failure. But when a failure happens, the system goes to a failed state, and I think jedis is trowing an exception:

redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:97)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:30)
        at redis.clients.jedis.JedisCluster.hgetAll(JedisCluster.java:471)
        at com.yahoo.ycsb.db.RedisClient.read(RedisClient.java:111)
        at com.yahoo.ycsb.DBWrapper.read(DBWrapper.java:125)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionRead(CoreWorkload.java:668)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:590)
        at com.yahoo.ycsb.ClientThread.run(Client.java:329)
redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:97)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:30)
        at redis.clients.jedis.JedisCluster.hgetAll(JedisCluster.java:471)
        at com.yahoo.ycsb.db.RedisClient.read(RedisClient.java:111)
        at com.yahoo.ycsb.DBWrapper.read(DBWrapper.java:125)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionReadModifyWrite(CoreWorkload.java:708)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:602)
        at com.yahoo.ycsb.ClientThread.run(Client.java:329)
redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:97)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:30)
        at redis.clients.jedis.JedisCluster.hgetAll(JedisCluster.java:471)
        at com.yahoo.ycsb.db.RedisClient.read(RedisClient.java:111)
        at com.yahoo.ycsb.DBWrapper.read(DBWrapper.java:125)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionRead(CoreWorkload.java:668)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:590)
        at com.yahoo.ycsb.ClientThread.run(Client.java:329)

To reproduce it.

1. Start YCSB targeting a cluster.
2. Bring a node down while the workload is being generated.
3. watch it burn

**Comment by marcosnils** [comment]
@castroflavio it's normal that Jedis throws that exception because it's very probable that when while cluster is recovering several operations fail. Jedis doesn't wait for the cluster to recover it just performs the necessary redirects y fails in case it reaches a max configured value. 

JedisCluster should process requests normally after cluster recovers.

**Comment by castroflavio** [comment]
Yeah. I understand that may be a desired behavior. 

But still these errors crash my simulation.

Is there anything I could do to make it to fail silently?

**Comment by marcosnils** [comment]
@castroflavio 

can't you catch and discard the exceptions from your side?. From the design POV it's ok for Jedis to throw an exception in this cases.

**Comment by castroflavio** [comment]
Nice. Thanks. That makes sense. I made a dirty adaptation in the ycsb. I think it expects the client to return an error in this case.

So I'll just catch the exception as you said.

Do you have any example of that? (I don't have a IDE right now.)

**Comment by marcosnils** [comment]
```java
try {
//Execute JedisCluster operation
} Catch (JedisClusterMaxRedirectionsException jcmre) {
// Do nothing
}
```
