### ISSUE TITLE
JedisClusterMaxRedirectionsException when redis cluster in amazon cloud

### ISSUE THREAD

**Issue by yogeshbelur** [xetorthio/jedis#1274]
### Expected behavior

Should return the values set for the keys.

### Actual behavior

throwing following exception

redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:97)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:30)
	at redis.clients.jedis.JedisCluster.set(JedisCluster.java:60)
	at 

### Steps to reproduce:

I have 6 nodes in amazon cloud which has internal ip and public ip.
nodes are binded to internal ip
created cluster with internal ips
JedisCluster is created with public ip in our local network(not the amazon cloud)
performing set and get opertion

Suppose i change the bind to public ip i get below exception
_May 09:38:35.433 # Creating Server TCP listening socket [PUBLICIP:PORT]: bind: Cannot assign requested address_

### Redis / Jedis Configuration
bind=publicip

#### Jedis version:
2.8.0

#### Redis version:
3.4

#### Java version:
1.8

**Comment by marcosnils** [comment]
Checl https://github.com/xetorthio/jedis/issues/1268
