### ISSUE TITLE
JedisSentinelPool unable to detect the Redis master

### ISSUE THREAD

**Issue by gauthamgshet** [xetorthio/jedis#1288]
### Expected behavior

JedisSentinelPool has to detect an available Redis master

### Actual behavior

I am using the JedisSentinelPool for testing the Redis failover mechanism. Ideally I should receive the active master when I use the following code:

JedisSentinelPool pool = new JedisSentinelPool(MASTER_NAME, sentinels);
Jedis jedis = pool.getResource();

However I receive the following exception:

May 18, 2016 10:25:29 AM redis.clients.jedis.JedisSentinelPool initSentinels
INFO: Trying to find master from available Sentinels...
May 18, 2016 10:25:33 AM redis.clients.jedis.JedisSentinelPool initSentinels
WARNING: Can not get master addr, master name: MasterServerName:6381. Sentinel: Sentinel1ServerName:26379.
May 18, 2016 10:25:33 AM redis.clients.jedis.JedisSentinelPool initSentinels
WARNING: Can not get master addr, master name: MasterServerName:6381. Sentinel: Sentinel2ServerName:26379.
Exception in thread "main" redis.clients.jedis.exceptions.JedisException: Can connect to sentinel, but MasterServerName:6381 seems to be not monitored...
       at redis.clients.jedis.JedisSentinelPool.initSentinels(JedisSentinelPool.java:176)
       at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:94)
       at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:81)
       at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:69)
       at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:44)
       at jedisJmeterTest.RedisServerConnFailoverTest.main(RedisServerConnFailoverTest.java:35)

### Steps to reproduce:

Code presented above.

**Comment by marcosnils** [comment]
@HeartSaVioR ?

**Comment by gauthamgshet** [comment]
Team,

There is no issue here. I was passing the server name along with port number for MASTER_NAME. Instead I need to pass "mymaster" keyword from the sentinel.conf.

Thanks for your help!!

Regards,
Gautham
