### ISSUE TITLE
JedisConnectionException: Could not get a resource from the pool

### ISSUE THREAD

**Issue by andyzty** [xetorthio/jedis#1330]
I use spring-data-redis but it have a problem

`<dependency>
			<groupId>redis.clients</groupId>
			<artifactId>jedis</artifactId>
			<version>2.7.3</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-redis</artifactId>
			<version>1.6.4.RELEASE</version>
		</dependency>`

`Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
at redis.clients.util.Pool.getResource(Pool.java:50)
at redis.clients.jedis.JedisPool.getResource(JedisPool.java:99)
at redis.clients.jedis.JedisPool.getResource(JedisPool.java:12)
at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:155)
at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:251)
at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:58)
at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:128)
at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:91)
at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:78)
at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:178)
at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:153)
at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:86)
at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:43)`

i config is
`redis.pool.maxTotal=500
redis.pool.maxIdle=200
redis.pool.minIdle=10
redis.pool.maxWait=6000
redis.pool.testOnBorrow=false
redis.pool.testOnReturn=false`

**Comment by marcosnils** [comment]
@andyzty how are you using the JedisPool?

**Comment by sheinbergon** [comment]
@andyzty  Did you mange to resolve it ?

**Comment by marcosnils** [comment]
Closed due to inactivity.

**Comment by gowrisankar22** [comment]
I am getting a below issue, any idea to resolve this issue. 
Redis version 3.2.4

Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

**Comment by marcosnils** [comment]
@gowrisankar22 seems like Jedis can't reach your redis server. `JedisConnectionExceptions` are for connection problems between Jedis and your Redis instance. Can you check if you can reach the server using the redis CLI?

**Comment by gowrisankar22** [comment]
@marcosnils Yes, connection to redis cli works perfectly fine. 
Please check this thread with the details,
https://github.com/xetorthio/jedis/issues/1405#issuecomment-253189148

**Comment by 1leo1** [comment]
same problem holds for me as well.
I have 3 masters and 3 slaves running in docker. But unable to connect to the redis server from my java program.

I did Port forward using kubectl to port 7000.
` kubectl port-forward redis-0-334270214-fd4k0 7000:7000`

Exception:

```
> Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
> 	at redis.clients.util.Pool.getResource(Pool.java:53)
> 	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
> 	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:66)
> 	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116)
```

**Comment by 1leo1** [comment]
@gowrisankar22 were you able to fix this ?
If yes then please share the solution.

Thanks in advance!

**Comment by anandvarkeyphilips** [comment]
spring.redis.host=10.111.77.51
#usually localhost, but can also be on a LAN
spring.redis.port =6379
#usually 6379, but settable in redis.conf

When I configured my application.properties with above setup, it worked.

**Comment by mrafeeq** [comment]
@anandvarkeyphilips  yours does not seem to be a fix, but rather the default configuration   , Inspite of that configuration, i get this issue

**Comment by owenj62** [comment]
I'm also starting to face this issue using the default config, no solution as of yet. I installed redis through Brew if it makes any difference

**Comment by hotcoder** [comment]
getting this issue , how to find this issue all configurations are done properly , and i verified that am able to reach the redis server , but still the issue is comming , 

spring:
redis:
  host: trclx2001.hq.target.com
  port: 6379
  maxActiveConnections: 10


do i need to increase the number of maxActiveConnections ?
