### ISSUE TITLE
ERR Protocol error: expected '$', got ' '

### ISSUE THREAD

**Issue by Flawd** [xetorthio/jedis#1358]
Getting this error. Why? How fix? I simply execute the code one time, second time, all works fine, third time (just an example) it gives this error. after that the connection is broken.

This is line 38:  connection.getJedis().hset(key, field, object.toString());
object is i.e. an integer
```
thread "pool-4-thread-1" 
[17:05:57] [pool-4-thread-1/WARN]: redis.clients.jedis.exceptions.JedisDataException: ERR Protocol error: expected '$', got ' '
[17:05:57] [pool-4-thread-1/WARN]: 	at redis.clients.jedis.Protocol.processError(Protocol.java:117)
[17:05:57] [pool-4-thread-1/WARN]: 	at redis.clients.jedis.Protocol.process(Protocol.java:151)
[17:05:57] [pool-4-thread-1/WARN]: 	at redis.clients.jedis.Protocol.read(Protocol.java:205)
[17:05:57] [pool-4-thread-1/WARN]: 	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
[17:05:57] [pool-4-thread-1/WARN]: 	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:222)
[17:05:57] [pool-4-thread-1/WARN]: 	at redis.clients.jedis.Jedis.hset(Jedis.java:606)
[17:05:57] [pool-4-thread-1/WARN]: 	at me.FlawlezZ.FlawlordBasedSan.redis.JedisManager.hset(JedisManager.java:38)
[17:05:57] [pool-4-thread-1/WARN]: 	at me.FlawlezZ.FlawlordChaRPGSan.data.Characters$JedisCharacter.read(Characters.java:43)
[17:05:57] [pool-4-thread-1/WARN]: 	at me.FlawlezZ.FlawlordChaRPGSan.data.mongo.MongoCharacter.readCharacter(MongoCharacter.java:34)
[17:05:57] [pool-4-thread-1/WARN]: 	at me.FlawlezZ.FlawlordChaRPGSan.data.mongo.MongoCharacter.lambda$loadCharacter$0(MongoCharacter.java:43)
[17:05:57] [pool-4-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[17:05:57] [pool-4-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[17:05:57] [pool-4-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:05:57] [pool-4-thread-2/WARN]: Exception in thread "pool-4-thread-2" 
[17:05:57] [pool-4-thread-2/WARN]: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
[17:05:57] [pool-4-thread-2/WARN]: 	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:198)
[17:05:57] [pool-4-thread-2/WARN]: 	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
[17:05:57] [pool-4-thread-2/WARN]: 	at redis.clients.jedis.Protocol.process(Protocol.java:141)
[17:05:57] [pool-4-thread-2/WARN]: 	at redis.clients.jedis.Protocol.read(Protocol.java:205)
[17:05:57] [pool-4-thread-2/WARN]: 	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
[17:05:57] [pool-4-thread-2/WARN]: 	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:222)
[17:05:57] [pool-4-thread-2/WARN]: 	at redis.clients.jedis.Jedis.hset(Jedis.java:606)
[17:05:57] [pool-4-thread-2/WARN]: 	at me.FlawlezZ.FlawlordBasedSan.redis.JedisManager.hset(JedisManager.java:38)
[17:05:57] [pool-4-thread-2/WARN]: 	at me.FlawlezZ.FlawlordBasedSan.mongo.MongoPlayer.readPlayer(MongoPlayer.java:44)
[17:05:57] [pool-4-thread-2/WARN]: 	at me.FlawlezZ.FlawlordBasedSan.mongo.MongoPlayer.lambda$loadPlayer$0(MongoPlayer.java:36)
[17:05:57] [pool-4-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[17:05:57] [pool-4-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[17:05:57] [pool-4-thread-2/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by xetorthio** [comment]
Are you sharing a Jedis instance through different threads or something
like that?

**Comment by Flawd** [comment]
bless you you lead me the right way
thank you
you are very generous

i didnt read the manual, only a bad tutorial

the actual error resulted from me chaining an async jedis void into another async void. after that I encountered another error: [B can not be cast to java.lang.Long error, because I always used the same `Jedis j = pool.getResource();`

...

**Comment by marcosnils** [comment]
:+1:

**Comment by sthenusan** [comment]
how to fix this issue ?
