### ISSUE TITLE
connected_clients increases and clients don't disconnect from the server

### ISSUE THREAD

**Issue by toniclecb** [xetorthio/jedis#1362]
### Expected behavior

I am hoping the server disconnect from the clients already closed.

### Actual behavior

This is my server:
Clients
connected_clients:1447 (and increasing)
...
```
id=4129 addr=10.1.1.4:35777 fd=1002 name= age=9491 idle=9491 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=exists
id=2135 addr=10.1.1.4:55925 fd=650 name= age=20408 idle=20408 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=get
id=5118 addr=10.1.1.4:52195 fd=1251 name= age=1515 idle=1515 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=expire
```

### Steps to reproduce:
My code is:
```
JedisPoolConfig configJedis = new JedisPoolConfig();
configJedis.setTestOnBorrow(true);
configJedis.setMaxWaitMillis(5000);
jedis = new JedisPool(configJedis, "localhost");
...
// To use I am doing something like this:
Jedis jed = jedis.getResource();
if (jed != null) {
      jed.set(key, "1");
      jed.expire(key, 60);
      jed.close();
}
```

### Redis / Jedis Configuration
I changed timeout to 120, but the behaviour continues.
#### Jedis version:
2.8.1
#### Redis version:
redis_version:3.0.5

I have tried some adjusts, but without success. 
Do I need do something more than close() to disconnect the clients?

**Comment by marcosnils** [comment]
@toniclecb timeout has nothing to do here. I believe the problem is elsewhere, I've just tried your code and code I never got more than 2 clients connected.

```java
 public static void main(String[] args) throws InterruptedException {
        JedisPoolConfig configJedis = new JedisPoolConfig();
        configJedis.setTestOnBorrow(true);
        configJedis.setMaxWaitMillis(5000);
        JedisPool pool= new JedisPool(configJedis, "localhost");
        for (int i = 0; i < 5000; i++) {
            Jedis jed = pool.getResource();
            if (jed != null) {
                jed.set("lala", "1");
                jed.expire("lala", 60);
                jed.close();
            }
        }
        System.out.println("Done, waiting");
        Thread.sleep(20000);

    }
```

Can you please submit a reproducible test case?

**Comment by marcosnils** [comment]
I also tried a multi-threaded example and clients never go above 8 which is the default value used by commons-pool


```java
JedisPoolConfig configJedis = new JedisPoolConfig();
        configJedis.setTestOnBorrow(true);
        configJedis.setMaxWaitMillis(5000);
        final JedisPool pool= new JedisPool(configJedis, "localhost");

        ExecutorService executor = Executors.newFixedThreadPool(500);
        for (int i = 0; i < 20000; i++) {

            executor.execute(new Runnable() {
                @Override
                public void run() {
                    Jedis jed = pool.getResource();
                    if (jed != null) {
                        jed.set("lala", "1");
                        jed.expire("lala", 60);
                        jed.close();
                    }
                }
            });
        }
        executor.shutdown();
        while (!executor.isTerminated()) {
        }
        System.out.println("Finished all threads");
```

**Comment by toniclecb** [comment]
Hi, @marcosnils,

I also tried your multi-thread example and you are right, clients never go above 8!

I put a print after `Jedis jed = pool.getResource()` and it is printed only 19300 times.
And an error is throwed:
```
Exception in thread "pool-1-thread-35" redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:51)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:99)
	at com.mycompany.jedistest.JedisTeste2$1.run(JedisTeste2.java:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:449)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	... 5 more
```
But it's ok, I am not with this problem in production.

I will investigate a little more my code and send feedback later.

**Comment by marcosnils** [comment]
Please open a different issue with more info if you find anything.
