### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by javaxiaoz** [xetorthio/jedis#1365]
i use this jar only .m2/repository/redis/clients/jedis/2.8.1/jedis-2.8.1.jar
my jdk java version "1.7.0_75"
and my code 
public class Test {
	public static void main(String[] args) {
		Jedis jedis=new Jedis("127.0.0.1", 6379);
		jedis.set("hi", "hello world");
		String greeting = jedis.get("hi");
		System.out.println(greeting);
	}
}
and the err
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused
	at redis.clients.jedis.Connection.connect(Connection.java:164)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:80)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:100)
	at redis.clients.jedis.BinaryClient.set(BinaryClient.java:97)
	at redis.clients.jedis.Client.set(Client.java:32)
	at redis.clients.jedis.Jedis.set(Jedis.java:68)
	at com.zm.ri.giovanni.controller.Test.main(Test.java:16)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at redis.clients.jedis.Connection.connect(Connection.java:158)
	... 6 more

**Comment by javaxiaoz** [comment]
anyone help me.my god..

**Comment by bestree** [comment]
Have you started the redis server using port 6379 in the same machine? The exception indicates that the server is not in service.

**Comment by javaxiaoz** [comment]
Jedis jedis=new Jedis("127.0.0.1", 6379);
I think this is meaning that i have started the redis server with port 6379?

**Comment by javaxiaoz** [comment]
@bestree

**Comment by jiacheo** [comment]
Jedis is a client impl, not server.

**Comment by jiacheo** [comment]
set up your own server like:

>  $redis_bin/redis-server /path/to/conf/redis.conf

**Comment by javaxiaoz** [comment]
@bestree you are right,i didnt install redis right!!! now i have solved it.thank you,lol

**Comment by javaxiaoz** [comment]
install redis before use jedis.my god,why no one told me...

**Comment by javaxiaoz** [comment]
thank you again.for help me .mr bestree and mr jiacheo.

**Comment by prakashatul1** [comment]
`public class testredis  {
	
	
	public static void main(String arg[]) {
		ServerSocket socket = null;
		try {
			socket = new ServerSocket(0);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    int port = socket.getLocalPort();
	    try {
			socket.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    RedisServer redisServer = null;
		try {
			redisServer = new RedisServer(port);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    redisServer.start();
	    System.out.println("Redis Server started");
		Jedis jedis = new Jedis();
	    jedis.set("events/city/rome", "32,15,223,828");
	    System.out.println("Stored string in redis: " + jedis.get("events/city/rome"));
	    
	    jedis.flushAll();
	    System.out.println("Data Flushed");
	    System.out.println("Stored string in redis: " + jedis.get("events/city/rome"));
	    
	    redisServer.stop();
	    System.out.println("Redis Server stopped");
	    
	}
}`


> I have been using jedis with embedded redis server with the above implementation suddenly it stopped working throwing error


> Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.Connection.connect(Connection.java:207)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:126)
	at redis.clients.jedis.BinaryClient.set(BinaryClient.java:110)
	at redis.clients.jedis.Client.set(Client.java:47)
	at redis.clients.jedis.Jedis.set(Jedis.java:120)
	at com.flipkart.redis.testredis.main(testredis.java:37)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:184)
	... 6 more


> please help

**Comment by doudou20188** [comment]
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused: connect
	at redis.clients.jedis.Connection.connect(Connection.java:207)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:126)
	at redis.clients.jedis.BinaryClient.set(BinaryClient.java:110)
	at redis.clients.jedis.Client.set(Client.java:47)
	at redis.clients.jedis.Jedis.set(Jedis.java:120)
	at com.com.cskaoyan.newsproject.controller.RedisDemo.main(RedisDemo.java:12)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:184)
	... 6 more

**Comment by doudou20188** [comment]
it is my problem,why? i install redis on windows ,it can not connect when i use idea in project

**Comment by doudou20188** [comment]
Jedis jedis = new Jedis();
        String password = jedis.set("password", "123456");
        System.out.println(password);


just try to demo ,but it wrong

**Comment by babysmm** [comment]
public static void main(String[] args) {
    	//连接本地的 Redis 服务
        Jedis jedis = new Jedis("127.0.0.1",6379);
        System.out.println("连接成功");
        //查看服务是否运行
        System.out.println("服务正在运行: "+jedis.ping());
    }

Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused: connect

why? RedisDesktopManager can connect

**Comment by babysmm** [comment]
[
![image](https://user-images.githubusercontent.com/30348056/54681653-de8c2b00-4b47-11e9-8908-78c31a9d83bf.png)
](url)
