### ISSUE TITLE
Spring data redis can not use the Jedis (> version 2.1.0) 

### ISSUE THREAD

**Issue by wwwzys** [xetorthio/jedis#1372]
### Expected behavior

I want to archive "Spring data redis" with Jedis. but it will be failure when using the Jedis version (> 2.1.0) 

### Actual behavior
when use version 2.2.0
> java.lang.NoClassDefFoundError: redis.clients.jedis.BinaryTransaction

when use latest version 2.8.1

>Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'poolConfig' defined in class path resource [app.xml]: Instantiation of bean failed; nested exception is java.lang.NoClassDefFoundError: net.sourceforge.cobertura.coveragedata.TouchCollector
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1105)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at cn.com.so.Myredistest.App.main(App.java:25)
Caused by: java.lang.NoClassDefFoundError: net.sourceforge.cobertura.coveragedata.TouchCollector
	at org.apache.commons.pool2.impl.BaseObjectPoolConfig.__cobertura_init(BaseObjectPoolConfig.java)
	at org.apache.commons.pool2.impl.BaseObjectPoolConfig.<clinit>(BaseObjectPoolConfig.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:88)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
	... 13 more
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:606)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:792)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:766)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:325)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:747)

### Steps to reproduce:

Spring configuration xml:

```
 <?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:p="http://www.springframework.org/schema/p"
	xmlns:context="http://www.springframework.org/schema/context"  
    xmlns:jee="http://www.springframework.org/schema/jee" 
    xmlns:tx="http://www.springframework.org/schema/tx"  
    xmlns:aop="http://www.springframework.org/schema/aop"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/context 
        http://www.springframework.org/schema/context/spring-context.xsd">
    <context:property-placeholder location="classpath:redis.properties" />
    <!-- 
	bean test
    <context:component-scan base-package="cn.com.so.*"></context:component-scan>
    -->
    <bean id="poolConfig" class="redis.clients.jedis.JedisPoolConfig">
        <property name="maxIdle" value="${redis.maxIdle}" />  
        <property name="maxActive" value="${redis.maxActive}" />  
        <property name="maxWait" value="${redis.maxWait}" />  
        <property name="testOnBorrow" value="${redis.testOnBorrow}" />
    </bean>
    <bean id="jedisPool" class="redis.clients.jedis.JedisPool">
    	<constructor-arg ref="poolConfig" />
    	<constructor-arg type="java.lang.String" value="${redis.host}"/>
    	<constructor-arg type="int" value="${redis.port}"/>
    	<constructor-arg type="int" value="${redis.maxWait}"/>
    	<constructor-arg type="java.lang.String" value="${redis.pass}"/>
    </bean>
    <!-- Spring data Jedis start:: -->
    <bean id="connectionFactory" class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory"  
        p:host-name="${redis.host}" p:port="${redis.port}" p:password="${redis.pass}"  p:pool-config-ref="poolConfig"/>  
    
    <bean id="redisTemplate" class="org.springframework.data.redis.core.StringRedisTemplate">
        <property name="connectionFactory" ref="connectionFactory" />
    </bean>
    <!-- Spring data Jedis end:: -->
</beans>

````

#### Jedis version:
         > 2.1.0
#### Redis version:
         3.2
#### Java version:
         1.8

**Comment by marcosnils** [comment]
Plz open this issue to the spring-data project https://jira.spring.io/browse/DATAREDIS/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel

**Comment by wwwzys** [comment]
@marcosnils  thx very much.

**Comment by vlio20** [comment]
@wwwzys , were you able to solve this?
