### ISSUE TITLE
jedis  call cluster.sinter error

### ISSUE THREAD

**Issue by zhangmeng0426** [xetorthio/jedis#1415]
### Expected behavior

Exception in thread "main" redis.clients.jedis.exceptions.JedisClusterException: No way to dispatch this command to Redis Cluster because keys have different slots.
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:46)
	at redis.clients.jedis.JedisCluster.sinter(JedisCluster.java:1519)
	at org.springframework.distribute.test.BinaryJedisCluster.testSet(BinaryJedisCluster.java:217)
	at org.springframework.distribute.test.BinaryJedisCluster.main(BinaryJedisCluster.java:63)

### Actual behavior

            Random random = new Random();
		cluster.del("sSetTest");
		for(int i=0; i<10 ;i++){
			int x = random.nextInt(50);
			//set数据结构里增加一个值
			cluster.sadd("sSetTest", "test"+i+x);
		}
		
		for(int i=0; i<10 ;i++){
			int x = random.nextInt(50);
			//set数据结构里增加一个值
			cluster.sadd("sSetTest2", "test"+i+x);
		}
	 		System.out.println(cluster.sinter("sSetTest","sSetTest2"));	
           
### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.ervery time when i use sinter method,  occur exception

### Redis / Jedis Configuration
Redis cluter three master three slave,replicate 1, 
#### Jedis version:
2.9.0
#### Redis version:
3.2.3
#### Java version:
1.7

**Comment by marcosnils** [comment]
@zhangmeng0426 this is not an issue, it's important to understand how redis cluster works (http://redis.io/topics/cluster-spec) so you can get the reason of this exception.
