### ISSUE TITLE
Sentinel cluster has some bug

### ISSUE THREAD

**Issue by zhangmeng0426** [xetorthio/jedis#1431]
### Expected behavior

     I  use three machines to build one master and two slaves, three sentinel, use jedis to connect sentinel, when one sentinel down, app can not use.
    setinel :
    192.161.14.140:26379 
    192.161.14.141:26379 
    192.161.14.143:26379 
    redis:
    192.161.14.140:6379 
    192.161.14.141:6379 
    192.161.14.143:6379 

   must be recreate jedispool?   

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. down  192.161.14.140:26379 

2016-11-18 11:53:55 redis.clients.jedis.JedisSentinelPool$MasterListener run
严重: Lost connection to Sentinel at 192.161.14.140:26379. Sleeping 5000ms and retrying.
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:199)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:285)
	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:121)
	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:115)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2680)
	at redis.clients.jedis.JedisSentinelPool$MasterListener.run(JedisSentinelPool.java:291)
2016-11-18 11:54:01 redis.clients.jedis.JedisSentinelPool$MasterListener run
严重: Lost connection to Sentinel at 192.161.14.140:26379. Sleeping 5000ms and retrying.
redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused: connect
	at redis.clients.jedis.Connection.connect(Connection.java:207)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
	at redis.clients.jedis.Connection.setTimeoutInfinite(Connection.java:94)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2678)
	at redis.clients.jedis.JedisSentinelPool$MasterListener.run(JedisSentinelPool.java:291)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at redis.clients.jedis.Connection.connect(Connection.java:184)
	... 4 more

### Redis / Jedis Configuration

    public static Jedis getConnection(){
		Set<String> sentinels = new HashSet<String>();
        sentinels.add("192.161.14.140:26379");
        sentinels.add("192.161.14.141:26379");
        sentinels.add("192.161.14.143:26379");

       JedisSentinelPool pool = new JedisSentinelPool(
                "mymaster",
                sentinels
        );
       
       Jedis jedis = pool.getResource();
       
       return jedis;
   }

   public static void main(String[] args) {
		JedisServiceImpl service = new JedisServiceImpl();
		System.out.println(System.currentTimeMillis());
		Jedis jedis = JedisCommon.getConnection();
		service.setJedis(jedis);
		System.out.println(System.currentTimeMillis());
		try {
			service.setMapValue("testMap", "name", "123123");   _**//debug at this line**_
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
#### Jedis version:
2.9.0
#### Redis version:
3.2.5
#### Java version:
1.7.0

**Comment by sheinbergon** [comment]
@zhangmeng0426 not sure I understand what's the issue. Could you please try to be a bit more specific about what's the issue you're facing ? The errors above seem normal... Do they constantly repeat ? Is your Jedis client become nonoperational ?

**Comment by zhangmeng0426** [comment]
I create a static Jedis object when project starting.   In the process of the whole project alive , the Jedis Object as a singleton provide services, but when a sentinel down, this **error** will be report all the time.

**Comment by kaybinwong** [comment]
there is a gap between your application and the sentinel.if the error repeat all the time, check it carefully.

**Comment by Lalithavelusamy** [comment]
**Issue**:
redis.clients.jedis.JedisSentinelPool$MasterListener.run Lost connection to Sentinel at 192.168.0.136:26399. Sleeping 5000ms and retrying.
 redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
  
 **scenario**: Redis High Availability
 3 redis and sentinels are running. made the master down and the other replica is picked up as master and working fine in terms of redis.
 Actual behaviour:  Application is still looking at the sentinel went down and logging this error in logs.
 Expected behavior: Once the master is picked, No need to log the error as above for the sentinel which is down.
 
 can someone pls help on this?
