### ISSUE TITLE
jedis data transfer RuntimeException

### ISSUE THREAD

**Issue by linyongfu2013** [xetorthio/jedis#1449]
### Expected behavior

Write here what you're expecting ...

### Actual behavior

java.lang.RuntimeException: Reading from a byte array threw an IOException (should never happen).
	at com.dyuproject.protostuff.IOUtil.mergeFrom(IOUtil.java:52)
	at com.dyuproject.protostuff.ProtobufIOUtil.mergeFrom(ProtobufIOUtil.java:95)
	at com.leesche.zcsp.node.cache.JedisUtil.hget(JedisUtil.java:499)

Caused by: com.dyuproject.protostuff.ProtobufException: CodedInput encountered an embedded string or bytes that misreported its size.
	at com.dyuproject.protostuff.ProtobufException.misreportedSize(ProtobufException.java:81)
	at com.dyuproject.protostuff.ByteArrayInput.readString(ByteArrayInput.java:328)
	at com.dyuproject.protostuff.runtime.RuntimeUnsafeFieldFactory$9$1.mergeFrom(RuntimeUnsafeFieldFactory.java:581)
	at com.dyuproject.protostuff.runtime.MappedSchema.mergeFrom(MappedSchema.java:196)
	at com.dyuproject.protostuff.IOUtil.mergeFrom(IOUtil.java:43)
### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

#### Jedis version: 
2.7.3

#### Java version:
1.8

it happens in sometime, could anyone give me a solution?

**Comment by cpeeyush** [comment]
@linyongfu2013  I don't see much of jedis related packages and information in trace you  reported. So not able to figure out the actual issue.

Can you please provide some more jedis related information.

**Comment by marcosnils** [comment]
^. Please provide more info. If possible a reproducible case, otherwise it's super difficult to help out!.
