### ISSUE TITLE
Redis Command getting executed twice

### ISSUE THREAD

**Issue by AgarwalR3** [xetorthio/jedis#1466]
### Expected behavior

Any command or LUA script executed using jedisCluster client should get executed only once on redis.

### Actual behavior

We have seen few instances where we have tried to execute evalSha command using jedisCluster, that LUA script has got executed twice on redis.

### Steps to reproduce:

Unable to reproduce. But have seen this happen sporadically in production. No exception seen in logs.

### Redis / Jedis Configuration

Redis configuration - v3.2.1, cluster: 8 master, 8 slave (121 mapping between master and slave)

Jedis version - 2.8.1

Pool configuration - Using GenericObjectPoolConfig. MinIdle=128, MaxIdle=128, MaxTotal=128. Other attributes are default.

Java version: 1.8.0_72

**Comment by marcosnils** [comment]
@AgarwalR3 thx for reporting. We'll leave this open in case someone encounters the same situation. If you manage to get a reproducible use-case please let us know!.

**Comment by anandsaha87** [comment]
Hi @marcosnils, offlate we have been also seeing similar issue a couple of times on production. We are using Jedis 2.8.1 with redis 3.2.1 cluster. Under high load of around 4k operations/sec per node, we have observed that for sudden very short streaks of time, redis operations become very slow and few commands for eg. evalsha,hmset executed during those period tend to get executed twice. Around those period, we have also found the following exception in the logs-

Could not return the resource to the pool
redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
       at `redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:103)`
       at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:112)
       at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:12)
       at redis.clients.jedis.Jedis.close(Jedis.java:3355)
       at redis.clients.jedis.JedisClusterCommand.releaseConnection(JedisClusterCommand.java:160)
       at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:154)
       at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:30)
       at redis.clients.jedis.JedisCluster.pttl(JedisCluster.java:212)
       at com.platform.utils.redis.RedisUtils.pttl(RedisUtils.java:161)

Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
       at
org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:640)
       at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:101)
       ... 23 more
       at redis.clients.jedis.JedisClusterCommand.releaseConnection(JedisClusterCommand.java:160)
       at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:154)
       at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:30)
       at redis.clients.jedis.JedisCluster.hmget(JedisCluster.java:422)

We have tried reproducing this issue under high load in test environment but have been unable to do so. 

Thanks!

**Comment by marcosnils** [comment]
hi @anandsaha87 thx for providing further info. I'll try to run some quick examples to reproduce.

**Comment by sheinbergon** [comment]
@marcosnils  I'm guessing that for commands to be executed twice, data must be sent through the socket twice. Do we currently have such "recovery" behavior in the codebase that can cause commands to be re-sent ? it's a good place to start looking...

**Comment by yixinsiyu** [comment]
Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool?

**Comment by marcosnils** [comment]
> . Do we currently have such "recovery" behavior in the codebase that can cause commands to be re-sent ? it's a good place to start looking...

not that I'm aware of.
