### ISSUE TITLE
jedis 2.9.0, redis.clients.jedis.exceptions.JedisDataException: ERR This instance has cluster support disabled

### ISSUE THREAD

**Issue by Danny-Hazelcast** [xetorthio/jedis#1485]
jedis 2.9.0,

connecting to a Redis labs enterprise free trial 4 process / shard cluster

redis pack: redis-4.4.2

redis.clients.jedis.exceptions.JedisDataException: ERR This instance has cluster support disabled

redis.clients.jedis.exceptions.JedisDataException: ERR This instance has cluster support disabled
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:285)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:291)
	at redis.clients.jedis.Jedis.clusterSlots(Jedis.java:3376)
	at redis.clients.jedis.JedisClusterInfoCache.discoverClusterNodesAndSlots(JedisClusterInfoCache.java:54)
	at redis.clients.jedis.JedisClusterConnectionHandler.initializeSlotsCache(JedisClusterConnectionHandler.java:39)
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:17)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(JedisSlotBasedConnectionHandler.java:20)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(JedisSlotBasedConnectionHandler.java:15)
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:41)
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:83)
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:74)
I have created a 4 shard cluster running on 1 physical box, using the Redis web console.

<img width="1038" alt="screen shot 2017-03-15 at 11 32 18" src="https://cloud.githubusercontent.com/assets/5988678/23946172/01e946be-0982-11e7-98ed-abe299af5c74.png">

the redis console says its a cluster ?

when using open source redis 3.2.8, and using the redis.conf file, every thing works as expected.

port 6379
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly no

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis
