### ISSUE TITLE
How to solve JedisConnectionException

### ISSUE THREAD

**Issue by chaitan64arun** [xetorthio/jedis#1486]
Hi,

I have several applications connecting to Redis server. I see a lot of timeout exceptions from time to time. I am using the Redis Server and Jedis library with default configuration. I want to solve this exception from happening. 

There is no exception log on the redis server. Exception Log on client is
```
2017-03-14 12:04:03,996  WARN JedisSentinelPool - Cannot connect to sentinel running @ 10.xx.yy.zz:26379. Trying next one.redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: connect timed out
	at redis.clients.jedis.Connection.connect(Connection.java:155)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:83)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:94)
	at redis.clients.jedis.BinaryClient.sentinel(BinaryClient.java:1074)
	at redis.clients.jedis.Client.sentinel(Client.java:771)
	at redis.clients.jedis.Jedis.sentinelGetMasterAddrByName(Jedis.java:2786)
	at redis.clients.jedis.JedisSentinelPool.initSentinels(JedisSentinelPool.java:126)
	at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:75)
	at redis.clients.jedis.JedisSentinelPool.<init>(JedisSentinelPool.java:38)
```

The connection code I use is 
```
        JedisPoolConfig config = new JedisPoolConfig();
        config.setMaxTotal(8);
        config.setMaxIdle(8);
        config.setBlockWhenExhausted(true);

        String masterName = "";
        Set<String> sentinelHosts = //actual values;
        this.pool = new JedisSentinelPool(masterName, sentinelHosts, config);
```
Jedis version: 2.7.2
Redis version: 2.8.9
Java version: 1.8

Any help on how to debug is appreciated.

**Comment by parvathysasi** [comment]
Hi ,
I am also facing similar issues , in which we are getting JedisConnectionException because of timed out. Ours is a multi threaded environment and we are using redis extensively. We are creating the redis pool with the below config,

_JedisPoolConfig config = new JedisPoolConfig();
		config.setTestOnBorrow(true);		
		config.setMaxIdle(1000);
		config.setMaxTotal(1000);
		
		config.setBlockWhenExhausted(true);
		config.setMaxWaitMillis(180000);
		pool = new JedisPool(config, getHost(), getPort());_
Can some one please suggest?

**Comment by folochina** [comment]
mark

**Comment by sazzad16** [comment]
@chaitan64arun From `java.net.SocketTimeoutException: connect timed out`, it seems like network connectivity issue about which Jedis can't _do_ anything. But you're welcome to suggest on _handling_ it.
