### ISSUE TITLE
 java.util.ArrayList cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by zhenguang** [xetorthio/jedis#1494]
### Expected behavior

We use jedis to store our session, we normally do not have any error, however, there's an occasion that jedis distribute the session wrongly, our user got login into a different account, we restart the Tomcat and flushdb redis in order to solve the issue, however, we look at the log, there are plenty of the similar error that show below

### Actual behavior

java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Long
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265)
	at redis.clients.jedis.Jedis.exists(Jedis.java:179)
	at com.app.online.RedisOnlineManager.exists(RedisOnlineManager.java:139)
	at com.app.online.RedisOnlineManager.checkOnline(RedisOnlineManager.java:399)
	at com.app.online.OnlineInterceptor.preHandle(OnlineInterceptor.java:119)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:130)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)

### Steps to reproduce:

Unable to reproduce

### Redis / Jedis Configuration

We are using Spring beans,

	<bean id="redisOnlineManager" class="com.app.online.RedisOnlineManager>
		<property name="pool">
			<bean class="redis.clients.jedis.JedisPool">
				<constructor-arg value="redis://localhost:1234/1" />
			</bean>
		</property>
	</bean>
	
---

	private JedisPool pool;

	public void setPool(JedisPool pool) {
		this.pool = pool;
	}
	private boolean exists(String key) {
		Jedis jedis = pool.getResource();
		try {
			return jedis.exists(key);
		} finally {
			jedis.close();
		}
	}

1) We understand that redis is not thread safe, however, we are unsure if the method we apply correctly uses jedis pool and making it thread safe

#### Jedis version:
2.9
#### Redis version:
3.2
#### Java version:
Tomcat: 8 Java 8
Spring: 4.1.1

**Comment by marcosnils** [comment]
This seems right, maybe there's somewhere else in your app where you're accessing Jedis in an unsafe say. As there's no way to reproduce I'll close as there's not much we can do about it.
