### ISSUE TITLE
Jedis cluster redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?

### ISSUE THREAD

**Issue by vshalgar** [xetorthio/jedis#1500]
### Expected behavior
Data from HGET 

### Actual behavior
redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:97)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:152)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:131)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:30)
	at redis.clients.jedis.JedisCluster.hget(JedisCluster.java:392)

This is inconsistent behavior, 
Cluster works absolutely fine apart from these intermediate glitches. I am executing around 150 commands/s on the cluster. I am running the commands simultaneously from around 10 diff machines.

RedisCluster Configuration
3 Masters
3 Slaves

Jedis Configuration
maxRedirections=6
timeout=50

Jedis version: 2.8.1
Redis version: redis-3.0.7
Java version: 1.7.0_67

**Comment by marcosnils** [comment]
Seems like something's wrong with your cluster. I'd suggest trying to set redis logs to debug and check if you see something there when this happens.

**Comment by vshalgar** [comment]
8 Failures happened from 07 Apr 12:10:02.200 PM to 07 Apr 12:10:02.700 PM

Observed that, The queries which failed in that timespan were trying to fetch data form the SETs which were present on the second master. (All the queries got redirected to one master)

Nothing for that timespan on the server logs,
(Latest logs on from server logs)
10036:M 07 Apr 08:22:39.075 * 1 changes in 60 seconds. Saving...
10036:M 07 Apr 08:22:39.105 * Background saving started by pid 7517
7517:C 07 Apr 08:22:56.394 * DB saved on disk
7517:C 07 Apr 08:22:56.425 * RDB: 111 MB of memory used by copy-on-write
10036:M 07 Apr 08:22:56.545 * Background saving terminated with success
10036:M 07 Apr 08:23:57.115 * 1 changes in 60 seconds. Saving...
10036:M 07 Apr 08:23:57.146 * Background saving started by pid 7519
7519:C 07 Apr 08:24:15.248 * DB saved on disk
7519:C 07 Apr 08:24:15.277 * RDB: 11 MB of memory used by copy-on-write
10036:M 07 Apr 08:24:15.384 * Background saving terminated with success

**Comment by sazzad16** [comment]
@vshalgar May be `timeout=50` is the cause? 50 milliseconds is very small time.

**Comment by sazzad16** [comment]
Closed due to inactivity.
