### ISSUE TITLE
Failed resolution of: Ljava/lang/management/ManagementFactory;

### ISSUE THREAD

**Issue by huayicheng2015** [xetorthio/jedis#1503]
Note: I can not visit the Google Groups
### Expected behavior

No Exception raised.

### Actual behavior

```
04-18 10:06:32.811 3668-3668/com.medzone.redisson E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.medzone.redisson, PID: 3668
                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
                                                                        at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxRegister(BaseGenericObjectPool.java:876)
                                                                        at org.apache.commons.pool2.impl.BaseGenericObjectPool.<init>(BaseGenericObjectPool.java:130)
                                                                        at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:107)
                                                                        at redis.clients.util.Pool.initPool(Pool.java:44)
                                                                        at redis.clients.util.Pool.<init>(Pool.java:23)
                                                                        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:185)
                                                                        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:162)
                                                                        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:92)
                                                                        at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:61)
                                                                        at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:56)
                                                                        at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                                        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
                                                                        at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23)
                                                                        at android.view.View.performClick(View.java:5697)
                                                                        at android.widget.TextView.performClick(TextView.java:10815)
                                                                        at android.view.View$PerformClick.run(View.java:22526)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:158)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/data/app/com.medzone.redisson-1/base.apk", zip file "/data/app/com.medzone.redisson-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.medzone.redisson-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.medzone.redisson-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.medzone.redisson-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.medzone.redisson-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.medzone.redisson-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.medzone.redisson-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.medzone.redisson-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.medzone.redisson-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.medzone.redisson-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.medzone.redisson-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.medzone.redisson-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                        at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxRegister(BaseGenericObjectPool.java:876) 
                                                                        at org.apache.commons.pool2.impl.BaseGenericObjectPool.<init>(BaseGenericObjectPool.java:130) 
                                                                        at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:107) 
                                                                        at redis.clients.util.Pool.initPool(Pool.java:44) 
                                                                        at redis.clients.util.Pool.<init>(Pool.java:23) 
                                                                        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:185) 
                                                                        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:162) 
                                                                        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:92) 
                                                                        at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:61) 
                                                                        at com.medzone.redisson.redis.RedisActivity$2.call(RedisActivity.java:56) 
                                                                        at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) 
                                                                        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) 
                                                                        at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23) 
                                                                        at android.view.View.performClick(View.java:5697) 
                                                                        at android.widget.TextView.performClick(TextView.java:10815) 
                                                                        at android.view.View$PerformClick.run(View.java:22526) 
                                                                        at android.os.Handler.handleCallback(Handler.java:739) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:158) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                    	Suppressed: java.lang.ClassNotFoundException: java.lang.management.ManagementFactory
                                                                        at java.lang.Class.classForName(Native Method)
                                                                        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                        		... 24 more
                                                                     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Add jedis-2.9.0.jar into Android project app/libs directory in Android Studio, and add ```compile 'org.apache.commons:commons-pool2:2.0'``` into app/build.gradle;
2. 

``` Java
private JedisPool jedisPool;
private Jedis jedis;
RxView.clicks(binding.btnRedisConfigure).subscribe(new Action1<Void>() {
            @Override
            public void call(Void aVoid) {
                jedisPool = new JedisPool(new JedisPoolConfig(),
                        redisResult.getHost(), Integer.parseInt(redisResult.getPort()),
                        JedisConstant.TIME_OUT, redisResult.getPassword());
                jedis = jedisPool.getResource();
            }
        }, new Action1<Throwable>() {
            @Override
            public void call(Throwable throwable) {
                Toast.makeText(RedisActivity.this, throwable.getMessage(), Toast.LENGTH_LONG).show();
                finish();
            }
        });
```

### Redis / Jedis Configuration

The configuration like ```redisResult.getHost()```, ```redisResult.getPort()```, ```redisResult.getPassword()``` is to connect to the remote host for executing jedis/redis commands.

#### Jedis version:

2.9.0

#### Redis version:

I don't know since it is a remote linux host like "123.2.2.3:1234" with a connection password.

#### Java version:

1.7

#### VM

Android

**Comment by huayicheng2015** [comment]
#538

**Comment by marcosnils** [comment]
There are no plans to support Jedis in Android as correctly mentioned in #538. Not much we can do with this

**Comment by tpnet** [comment]
@huayicheng2015  Have you solved it now？
