### ISSUE TITLE
How can i use jedis cluster keys method？

### ISSUE THREAD

**Issue by stranger520** [xetorthio/jedis#1514]
ok ,i use jedis cluster keys method :
```
@Autowired
private JedisCluster jedisCluster;

Set<String> keys = new HashSet<>();
 for (Map.Entry<String, JedisPool> entry : cluster.getClusterNodes().entrySet()) {
       Jedis jedis = entry.getValue().getResource();
       Set<String> _keys =  jedis.keys(pattern);
        keys.addAll(_keys);
}
```
but ,this code throw exception,:
```
redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'KEYS'
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:276)
	at redis.clients.jedis.Jedis.keys(Jedis.java:246)
```
I don't know if I write wrong! please help me, thanks a lot!!

**Comment by marcosnils** [comment]
Please ask this question in the mailing list. github is used for design discussions and bugs mainly.

http://groups.google.com/group/jedis_redis
