### ISSUE TITLE
Could not get a resource from the pool

### ISSUE THREAD

**Issue by vanesavl** [xetorthio/jedis#1530]
I have a multithread application, where I have defined a JedisPool with next configuration:

JedisPoolConfig poolConfig = new JedisPoolConfig();
poolConfig.setMaxTotal(1000); 
poolConfig.setMaxIdle(1000); 
poolConfig.setMinIdle(16);
poolConfig.setTestOnBorrow(true); 
poolConfig.setTestOnReturn(true); 
poolConfig.setTestWhileIdle(true); 
poolConfig.setMinEvictableIdleTimeMillis(Duration.ofSeconds(60).toMillis());
poolConfig.setTimeBetweenEvictionRunsMillis(Duration.ofSeconds(30).toMillis()); 
poolConfig.setNumTestsPerEvictionRun(3); 
poolConfig.setBlockWhenExhausted(true);

The application is running in several machines so there is a JedisPool on each.

Sometimes I get the error:

redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.util.Pool.getResource(Pool.java:50)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:99)        
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: Unable to validate object
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:506)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
        at redis.clients.util.Pool.getResource(Pool.java:48)

I have set  in redis server maxclients= 99900

Jedis version: 2.8.0
Redis version: 3.2.8 

Java version: 1.8

**Comment by jingbanghu** [comment]
poolConfig.setMaxTotal(1000);
may be your client get Jedis exceed 1000,i have sufferd this problem

**Comment by marcosnils** [comment]
^. Thx @jingbanghu for providing feedback. I'll close this as it has been discussed countless times already in the issue tracker

**Comment by turkmenf** [comment]
I actually scanned through the tracker but couldn't find any specific solution to this problem. Could you please point to one matching the question here? 

Just to provide more information I configured also /etc/hosts to other available interfaces but didn't help either. I have set the parameters mentioned above, and even provided application.properties to my Spring boot application to no avail.
