### ISSUE TITLE
Could not get a resource from the pool with jedis2.4.2

### ISSUE THREAD

**Issue by shenpengyan** [xetorthio/jedis#1540]
I use jedis2.4.2 and I use JedisPool, these days there are lots of `Could not get a resource from the pool` error, when I use `JedisPool.getResource()` 
I analyze the error message and there are two types error 

Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
        at redis.clients.jedis.Protocol.process(Protocol.java:135) ~[jedis-2.4.2.jar:na]
        at redis.clients.jedis.Protocol.read(Protocol.java:191) ~[jedis-2.4.2.jar:na]
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:175) ~[jedis-2.4.2.jar:na]
        at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2132) ~[jedis-2.4.2.jar:na]
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:67) ~[jedis-2.4.2.jar:na]
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819) ~[commons-pool2-2.0.jar:2.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429) ~[commons-pool2-2.0.jar:2.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360) ~[commons-pool2-2.0.jar:2.0]
        at redis.clients.util.Pool.getResource(Pool.java:40) ~[jedis-2.4.2.jar:na]
        ... 35 common frames omitted

Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset by peer
        at redis.clients.jedis.Connection.connect(Connection.java:142) ~[jedis-2.4.2.jar:na]
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:75) ~[jedis-2.4.2.jar:na]
        at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1724) ~[jedis-2.4.2.jar:na]
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:65) ~[jedis-2.4.2.jar:na]
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819) ~[commons-pool2-2.0.jar:2.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429) ~[commons-pool2-2.0.jar:2.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360) ~[commons-pool2-2.0.jar:2.0]
        at redis.clients.util.Pool.getResource(Pool.java:40) ~[jedis-2.4.2.jar:na]
        ... 37 common frames omitted

I use it by:

    public Object execute() {
        Jedis jedis = null;
        JedisPool loPool = pool;
        try {
            jedis = loPool.getResource();
            // do something
            loPool.returnResource(jedis);
            return r;
        } catch (Throwable e) {
            loPool.returnBrokenResource(jedis);
            throw new RuntimeException(e);
        }
    }

### Redis / Jedis Configuration

My jedisPoolConfig is "
maxTotal" value="800"
"maxIdle" value="80"

#### Jedis version:

2.4.2

#### Redis version:

2.8.8

#### Java version:

1.6

Expend for your answer!!! Thank you

@malomalo @pietern @maxd @thesmith

**Comment by marcosnils** [comment]
@shenpengyan you're using an extremely old version of jedis which we don't support anymore. Any chance you can upgrade?

**Comment by shenpengyan** [comment]
@marcosnils Maybe upgrade the version can slove the problem, but I want to know why. Is there other developer ask similar question? Or do you know why `Could not get a resource from the pool` error occured when I use JedisPool.getResource() ?

**Comment by marcosnils** [comment]
@sheinbergon if you search in the issue list you'll see that many people reported the same problem but they solved it differently. As we don't support 2.4.2 anymore is really hard to tell. There's not much we can do here
