### ISSUE TITLE
JedisCluster error message while connecting 

### ISSUE THREAD

**Issue by maybhi** [xetorthio/jedis#1547]
### Expected behavior

I am getting error while connecting to AWS Redis cluster(cluster mode enabled) using JedisCluster
and also connected to redis.

here is my code,
`JedisCluster jedisCluster=null;
    	try{
		  jedisCluster=new JedisCluster(new HostAndPort("aws redis endpoint",6379));
		  System.out.println("inside try");
    	}
    	catch (Exception e) {
			// TODO: handle exception
    		System.out.println("Exception occured");
    		e.printStackTrace();
		}
	    System.out.println("jediscluster connected"+jedisCluster.getClusterNodes());
	    
	    Map<String,JedisPool> jedisClusterPool=jedisCluster.getClusterNodes();
	   
	    for(JedisPool pool:jedisClusterPool.values()){
	    	System.out.println(pool.toString());
	    	
	    }`

i am getting below output

Jul 17, 2017 9:24:25 AM redis.clients.jedis.HostAndPort getLocalHostQuietly
SEVERE: cant resolve localhost address
java.net.UnknownHostException: ip: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at redis.clients.jedis.HostAndPort.getLocalHostQuietly(HostAndPort.java:105)
	at redis.clients.jedis.HostAndPort.<clinit>(HostAndPort.java:12)
	at com.testrediscluster.App.testCluster(App.java:25)
	at com.testrediscluster.App.main(App.java:18)
Caused by: java.net.UnknownHostException: ip: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 4 more

inside try
jediscluster connected{ip=redis.clients.jedis.JedisPool@7591083d, ip=redis.clients.jedis.JedisPool@77a567e1}
redis.clients.jedis.JedisPool@7591083d
redis.clients.jedis.JedisPool@77a567e1

### Actual behavior

I am getting below error and also connected to cluster. I am getting below error which i should not get i guess,

Jul 17, 2017 9:24:25 AM redis.clients.jedis.HostAndPort getLocalHostQuietly
SEVERE: cant resolve localhost address
java.net.UnknownHostException: ip: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at redis.clients.jedis.HostAndPort.getLocalHostQuietly(HostAndPort.java:105)
	at redis.clients.jedis.HostAndPort.<clinit>(HostAndPort.java:12)
	at com.testrediscluster.App.testCluster(App.java:25)
	at com.testrediscluster.App.main(App.java:18)
Caused by: java.net.UnknownHostException: ip: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 4 more

Whats the reason for this error or Exception?

#### Jedis version:
2.9.0
#### Redis version:
3.2.4(AWS Clustered Redis)
#### Java version:
1.8

**Comment by jingbanghu** [comment]
you can ping the "aws redis endpoint",or telnet "aws redis endpoint" 6379

**Comment by zero-master** [comment]
@maybhi Please consider increasing the timeout to 60 seconds as described here: https://github.com/xetorthio/jedis/wiki/FAQ and report back the results.

**Comment by marcosnils** [comment]
@maybhi did you find a solution for this?

**Comment by sazzad16** [comment]
Closed due to inactivity.
