### ISSUE TITLE
redis cluster password problem with jedis 2.9.0

### ISSUE THREAD

**Issue by dunkcoder** [xetorthio/jedis#1570]
Can anyone help to point out the problem is?

If I set the cluster's password and configured as below picture shows, exceptions occurred,
but if I cancelled the  cluster's password and recreated it, set the password null in application.yml and the constructor of JedisCluster, everything is OK. 

`Caused by: redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:285)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:291)
	at redis.clients.jedis.Jedis.clusterSlots(Jedis.java:3376)
	at redis.clients.jedis.JedisClusterInfoCache.discoverClusterNodesAndSlots(JedisClusterInfoCache.java:54)
	at redis.clients.jedis.JedisClusterConnectionHandler.initializeSlotsCache(JedisClusterConnectionHandler.java:39)
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:17)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(JedisSlotBasedConnectionHandler.java:20)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(JedisSlotBasedConnectionHandler.java:15)
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:41)
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:83)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.createCluster(JedisConnectionFactory.java:306)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.createCluster(JedisConnectionFactory.java:280)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.afterPropertiesSet(JedisConnectionFactory.java:241)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 54 common frames omitted`

### Redis / Jedis Configuration
![image](https://user-images.githubusercontent.com/4263743/29528175-a6c3d3c0-86cd-11e7-8d25-f9f88a982512.png)

![image](https://user-images.githubusercontent.com/4263743/29529190-45f390e0-86d1-11e7-8883-c947838827d9.png)

#### Jedis version:
![image](https://user-images.githubusercontent.com/4263743/29528072-3fab7fbc-86cd-11e7-8381-85dfb844f64b.png)

#### Redis version:
➜  src redis-server --version
Redis server v=3.2.10 sha=00000000:0 malloc=libc bits=64 build=3c0ef7bf309ea807

#### Java version:
➜  src java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by dunkcoder** [comment]
Thanks very much, I fixed it myself.
1. Change redis.conf referer to this: https://github.com/xetorthio/jedis/pull/1269/files, pay attentation to this line: requirepass cluster

2. Setup cluster using redis-trib-pass.rb
https://github.com/seekasia/redis/tree/master/src/redis-trib-pass.rb

3. application.yml: password: cluster

**Comment by banbeishui** [comment]
Hi , I encounted a problem with jedis 2.9.0 and redis 2.8.19, redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'AUTH' , 
do you know the reason ?

**Comment by Madan165** [comment]
**To use Authentication with cluster you need to add latest 'jedis' i.e 
**1. Add following code in pom.xml file****

			<dependency>
			    <groupId>redis.clients</groupId>
			    <artifactId>jedis</artifactId>
			    <version>3.0.0-m1</version>
			</dependency>

**2. Next step I have written the program i.e.**

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.pool2.impl.GenericObjectPoolConfig;

import redis.clients.jedis.HostAndPort;
import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisCluster;
import redis.clients.jedis.JedisPoolConfig;
import redis.clients.jedis.JedisShardInfo;

public class JedisMain {

	public static void main(String[] args) {
		try {
		String host = "<yourhost>";//The access URL is displayed on the console.
		int port = <yourport>;
		//Authentication information
		String Pass="<yourPassword>";
		Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
		
		jedisClusterNodes.add(new HostAndPort(host, port));
		
		GenericObjectPoolConfig poolConfig =new JedisPoolConfig();
		poolConfig.setMaxTotal(20);
		poolConfig.setMaxIdle(3);
		poolConfig.setMaxWaitMillis(3000);
		poolConfig.setTestOnBorrow(true);
		JedisCluster jedis = new JedisCluster(jedisClusterNodes, 5000, 100, 10, Pass, poolConfig);
		
		String key = "name";
		String value = "dummy";
		//Set a key.
		jedis.set(key, value);
		System.out.println("Set Key " + key + " Value: " + value);
		//Get the key.
		String getvalue = jedis.get(key);
		System.out.println("Get Key " + key + " ReturnValue: " + getvalue);
		jedis.close();
		
		} catch (Exception e) {
		     e.printStackTrace();
		}
		}
	
	
	
}


**3. It gives following outupt in console. by running as Java Application**

Set Key name Value: dummy
Get Key name ReturnValue: dummy
