### ISSUE TITLE
java.lang.Long cannot be cast to java.util.List

### ISSUE THREAD

**Issue by Arraying** [xetorthio/jedis#1590]
I'm getting an exception (`java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.List`) when attempting to get a set.

### Expected behavior

I was expecting the return of an empty Set or even null if the set doesn't exist, and a regular set if it does exist.

### Actual behavior

I have an exception thrown, regardless of whether the set exists or not.

The exception comes from here: 
![Image](http://img.arraying.de/i/aj8ed0m90h.png)

Here is a stacktrace:

`Exception in thread "ForkJoinPool.commonPool-worker-1" java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.List
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:276)
	at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:269)
	at redis.clients.jedis.Jedis.smembers(Jedis.java:1123)
	at de.arraying.arraybot.data.database.templates.SetEntry.values(SetEntry.java:54)
	at de.arraying.arraybot.command.Commands.execute(Commands.kt:83)
	at de.arraying.arraybot.command.Commands$executeCommand$1.doResume(Commands.kt:69)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:235)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

### Steps to reproduce:

1. Create a Jedis object, I'm using `redis = new Jedis(configuration.getRedisHost(), configuration.getRedisPort());`

2. Simply do `redis.smembers("i");`, I called my set "i" but the name doesn't really matter, all I've tried error.

If it's useful, after creating a new Jedis object I do:
* Jedis#auth to authenticate
* Jedis#select to select the correct index

### Redis / Jedis Configuration

I've already stated my Jedis configuration, and I haven't really touched anything execpt for the bind and password in my Redis config.

#### Jedis version:

2.9.0

#### Redis version:

3.0.6

#### Java version:

Currently running in a Java class in a Java 1.8/Kotlin 1.1.4-2 Gradle project.

**Comment by MSaifAsif** [comment]
Any solution to the above issue ?

**Comment by Arraying** [comment]
@MSaifAsif 

Officially no, I've gotten zero support from the actual developers. However, after reading the docs, **it solved itself once I switched to a Jedis pool.** My best guess would be the non thread safe Jedis instance screwing up in a multithreaded environment and throwing this error. But that's just my presumption.

I didn't realise this issue was still open, if that fixes it for you I'll close it.

**Comment by HeartSaVioR** [comment]
@Arraying 
Hello. Sorry to visit too late.
As you found the information from doc, Jedis instance is not thread-safe and that's why JedisPool exists. If it solves your issue could we close this? Thanks in advance.

**Comment by MSaifAsif** [comment]
@Arraying Yes you are absolutely right, that solved the problem. 
@HeartSaVioR Ah I understand better now, makes sense why JedisPool exists. Should've gone through the docs myself as well. Thanks for the information. We can close this .
