### ISSUE TITLE
JedisCluster hangs entire threads sharing the same JedisCluster when the redis is temporarily overloaded.

### ISSUE THREAD

**Issue by PeterStayPool** [xetorthio/jedis#1620]
### Expected behavior

Threads using the same JedisCluster should not hang.

### Actual behavior

Over 400 threads sharing the JedisCluster hung stopping the entire application

### Steps to reproduce:

1. create an multithread application sharing the same jedisCuster. (maxTotal for GenericObjectPoolConfig was 10).
2. put enough load on Redis cluster causing cluster nodes's CPU top 100%
3. let the application to get/set values until the applications' threads get stuck.

### Redis / Jedis Configuration

15 shards per cluster with 1 replica per each shard.

#### Jedis version:
2.9
#### Redis version:
3.2
#### Java version:
1.8.0

After examining the thread dump and the code, the reason for hang was due to the exhaustion of the Jedis connections of the pool.

Here is the analysis of the thread dump.

It was the deadlock caused by the exhaustion of the JedisPool.
JedisPool uses a GenericObjectPool, which uses LinkedBlockingDequeue.

To access the JedisPool, one of two locks needs to be acquired, Either read lock or write lock of ReentrantReadWriteLock.

One thread (Thread 88) was sleeping on on the GenericObjectPool.borrowOjbect after acquiring a write lock because the pool was empty. --> This was caused because the pool for the slot did not exists, which is unusual as the author quoted.
```
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000002c5412050> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:524)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:438)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redis.clients.jedis.JedisClusterInfoCache.renewClusterSlots(JedisClusterInfoCache.java:103)
	at redis.clients.jedis.JedisClusterConnectionHandler.renewSlotCache(JedisClusterConnectionHandler.java:52)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:135)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:141)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:141)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:141)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:141)
	at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:60)
	at redis.clients.jedis.BinaryJedisCluster.get(BinaryJedisCluster.java:98)
```

This thread was waiting on the signal in this code 

```
    public T borrowObject(long borrowMaxWaitMillis) throws Exception {
        assertOpen();
......
        while (p == null) {
            create = false;
            if (blockWhenExhausted) {
                p = idleObjects.pollFirst();
                if (p == null) {
                    create = true;
                    p = create();  --> line 434
                }
                if (p == null) {
                    if (borrowMaxWaitMillis < 0) {
                        p = idleObjects.takeFirst(); ---> this method is block method. : line438
                    } else {
                        waitTime = System.currentTimeMillis();
                        p = idleObjects.pollFirst(borrowMaxWaitMillis,
                                TimeUnit.MILLISECONDS);
                        waitTime = System.currentTimeMillis() - waitTime;
                    }
                }
```

In normal case, when the pool is empty, line 434 is executed and new Jedis is created by the JedisFactory() or throw exception (connection refuse) and line 438 is not executed.

However, when createCount is larger than maxTotal meaning there are already 10 connections created and rented out, line 434 returns null.

If these 10 connections are returned correctly, the thread sleeping on line 434 will resume.

However, this hang state was not recovered. This implies that returning to the connection to the pool had failed, which indicating the connection leakage had happened.

I saw lots of the following messages in the logs
```
redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:103) ~[jedis-2.x.jar:?]
.....
Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:633) ~[commons-pool2-2.2.jar:2.2]
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:101) ~[jedis-2.x.jar:?]
```

This this blocked 343 threads trying to acquire the read lock.
```
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <merged>(a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
	at redis.clients.jedis.JedisClusterInfoCache.getSlotPool(JedisClusterInfoCache.java:234)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:62)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116)
	at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:60)
	at redis.clients.jedis.BinaryJedisCluster.get(BinaryJedisCluster.java:98)
```

31 thread were also sleeping on the GenericObjectPool.borrowOjbect due to empty pool but no lock acquired.

```
java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <merged>(a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:524)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:438)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:66)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116)
	at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:60)
	at redis.clients.jedis.BinaryJedisCluster.get(BinaryJedisCluster.java:98)
```

**Comment by scyehan** [comment]
we also meet this problem, set borrowMaxWaitMillis can resolve

**Comment by PeterStayPool** [comment]
I also ended up setting that value but the design flaw still needs to be addressed I think.

Thank you for your advice.

**Comment by sazzad16** [comment]
@scyehan What value did you use for `borrowMaxWaitMillis`?

**Comment by jesseeuton** [comment]
I am also running into this issue.  What value should be set for borrowMaxWaitMillis?

**Comment by zackb** [comment]
Was there a resolution to this?

**Comment by playernodie** [comment]
2021 still have same issue

**Comment by sazzad16** [comment]
> ..., set borrowMaxWaitMillis can resolve

@playernodie Did you try this solution?

**Comment by loop** [comment]
@sazzad16 Where does borrowMaxWaitMillis need to be set?

**Comment by sazzad16** [comment]
@loop In the pool config (JedisPoolConfig/GenericObjectPoolConfig)

**Comment by loop** [comment]
> @loop In the pool config (JedisPoolConfig/GenericObjectPoolConfig)

This way?
```
JedisPoolConfig config = new JedisPoolConfig();
config.setMaxWaitMillis(500);
```

**Comment by sazzad16** [comment]
@loop yes
