### ISSUE TITLE
JedisPool.getResource block when redis server restart

### ISSUE THREAD

**Issue by bhsc881114** [xetorthio/jedis#1625]
### Expected behavior

because redis server RAM is not enough,our ops upgrade redis server RAM with restart，we think it's have no effect on jedis client，it's will recover automatic

### Actual behavior
but some days later  with some exceptional situation，we found JedisPool.getResource is block

"LogSpout:1-MultipleThreadSpoutExecutors" prio=10 tid=0x00002aaab8629000 nid=0x49d waiting on condition [0x000000004304e000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000079aad4c20> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
        at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:583)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:442)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
        at redis.clients.util.Pool.getResource(Pool.java:48)
        at redis.clients.jedis.**JedisPool.getResource**(JedisPool.java:86)
        at com.xxxxx.redis.RedisCountingService.getRedis(RedisCountingService.java:202)
        ..........

#### Jedis version:
2.7.2

#### Redis version:
3.0.5

**Comment by sazzad16** [comment]
@bhsc881114 Jedis 2.7 is not in development anymore. Are you still having this issue?

**Comment by sazzad16** [comment]
Closed due to inactivity.

**Comment by yanghuirong** [comment]
Thanks for the answer! I updated my Jedis from 2.7.x to Jedis 2.9.x which solved the problem.
