### ISSUE TITLE
ScanParams throw exception when count is set withe jedis 2.9

### ISSUE THREAD

**Issue by platnera** [xetorthio/jedis#1662]
Hi

while using jedis 2.9 i tried to set the count property on ScanParams object ( scanParams.count(1000) ) unfortunately NoSuchMethodError exception was thrown.

Exception in thread "main" java.lang.NoSuchMethodError: redis.clients.jedis.ScanParams.count(Ljava/lang/Integer;)Lredis/clients/jedis/ScanParams;
	at reddis.ReddisControler.scanParams(ReddisControler.java:78)
	at testScanParams.ScanParamsTest.main(ScanParamsTest.java:10)

the same code run without any problem with jedis 2.8.2

Please help me

thanks

### Expected behavior

code will run without any exception

### Actual behavior

exception was thrown:

Exception in thread "main" java.lang.NoSuchMethodError: redis.clients.jedis.ScanParams.count(Ljava/lang/Integer;)Lredis/clients/jedis/ScanParams;
	at reddis.ReddisControler.scanParams(ReddisControler.java:78)
	at testScanParams.ScanParamsTest.main(ScanParamsTest.java:10)

### Steps to reproduce:

run this function in order to reproduce.
prefix = string to search

public List<String> scanParams(String prefix) 
	{
    	List<String> result = new ArrayList<String>();
    	ScanParams scanParams = new ScanParams();
    	scanParams.count(1000); //cursor chunk-size
    	scanParams.match(prefix+'*');
    	String cur = redis.clients.jedis.ScanParams.SCAN_POINTER_START; 
    	boolean cycleIsFinished = false;
    	while( !cycleIsFinished ) {
    		ScanResult<String> scanResult = mJedis.scan( cur, scanParams);
    		List<String> cycleResult = scanResult.getResult();
    		result.addAll(cycleResult);
    		cur = scanResult.getStringCursor();
    		if (cur.equals("0")) {
    			cycleIsFinished = true;
    		}                 
    	}
       
    	return result;
    }

### Redis / Jedis Configuration
default redis configuration

#### Jedis version:
jedis version 2.9

#### Redis version:
redis_version:3.2.3

#### Java version:
jre 1.8.0_111

**Comment by sazzad16** [comment]
@platnera Sorry, couldn't help you about this. You can examine the classpath.

**Comment by jinitbansod** [comment]
i am facing the same issue can anyone help on that
Caused by: java.lang.NoSuchMethodError: redis.clients.jedis.ScanParams.count(I)Lredis/clients/jedis/ScanParams;
	at org.springframework.data.redis.connection.jedis.JedisConverters.toScanParams(JedisConverters.java:464) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisConnection$5.doScan(JedisConnection.java:3438) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.KeyBoundCursor.doScan(KeyBoundCursor.java:39) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.ScanCursor.scan(ScanCursor.java:86) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.ScanCursor.doOpen(ScanCursor.java:121) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.ScanCursor.open(ScanCursor.java:110) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisConnection.hScan(JedisConnection.java:3443) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisConnection.hScan(JedisConnection.java:3417) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultHashOperations$14.doInRedis(DefaultHashOperations.java:243) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultHashOperations$14.doInRedis(DefaultHashOperations.java:238) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:204) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:166) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:88) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultHashOperations.scan(DefaultHashOperations.java:238) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at com.globant.microservice.utils.RedisUtil.getMapMatchingKeyValues(RedisUtil.java:47) ~[bin/:na]

**Comment by ShiwaniSinha** [comment]
Hi, I am also getting similar issue.The class is there on the classpath and even I could see method count but still getting the error.Can someone help with the solution?
