### ISSUE TITLE
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to [B

### ISSUE THREAD

**Issue by TheMajster** [xetorthio/jedis#1664]
Welcome.

Code
`public class Redis {
    private JedisPool pool;
    private String ip;
    private int port;
    private String pass;

    public Redis(String ip, int port, String pass){
        this.ip = ip;
        this.port = port;
        this.pass = pass;
        this.pool = new JedisPool(this.ip, this.port);
    }

    public Jedis getJedis(){
        try (Jedis jedis = this.pool.getResource()) {
            this.auth(jedis);
            return jedis;
        }
    }
    public Jedis getNonPooledJedis(){
        Jedis jedis = new Jedis(this.ip, this.port);
        this.auth(jedis);
        return jedis;
    }
    public void subscribe(JedisPubSub listener, String... channels){
        Bukkit.getScheduler().runTaskAsynchronously(Main.getPlugin(), () -> {
            Jedis jedis = this.getNonPooledJedis();
            jedis.subscribe(listener, channels);
        });
    }
    public void publish(String channel, String value){
        Bukkit.getScheduler().runTaskAsynchronously(Main.getPlugin(), () -> this.getJedis().publish(channel, value));
    }

    public void disable(){
        getPool().destroy();
        Bukkit.getScheduler().cancelAllTasks();
    }

    public void set(String key, Object value){
        Bukkit.getScheduler().runTaskAsynchronously(Main.getPlugin(), () -> {
            Jedis jedis = this.getJedis();
            jedis.set(key, value.toString());
        });
    }
    public boolean contains(String key){
        Jedis jedis = this.getJedis();
        if(jedis.get(key) != null) return true;
        return false;
    }

    public String get(String key){
        return this.getJedis().get(key);
    }

    public JedisPool getPool(){
        return this.pool;
    }

    private void auth(Jedis jedis){
        if(this.pass != null && !"".equalsIgnoreCase(this.pass)){
            jedis.auth(this.pass);
        }
    }`

Error
#`[04:26:41] [Craft Scheduler Thread - 10/WARN]: Exception in thread "Craft Scheduler Thread - 10" 
[04:26:41] [Craft Scheduler Thread - 10/WARN]: org.apache.commons.lang.UnhandledException: Plugin SectorSpigot v0.0.1 generated an exception while executing task 34
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to [B
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:239)
	at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2139)
	at me.themajster.sectors.spigot.redis.Redis.auth(Redis.java:74)
	at me.themajster.sectors.spigot.redis.Redis.getJedis(Redis.java:27)
	at me.themajster.sectors.spigot.redis.Redis.lambda$publish$1(Redis.java:43)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

[04:26:43] [Craft Scheduler Thread - 9/WARN]: Exception in thread "Craft Scheduler Thread - 9" 
[04:26:43] [Craft Scheduler Thread - 9/WARN]: org.apache.commons.lang.UnhandledException: Plugin SectorSpigot v0.0.1 generated an exception while executing task 35
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265)
	at redis.clients.jedis.Jedis.publish(Jedis.java:2690)
	at me.themajster.sectors.spigot.redis.Redis.lambda$publish$1(Redis.java:43)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196)
	... 13 more

[04:26:58] [Server thread/INFO]: TheMajster lost connection: Disconnected
[04:26:58] [Server thread/INFO]: TheMajster left the game.
[04:27:01] [Thread-8/INFO]: UUID of player TheMajster is 2fcbde39-b580-3sds26-b3fcxxx90847
[04:27:01] [Server thread/INFO]: TheMajster[/1xxxxxxx36283] logged in with entity id 329 at ([world]1012.6028784051923, 74.0, 527.4178747730817)
[04:27:05] [Craft Scheduler Thread - 6/WARN]: Exception in thread "Craft Scheduler Thread - 6" 
[04:27:05] [Craft Scheduler Thread - 6/WARN]: org.apache.commons.lang.UnhandledException: Plugin SectorSpigot v0.0.1 generated an exception while executing task 137
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:199)
	at redis.clients.util.RedisInputStream.readLine(RedisInputStream.java:47)
	at redis.clients.jedis.Protocol.processError(Protocol.java:109)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265)
	at redis.clients.jedis.Jedis.publish(Jedis.java:2690)
	at me.themajster.sectors.spigot.redis.Redis.lambda$publish$1(Redis.java:43)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

[04:27:05] [Craft Scheduler Thread - 4/WARN]: Exception in thread "Craft Scheduler Thread - 4" 
[04:27:05] [Craft Scheduler Thread - 4/WARN]: org.apache.commons.lang.UnhandledException: Plugin SectorSpigot v0.0.1 generated an exception while executing task 136
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:199)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:239)
	at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2139)
	at me.themajster.sectors.spigot.redis.Redis.auth(Redis.java:74)
	at me.themajster.sectors.spigot.redis.Redis.getJedis(Redis.java:27)
	at me.themajster.sectors.spigot.redis.Redis.lambda$publish$1(Redis.java:43)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

[04:27:06] [Server thread/INFO]: TheMajster lost connection: Disconnected
[04:27:06] [Server thread/INFO]: TheMajster left the game.
[04:27:49] [Thread-9/INFO]: UUID of player TheMajster is 2fcbde39-b580xxxxxxxxc90847
[04:27:49] [Server thread/INFO]: TheMajster[/1xxxxxxxx33445] logged in with entity id 594 at ([world]998.5792406764423, 75.0, 529.4494795633668)
[04:27:56] [Server thread/WARN]: TheMajster moved too quickly! 19.0725782895596,-2.0,-1.7690229901962766 (19.0725782895596, -2.0, -1.7690229901962766)
[04:28:05] [Craft Scheduler Thread - 3/WARN]: Exception in thread "Craft Scheduler Thread - 3" 
[04:28:05] [Craft Scheduler Thread - 3/WARN]: org.apache.commons.lang.UnhandledException: Plugin SectorSpigot v0.0.1 generated an exception while executing task 196
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:239)
	at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2139)
	at me.themajster.sectors.spigot.redis.Redis.auth(Redis.java:74)
	at me.themajster.sectors.spigot.redis.Redis.getJedis(Redis.java:27)
	at me.themajster.sectors.spigot.redis.Redis.lambda$publish$1(Redis.java:43)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196)
	... 15 more

[04:28:06] [Server thread/INFO]: TheMajster lost connection: Disconnected
[04:28:06] [Server thread/INFO]: TheMajster left the game.
`

**Comment by sazzad16** [comment]
@TheMajster There are several `java.net.SocketTimeoutException: Read timed out`. May be network connection issue?

**Comment by sebdehne** [comment]
I have the same issue:

java.lang.ClassCastException: java.lang.Long cannot be cast to [B
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:239)
	at redis.clients.jedis.BinaryJedis.unwatch(BinaryJedis.java:1802)
...

**Comment by nathanfranke** [comment]
Yeah this is definitely still reproducible. The `Read timed out`s happened after the bug.
