### ISSUE TITLE
Jedis(2.9.0) throws exception when connecting from Spring-data-redis(1.8.9)

### ISSUE THREAD

**Issue by ramchris** [xetorthio/jedis#1709]
Steps are explained in stackoverflow. This is the link for the issue I faced.

https://stackoverflow.com/questions/47763245/cannot-get-jedis-connection-could-not-get-a-resource-from-the-pool

**Comment by marcosnils** [comment]
@ramchris please open this issue in the spring-data-redis issue tracker. If it's a Jedis issue that team will probably redirect it here.

**Comment by marcosnils** [comment]
@ramchris if you look at the Jedis issues you'll see that a lot of people already reported the "could not get resource from pool" error several times. It's usually a user's code problem when the Jedis instance is not being returned to the pool correctly. As you're using spring-data-redis, I'm not sure how the framework handles that that's why I've requested to open the issue there.

**Comment by ramchris** [comment]
@marcosnils  https://jira.spring.io/browse/DATAREDIS-742 was closed by Spring folks saying it was not an issue on Spring-data-redis. I hope Jedis should add a feature for distributed locking in future.

**Comment by mp911de** [comment]
Looking at the stack trace it's related to a read-timeout while closing/flushing:

```
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:16)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:194)
	... 40 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.jedis.Connection.disconnect(Connection.java:224)
	at redis.clients.jedis.BinaryClient.disconnect(BinaryClient.java:941)
	at redis.clients.jedis.Connection.close(Connection.java:214)
	at redis.clients.jedis.BinaryClient.close(BinaryClient.java:947)
	at redis.clients.jedis.Jedis.close(Jedis.java:3412)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:117)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:836)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:434)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	... 43 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:757)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at redis.clients.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:52)
	at redis.clients.util.RedisOutputStream.flush(RedisOutputStream.java:216)
	at redis.clients.jedis.Connection.disconnect(Connection.java:220)
	... 52 more
```

This kind of exception should be handled by jedis by ignoring that kind of failure during close or at least within the pooling part. Exceptions bubble otherwise into the application code which is not desirable.

**Comment by ramchris** [comment]
Thanks @mp911de
