### ISSUE TITLE
Jedis causes OutOfMemoryException after SocketTimeoutException

### ISSUE THREAD

**Issue by ragabar** [xetorthio/jedis#1747]
# Description
The problem happens when the client is waiting for 1 response, and after parsing the first bytes of a response, then get 
SocketTimeoutException on read. The exception causes `jedis.close()` to send QUIT but keep processing the partially-read response from ZREVRANGE response.
Then the partially response might land on * by luck if the response contains a star.
With this low-probability incident, jedis will try to allocate an array with the size that he gets from the partial stream.
It might be lucky that the rest of the response line is a small enough numb*__*er to allocate in the heap, and might be unlucky to
allocate a very large array, or allocate with a negative number of elements.
This causes the JVM to crash with OOM Java heap space, suppresed in `java.net.SocketTimeoutException: Read timed out` Exception.

A similar bug has been discoverd when using pipelined, that at a SocketTimeout, `pipeline.close()` calls `sync()` in order to complete parsing
pending responses, but it end up reading partial-read response. causing the same problem as above.
 
# Environment
OS: OSX/Linux.
Java Version: 1.8.0_151
Jedis version: `jedis-2.8.1`, but jedis-2.9.0 (latest version) has the same bug.

# Steps to reproduce
### Observed behavior
When timeout value is 1000, jedis.close() will be called after SocketTimeoutException, leading to process partiall-read response.
Which luckily could end up allocating an array that causes OutOfMemoryException.
To reproduce this behavior, Run the following code with command: `java -Xmx2g -cp . jedis.jar:. Main 1000 1`

### Expected behavior
After a SocketTimeoutException and `jedis.close()` being called, it should retrun the redis protocol parser to a healthy state.
To reproduce this behavior, Run the following code with command: `java -Xmx2g -cp . jedis.jar:. Main 3000 1`
 
```java
package com.myPackage;

import java.io.IOException;
import java.io.PrintStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Set;

import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;
import redis.clients.jedis.Pipeline;
import redis.clients.jedis.Response;

public class Main {
    private static JedisPoolConfig POOL_CONFIG = new JedisPoolConfig();

    public static void main(String[] args) {
        int timeout = Integer.parseInt(args[0]);
        int bugNo = Integer.parseInt(args[1]);
        
        System.out.println("Running with timeout:" + timeout + " and bugNo:" + bugNo);
        
        Thread serverThread = new Thread(Main::serverLoop);
        serverThread.start();

        JedisPool jedisPool = new JedisPool(POOL_CONFIG, "localhost", 8123, timeout);

        if (bugNo == 1) {
            firstBug(jedisPool);
        } else if (bugNo == 2) {
            secondBug(jedisPool);
        } else {
            throw  new IllegalArgumentException("Wrong bug number " + bugNo);
        }
    }

    // This causes an out-of-memory exception when jedis.close() sends QUIT but then parses the partially-read response from ZREVRANGE response.
    private static void firstBug(JedisPool jedisPool) {
        try (Jedis jedis = jedisPool.getResource()) {
            Set<String> result = jedis.zrevrange("somekey", 0, 1);
            System.err.println("Received: " + result);
        }
    }

    // This causes an out-of-memory exception when pipeline.close() calls sync() thinking there is 1 outstanding response but then parses the partially-read response from ZREVRANGE response.
    private static void secondBug(JedisPool jedisPool) {
        try (Jedis jedis = jedisPool.getResource();
             Pipeline pipeline=jedis.pipelined()){
            Response<Set<String>> response = pipeline.zrevrange("somekey", 0, 1);
            pipeline.sync();
            System.err.println("Received: " + response.get());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    // This mock 'redis server' responds with a single-element array containing the 11-byte string "**800000000".
    // By flushing/sleeping we arrange for it to be send in two packets so that we can demonstrate the impact of jedis
    // getting a socket read timeout partway through.
    private static void serverLoop() {
        try {
            ServerSocket server = new ServerSocket(8123);

            Socket socket = server.accept();

            String response1 = "*1\r\n$11\r\n*";
            String response2 = "*800000000\r\n";

            PrintStream printStream = new PrintStream(socket.getOutputStream());
            printStream.append(response1);
            printStream.flush();
            Thread.sleep(2000);
            printStream.append(response2);
            printStream.close();
            System.out.println("Exiting server");
        } catch (IOException | InterruptedException e) {
            System.err.println("Got exception: " + e);
        }
    }
}
```

And here's the stacktrace from the debugger with a timeout of 1000

```
Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:201)
	at redis.clients.util.RedisInputStream.read(RedisInputStream.java:180)
	at redis.clients.jedis.Protocol.processBulkReply(Protocol.java:171)
	at redis.clients.jedis.Protocol.process(Protocol.java:145)
	at redis.clients.jedis.Protocol.processMultiBulkReply(Protocol.java:196)
	at redis.clients.jedis.Protocol.process(Protocol.java:147)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233)
	at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:226)
	at redis.clients.jedis.Jedis.zrevrange(Jedis.java:1469)
	at com.myPackage.Main.firstBug(Main.java:35)
	at com.myPackage.Main.main(Main.java:27)
	Suppressed: java.lang.OutOfMemoryError: Java heap space
		at java.util.ArrayList.<init>(ArrayList.java:153)
		at redis.clients.jedis.Protocol.processMultiBulkReply(Protocol.java:193)
		at redis.clients.jedis.Protocol.process(Protocol.java:147)
		at redis.clients.jedis.Protocol.read(Protocol.java:205)
		at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
		at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:196)
		at redis.clients.jedis.BinaryJedis.quit(BinaryJedis.java:163)
		at redis.clients.jedis.JedisFactory.destroyObject(JedisFactory.java:69)
		at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:865)
		at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:639)
		at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:101)
		at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:112)
		at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:12)
		at redis.clients.jedis.Jedis.close(Jedis.java:3355)
		at com.myPackage.Main.firstBug(Main.java:37)
		... 1 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:195)
	... 12 more

```

# Suggested solution
When a SocketTimeoutException happens, the connections is marked as broken. Later, when trying to parse a reply again, a check is made on the state of the connection. If the connection is broken a `JedisConnectionException` is thrown, and will not continue reading from the current connection.

**Comment by sazzad16** [comment]
Resolved by #1923

**Comment by 13121314** [comment]
what milestone solved this problem?
2.9.1?
2.9.2?
thanks.

**Comment by suryavtkt** [comment]
if we stop reading data from broken connection, who will take care of that request
Do we have any retry mechanism to process the request to complete

**Comment by sazzad16** [comment]
@13121314 3.1.0 

apologies for the late reply
