### ISSUE TITLE
JedisException Could not return the resource to the pool when using Jedis cluster

### ISSUE THREAD

**Issue by warrenzhu25** [xetorthio/jedis#1752]
### Expected behavior

Jedis should not throw such exception in any scenario.

### Actual behavior

I'm connecting to Azure redis, which is cluster mode with 1 shards and two nodes are master and slave. When reboot master node, the exception will be thrown sometimes.

```
Exception in thread "main" redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
        at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:94)
        at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:235)
        at redis.clients.jedis.Jedis.close(Jedis.java:3430)
        at redis.clients.jedis.JedisClusterCommand.releaseConnection(JedisClusterCommand.java:172)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:166)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:33)
        at redis.clients.jedis.JedisCluster.get(JedisCluster.java:169)
        at com.microsoft.azure.redis.jedis.benchmark.ReconnectBenchmark.simulateWorkload(ReconnectBenchmark.java:64)
        at com.microsoft.azure.redis.jedis.benchmark.ReconnectBenchmark.simulateClusterWorkload(ReconnectBenchmark.java:78)
        at com.microsoft.azure.redis.jedis.benchmark.ReconnectBenchmark.runTest(ReconnectBenchmark.java:50)
        at com.microsoft.azure.redis.jedis.benchmark.ReconnectBenchmark.main(ReconnectBenchmark.java:38)
Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
        at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:640)
        at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:92)
```

### Steps to reproduce:

This exception can't be stably reproduced:
1. Create a redis cluster with 1 shard and 2 nodes are master and slave.
2. Create JedisCluster instance, then calling jedisCluster.set() and get() in the loop
3. Reboot or kill master node

#### Jedis version:
2.9.0
#### Java version:
1.8

**Comment by sazzad16** [comment]
@warrenzhu25 Seems like you are closing same resource more that once.

**Comment by warrenzhu25** [comment]
I didn't explicitly return any object. The code is something like this

```java

        try(Jedis jedis = jedisPool.getResource()){
            // perform some redis command
        } catch (JedisConnectionException e){
            // log
        }
```

I believe jedis is implicitly returned by try clause. This looks strange.

**Comment by sazzad16** [comment]
@warrenzhu25 I said about closing, not returning.

However, try-with-resources is implicitly calling `jedis.close()`. Is it, somehow, being called again?

**Comment by warrenzhu25** [comment]
I'm petty sure that I haven't called it ever. Maybe this is common pool issue, I'll look into it.

**Comment by rvkvino** [comment]
I have tried like bellow,
try {
	jedis = jedisPool.getResource();
	RateRow[] cbaserates = gson.fromJson(jedis.get("WLBaseRates"), RateRow[].class);
} catch (IllegalStateException ex) {
	ex.printStackTrace();
} finally {
	jedis.close();
}
But still I have an issue sometime showing Exception in thread "Timer-0" redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool at redis.clients.util.Pool.returnBrokenResourceObject
