### ISSUE TITLE
Conection reset by Jedis between 520000 and 530000 inserts

### ISSUE THREAD

**Issue by sachingupt** [xetorthio/jedis#1758]
I am inserting around 1.5 M object in Redis using Jedis client in batches of 10000. However, after 520000 inserts I get the following Exception, It does not help even if I attempt to recreate a Jedis Client connection and attempt to push, I get same exception immidiately. I have posted the server Log below as well. I am running server and client on Windows Machine :
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset by peer: socket write error
	at redis.clients.jedis.Protocol.sendCommand(Protocol.java:104)
	at redis.clients.jedis.Protocol.sendCommand(Protocol.java:84)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:127)
	at redis.clients.jedis.BinaryClient.mset(BinaryClient.java:204)
	at redis.clients.jedis.Client.mset(Client.java:134)
	at redis.clients.jedis.Jedis.mset(Jedis.java:460)

### Actual behavior

=== REDIS BUG REPORT START: Cut & paste starting from here ===
Redis version: 3.2.100
[6556] 25 Jan 12:16:34.358 # ------------------------------------------------
[6556] 25 Jan 12:16:34.358 # Fatal Error: "Unknown object type" #..\src\rdb.c:560
[6556] 25 Jan 12:16:34.358 # ------------------------------------------------
[6556] 25 Jan 12:16:34.358 # --- EXCEPTION_ACCESS_VIOLATION
[6556] 25 Jan 12:16:34.358 # --- STACK TRACE
redis-server.exe!((null):0)(0x0012E2F0, 0x0012FF90, 0x00000001, 0x4013A7F8)
redis-server.exe!((null):0)(0x00000001, 0x00000000, 0x00000001, 0x00609FD0)
kernel32.dll!UnhandledExceptionFilter((null):0)(0x0012E2F0, 0x00000006, 0x00000000, 0x00000001)
ntdll.dll!EtwEventSetInformation((null):0)(0x0012EF30, 0x0000000A, 0x40140E48, 0x00000000)
ntdll.dll!_C_specific_handler((null):0)(0x00130000, 0x0012FF90, 0x0012FF90, 0x7757F818)
ntdll.dll!RtlDecodePointer((null):0)(0x00130000, 0x7732DD88, 0x000127EC, 0x02BFC350)
ntdll.dll!RtlUnwindEx((null):0)(0x0012EF30, 0x0012EA40, 0x00000000, 0x00000000)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x00000001, 0x40170E80, 0x0037ECF0, 0x40000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000002, 0x0012F2E0, 0x0012F2E0, 0x00000001)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x0012F2E0, 0x00000001, 0x0012F2E0, 0x03C07040)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x40167210, 0x02130000, 0x00000005, 0x02532754)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x02130000, 0x02130000, 0x5A608638, 0x00000005)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000005, 0x00000000, 0x0035A580, 0x00000005)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000006, 0x00000000, 0x00000000, 0x0036FF50)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
kernel32.dll!BaseThreadInitThunk((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)

I am using Java8 and pushing normal key value entries in Redis.
### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by sachingupt** [comment]
Redis Version is 3.2.100 and Jedis version is 2.9.0
