### ISSUE TITLE
No reachable node in cluster

### ISSUE THREAD

**Issue by igor-bbm** [xetorthio/jedis#1760]
I am new to Redis\Jedis development. I have installed redis-server via `apt-get` on my ubuntu machine.
I am going to use Redis in my cloud deployment, but I need to feature proof it against local setup first.
I am using Jedis in my Spring Boot application, find the snippet below:

```
@Configuration
public class RedisConfig {

    @Value("${redis.pool.max-total}")
    private Integer maxTotal;

    @Value("${redis.pool.max-idle}")
    private Integer maxIdle;

    @Value("${redis.pool.min-idle}")
    private Integer minIdle;

    @Value("${redis.pool.block-when-exhausted}")
    private Boolean blockWhenExhausted;

    @Value("${redis.pool.max-wait-millis}")
    private Long maxWaitMillis;

    @Value("${redis.pool.test-on-borrow}")
    private boolean testOnBorrow;

    /**
     * format example: localhost:6379,host1:port1,host2:port2
     */
    @Value("${redis.hosts}")
    private String hosts;

    @Bean
    JedisConnectionFactory jedisConnectionFactory() {
        RedisClusterConfiguration redisClusterConfig = new RedisClusterConfiguration();
        redisClusterConfig.setClusterNodes(parseHosts());

        JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
        jedisPoolConfig.setMaxTotal(maxTotal);
        jedisPoolConfig.setMaxIdle(maxIdle);
        jedisPoolConfig.setMinIdle(minIdle);
        jedisPoolConfig.setBlockWhenExhausted(blockWhenExhausted);
        jedisPoolConfig.setMaxWaitMillis(maxWaitMillis);
        jedisPoolConfig.setTestOnBorrow(testOnBorrow);

        jedisPoolConfig.setBlockWhenExhausted(blockWhenExhausted);

        return new JedisConnectionFactory(redisClusterConfig, jedisPoolConfig);
    }

    private Iterable<RedisNode> parseHosts() {
        return Arrays.stream(hosts.split(",")).map(host -> {
            String[] hostInfo = host.split(":");
            String hostName = hostInfo[0].trim();
            Integer port = Ints.tryParse(hostInfo[1].trim());
            return new RedisNode(hostName, port);
        }).collect(Collectors.toList());
    }

...
```
then in the same class I configure several `RedisTemplate`s specific to my business needs.

When I run my app every single time it tries to read\write data from Redis, I see

```
org.springframework.data.redis.RedisConnectionFailureException: No reachable node in cluster; nested exception is redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: No reachable node in cluster
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:67) ~[spring-data-redis-1.7.5.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:41) ~[spring-data-redis-1.7.5.RELEASE.jar:na]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37) ~[spring-data-redis-1.7.5.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisClusterConnection.convertJedisAccessException(JedisClusterConnection.java:3696) ~[spring-data-redis-1.7.5.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisClusterConnection.get(JedisClusterConnection.java:546) ~[spring-data-redis-1.7.5.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:46) ~[spring-data-redis-1.7.5.RELEASE.jar:na]
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:54) ~[spring-data-redis-1.7.5.RELEASE.jar:na]
```
I wouldn't expect any issues. 

I have only one node in my cluster: `localhost:6379`
And the only change that I've made to `redis.conf` file - I have uncommented line `cluster-enabled yes`. 
I am not sure if that is a legitimate setup though. But I am able to connect to `localhost:6379` via `redis-cli` and run get\set commands there. 
If that is an incorrect setup, it seems that the exception message is a little bit misleading.

Redis 3.0.6
Jedis 2.8.2

**Comment by sazzad16** [comment]
@igor-bbm Only uncommenting `cluster-enabled yes` does not create cluster. Google for related tutorials/resources and set up a cluster first.
