### ISSUE TITLE
Is it possible to use Connection Pooling on Google App Engine? 

### ISSUE THREAD

**Issue by cnordvik** [xetorthio/jedis#1777]
When I try to use JedisPool I get an exception on GAE. Is this expected? Are there any alternatives to using Jedis on GAE and still get efficient connection handling? 

```
java.lang.NoClassDefFoundError: java.lang.management.ManagementFactory is a restricted class. Please see the Google App Engine developer's guide for more details.
	at com.google.apphosting.runtime.security.shared.stub.java.lang.management.ManagementFactory.<clinit>(ManagementFactory.java)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxRegister(BaseGenericObjectPool.java:981)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.<init>(BaseGenericObjectPool.java:137)
	at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:105)
	at redis.clients.util.Pool.initPool(Pool.java:44)
	at redis.clients.util.Pool.<init>(Pool.java:23)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:185)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:162)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:92)
```

**Comment by marcosnils** [comment]
Hi Christier. Seems like it's due to the dependency that commons pool has on Jmx. Plz open an issue in their tracker to see what's their opinion about it. Nothing to do on Jedis side as we're not planning to drop of replace the dependency for the moment.

**Comment by cnordvik** [comment]
Do you recommend using Jedis in a cloud based production environment without connection pooling or should we look into other Redis clients like Lettuce? We expect hundreds of reads per second so we need the performance to be optimal.

**Comment by marcosnils** [comment]
> We expect hundreds of reads per second so we need the performance to be optimal.

This won't be a problem. Jedis is being used in environmens with tens of thousands of reqs per second and performance is not an issue. Lettuce choice should be more about underlying networking implementation (NIO) and API design rather than performance.

**Comment by cnordvik** [comment]
Just to make sure, our clients are mobile clients making a HTTP connections to GAE. Will it be a problem with 100 clients each having to open a connection to Redis via Jedis since we don't use connection pooling? Just wondering how big deal it is that we can't use connection pooling feature on GAE and if we should consider moving to AWS Elastic Beanstalk where it works (we'd rather not move...).

**Comment by marcosnils** [comment]
> Will it be a problem with 100 clients each having to open a connection to Redis via Jedis since we don't use connection pooling?

You won't be able to use a single Jedis instance for this as it's not thread safe. Have you asked the commons-pool project about GAE integration?

**Comment by mp911de** [comment]
@cnordvik `NoClassDefFoundError` is raised because GAE seems to not support JMX. Disabling JMX should do the trick:

```java
GenericObjectPoolConfig config = new GenericObjectPoolConfig();
config.setJmxEnabled(false);
```

**Comment by cnordvik** [comment]
@mp911de Thanks! But I got a new error, any chance you have any idea how to resolve that one as well? I couldn't find anything on Google when searching for this error so I'm not sure if it's fixable or not :-/

```
JedisPushInserter run: Error registering, retrying task! (JedisPushInserter.java:113)
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:484)
	at java.security.AccessController.checkPermission(AccessController.java:698)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.google.apphosting.runtime.security.CustomSecurityManager.checkPermission(CustomSecurityManager.java:55)
	at com.google.apphosting.runtime.security.CustomSecurityManager.checkAccess(CustomSecurityManager.java:136)
	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
	at java.lang.Thread.init(Thread.java:391)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:596)
	at org.apache.commons.pool2.impl.EvictionTimer$EvictorThreadFactory.newThread(EvictionTimer.java:116)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:600)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:943)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1635)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:590)
	at org.apache.commons.pool2.impl.EvictionTimer.schedule(EvictionTimer.java:81)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.startEvictor(BaseGenericObjectPool.java:736)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.setTimeBetweenEvictionRunsMillis(BaseGenericObjectPool.java:462)
	at org.apache.commons.pool2.impl.GenericObjectPool.setConfig(GenericObjectPool.java:314)
	at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:115)
	at redis.clients.util.Pool.initPool(Pool.java:44)
	at redis.clients.util.Pool.<init>(Pool.java:23)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:185)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:162)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:92)
```

**Comment by mp911de** [comment]
Disable background eviction (`timeBetweenEvictionRunsMillis ` and maybe a couple of other properties). Seems that GAE requires a dedicated `ThreadFactory` and Commons Pool 2 does not allow setting the `ThreadFactory`.

**Comment by cnordvik** [comment]
Ok, I set the timeBetweenEvictionRunsMillis and it seems to run fine. But I have no idea of the implications of that. Disabling JMX and setting timeBetweenEvictionRunsMillis=0 and running on GAE is a good way to go about this?
