### ISSUE TITLE
Connection reset by peer: socket write error

### ISSUE THREAD

**Issue by qiaoyuwen** [xetorthio/jedis#1802]
### Actual behavior

when i use mset function to insert data redis, If the size of the data exceeds a certain amount it throw JedisConnectionException.

jedis log:

Exception in thread "main" net.svr.mon.exception.GeneralException: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset by peer: socket write error
  at net.svr.mon.redis.RedisClient.mset(RedisClient.java:219)
  at cloudbrain.mf.igs.redisMsetTest.main(redisMsetTest.java:21)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset by peer: socket write error
  at redis.clients.jedis.Protocol.sendCommand(Protocol.java:98)
  at redis.clients.jedis.Protocol.sendCommand(Protocol.java:78)
  at redis.clients.jedis.Connection.sendCommand(Connection.java:95)
  at redis.clients.jedis.BinaryClient.mset(BinaryClient.java:194)
  at redis.clients.jedis.Client.mset(Client.java:111)
  at redis.clients.jedis.Jedis.mset(Jedis.java:392)
  at net.svr.mon.redis.RedisClient.mset(RedisClient.java:217)
  ... 1 more
Caused by: java.net.SocketException: Connection reset by peer: socket write error
  at java.net.SocketOutputStream.socketWrite0(Native Method)
  at java.net.SocketOutputStream.socketWrite(Unknown Source)
  at java.net.SocketOutputStream.write(Unknown Source)
  at redis.clients.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:31)
  at redis.clients.util.RedisOutputStream.write(RedisOutputStream.java:53)
  at redis.clients.util.RedisOutputStream.write(RedisOutputStream.java:44)
  at redis.clients.jedis.Protocol.sendCommand(Protocol.java:94)
  ... 7 more

redis log:

[18264] 18 Apr 16:20:29.606 - Protocol error from client: id=2 addr=127.0.0.1:53278 fd=7 name= age=1 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=8184 qbuf-free=24584 obl=47 oll=0 omem=0 events=r cmd=ping

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by marcosnils** [comment]
Have you checked redis logs? Probably related to a network limit. Please provide a reproducible test case

**Comment by marcosnils** [comment]
Have you checked redis logs? Probably related to a network limit. Please provide a reproducible test case

**Comment by qiaoyuwen** [comment]
This is redis's log:
Protocol error (invalid mbulk count) from client: id=2 addr=127.0.0.1:52108 fd=7 name= age=1 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=8184 qbuf-free=24584 obl=47 oll=0 omem=0 events=r cmd=ping. Query buffer during protocol error: '*1099999..$4..MSET..$1..1..$87..aaaaaaaaqqqqqqqqqqqqqqqqqqqqqqqq' (... more 8056 bytes ...) 'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq..$2..81..$87..';

I found the redis networking.c 1173 row's code:
if (!ok || ll > 1024*1024) {
    addReplyError(c,"Protocol error: invalid multibulk length");
    setProtocolError("invalid mbulk count",c,pos);
    return C_ERR;
}

# Can jedis not split the data?

**Comment by qiaoyuwen** [comment]
I know the error's reason,
the length of args of the API command MSET can’t be bigger than 1024 * 1024, so the length of the array KeyValuePair 
(RedisKey, RedisValue)[] values can't be bigger than 524288.
