### ISSUE TITLE
JedisCluster can be instantiated when all nodes not reachable

### ISSUE THREAD

**Issue by fuyuanpai** [xetorthio/jedis#1815]
### Expected behavior
JedisCluster can not be instantiated when all nodes not reachable 

### Actual behavior
JedisCluster can be instantiated when all nodes not reachable 

### Steps to reproduce:
_Code:_ 
```
HostAndPort node = new HostAndPort("10.21.0.233", 2881);
JedisCluster jedisCluster = new JedisCluster(node);
jedisCluster.set("key", "value");
```

when node 10.21.0.233:2881 is not reachable, the jedisCluster instance will be created successfully
But the set operation will fail with exception:
```
redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: No reachable node in cluster
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:57)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:74)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:31)
	at redis.clients.jedis.JedisCluster.set(JedisCluster.java:103)
	at test.JedisClusterTest.main(JedisClusterTest.java:16)

```

Even when the 10.21.0.233:2881 is reachable again, the jedisCluster instance still not usable. All cache operation method in jedisCluster will throw the **JedisNoReachableClusterNodeException**
That is to say, we created a jedisCluster instance which is no use at all. It is not reasonable.
When all the cluster nodes not reachable, the JedisCluster should not be instantiated. **(Fail-Fast principle)**

**Comment by sazzad16** [comment]
@fuyuanpai How do you want to solve this? Also, what would you do if all of the nodes become unreachable in middle of a process?

**Comment by sazzad16** [comment]
Closed due to inactivity.
