### ISSUE TITLE
How to debug hanging getResource() call

### ISSUE THREAD

**Issue by srmo** [xetorthio/jedis#1844]
Using jedis 2.9.0 with Spring-Data-Redis 1.8.7
Calling redisTemplate.hasKey() leads to a stacktrace that keeps haning forever (now 9 hours) while working before flawlesly (~10B calls).
How can I continue to investigate the current situation. I have root access to the instance running the java process and the redis server.
Both are local to each other.
The java process and Redis are running on the same machine.

See Stacktrace at the end.

Running REDIS 4.0.8 on a Debian instance virtualized on KVM/libvirt.

Redis Server TOP values:
Prio: 20
Nice:   0 
Virt: 1043120
Res: 737180
SHR: 1496
S: S   
%Mem: 18.2

### Expected behavior
Call returns quickly

### Actual behavior
As described, the call seems to be stuck for ~9 hours

### Redis / Jedis Configuration
Redis: default config after "make"
Jedis: default config via JedisConnectionFactory via spring data redis

#### Jedis version:
 2.9.0 

#### Redis version:
4.0.8

#### Java version:
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

Related thread-dump:
```
2018-08-11_09:19:18.45343 "pool-3-thread-5" #1989 prio=5 os_prio=0 tid=0x00007f860c7d9800 nid=0xb12 waiting on condition [0x00007f86248de000]
2018-08-11_09:19:18.45343    java.lang.Thread.State: WAITING (parking)
2018-08-11_09:19:18.45344 	at sun.misc.Unsafe.park(Native Method)
2018-08-11_09:19:18.45345 	- parking to wait for  <0x00000007006e36d8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
2018-08-11_09:19:18.45345 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
2018-08-11_09:19:18.45346 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
2018-08-11_09:19:18.45347 	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:583)
2018-08-11_09:19:18.45349 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:442)
2018-08-11_09:19:18.45350 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
2018-08-11_09:19:18.45351 	at redis.clients.util.Pool.getResource(Pool.java:49)
2018-08-11_09:19:18.45352 	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
2018-08-11_09:19:18.45353 	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:16)
2018-08-11_09:19:18.45353 	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:194)
2018-08-11_09:19:18.45354 	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:348)
2018-08-11_09:19:18.45355 	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:129)
2018-08-11_09:19:18.45355 	at org.springframework.data.redis.core.RedisConnectionUtils.bindConnection(RedisConnectionUtils.java:67)
2018-08-11_09:19:18.45356 	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:192)
2018-08-11_09:19:18.45357 	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
2018-08-11_09:19:18.45359 	at org.springframework.data.redis.core.RedisTemplate.hasKey(RedisTemplate.java:658)
```

**Comment by marcosnils** [comment]
Please open this issue in the spring-data-redis as it's not related to Jedis directly.
