### ISSUE TITLE
Can't capture JedisConnectionException

### ISSUE THREAD

**Issue by PabloL007** [xetorthio/jedis#1858]
### Expected behavior

With the following code, when a JedisConnectionException is thrown it should enter the catch section and print those two messages:
```scala
import redis.clients.jedis.{Jedis, JedisSentinelPool}
import redis.clients.jedis.exceptions.JedisConnectionException

import collection.JavaConverters._

object Main extends App {
  val MASTER_NAME = "demo"
  val sentinels = Set(
    "172.14.121.5:26379",
    "172.14.121.6:26380",
    "172.14.121.7:26381"
  )

  // --- JEDIS ---
  val pool = new JedisSentinelPool(MASTER_NAME, sentinels.asJava)
  var jedis:Jedis = _

  try {
    jedis = pool.getResource
    jedis.set("testkey", "testvalue")
    var test = jedis.get("testkey")
    println(test)
  } catch {
    case e:JedisConnectionException =>
      println("Hello, this is a test ---------------------------------")
      println(s"Jedis exception: ${e.getMessage}")
    case e : Throwable =>
      println(s"Other exception: ${e.getMessage}")
  } finally {
    if(jedis != null){
      jedis.close()
    }
  }

  pool.destroy()
```

### Actual behavior

The exception passes through without being caught:

```shell
Aug 24, 2018 1:32:17 PM redis.clients.jedis.JedisSentinelPool initSentinels
INFO: Trying to find master from available Sentinels...
Aug 24, 2018 1:32:17 PM redis.clients.jedis.JedisSentinelPool initSentinels
INFO: Redis master running at 172.14.121.3:6380, starting Sentinel listeners...
Aug 24, 2018 1:32:17 PM redis.clients.jedis.JedisSentinelPool$MasterListener run
SEVERE: Lost connection to Sentinel at 172.14.121.6:26380. Sleeping 5000ms and retrying.
redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
        at redis.clients.jedis.Connection.connect(Connection.java:207)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
        at redis.clients.jedis.Connection.setTimeoutInfinite(Connection.java:94)
        at redis.clients.jedis.Jedis.subscribe(Jedis.java:2678)
        at redis.clients.jedis.JedisSentinelPool$MasterListener.run(JedisSentinelPool.java:291)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at redis.clients.jedis.Connection.connect(Connection.java:184)
        ... 4 more

Aug 24, 2018 1:32:17 PM redis.clients.jedis.JedisSentinelPool initPool
INFO: Created JedisPool to master at 172.14.121.3:6380
testvalue
```
### Steps to reproduce:

1. Start up a Redis master and 2 slaves
2. Start up 3 sentinels monitoring that master
3. Stop one of the sentinels
4. Configure the Sentinel pool with all three sentinels
5. Create the pool
6. Call pool.getResource()

**Comment by PabloL007** [comment]
I've also tried including all the code in the try:
```scala
import redis.clients.jedis.{Jedis, JedisSentinelPool}
import redis.clients.jedis.exceptions.JedisConnectionException

import collection.JavaConverters._

object Main extends App {
  val MASTER_NAME = "demo"
  val sentinels = Set(
    "172.14.121.5:26379",
    "172.14.121.6:26380",
    "172.14.121.7:26381"
  )

  // --- JEDIS ---


  try {
    val pool = new JedisSentinelPool(MASTER_NAME, sentinels.asJava)
    var jedis:Jedis = pool.getResource
    jedis.set("testkey", "testvalue")
    var test = jedis.get("testkey")
    println(test)
  } catch {
    case e:JedisConnectionException =>
      println("Hello, this is a test ---------------------------------")
      println(s"Jedis exception: ${e.getMessage}")
    case e : Throwable =>
      println(s"Other exception: ${e.getMessage}")
  } finally {
   // if(jedis != null){
   //   jedis.close()
  //  }
  }

  //pool.destroy()
```

**Comment by sazzad16** [comment]
@PabloL007 `JedisSentinelPool` creates new threads internally. It is not possible to catch exceptions in those threads from outside.
