### ISSUE TITLE
Could not get a resource from the pool

### ISSUE THREAD

**Issue by 437865981** [xetorthio/jedis#1860]
### Expected behavior
redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
        at redis.clients.util.Pool.getResource(Pool.java:51)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
        at top.hb.common.util.RedisUtil.getJedis(RedisUtil.java:230)
        at top.hb.common.util.RedisUtil.getValue(RedisUtil.java:1087)
        at top.hb.common.mq.RocketMQListenerForAliyun.checkSymbolIsOpen(RocketMQListenerForAliyun.java:190)
        at top.hb.common.mq.RocketMQListenerForAliyun.match(RocketMQListenerForAliyun.java:91)
        at top.hb.common.mq.RocketMQListenerForAliyun.process(RocketMQListenerForAliyun.java:71)
        at top.hb.common.mq.RocketMQListenerForAliyun.consume(RocketMQListenerForAliyun.java:219)
        at com.aliyun.openservices.ons.api.impl.rocketmq.ConsumerImpl$MessageListenerImpl.consumeMessage(ConsumerImpl.java:97)
        at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:417)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:449)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
        at redis.clients.util.Pool.getResource(Pool.java:49)

### Actual behavior

 when  i run almost 12 hour the exception is happened,help me ,thanks

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. I use the jedisPool and all of the method has invoked the jedis.colse() after used;
2. one of the method like this 
	public static boolean setNX(String key, String value, int second) {
		Jedis jedis = null;
		try {
			value = value == null ? "" : value;
			jedis = getJedis();
			String result = jedis.set(key, value,"NX", "EX", second);
			if ("OK".equalsIgnoreCase(result)) {
				return true;
			} else {
				return false;
			}
		} catch (Exception e) {
			log.error(key + ",",e);
			return false;
		} finally {
			jedis.close();
		}
	}
3、the pool config:
redis.evictionPolicyClassName=org.apache.commons.pool2.impl.DefaultEvictionPolicy
redis.lifo=true
redis.maxIdle=100
redis.maxTotal=2000
redis.maxWaitMillis=5000
redis.minIdle=0

**Comment by pkptzx** [comment]
why close?

**Comment by ldongxu** [comment]
I have the same problem.
jedis v2.9.0,Could not get a resource from the pool
