### ISSUE TITLE
jedis with embedded redis not working

### ISSUE THREAD

**Issue by prakashatul1** [xetorthio/jedis#1879]
public static void main(String arg[]) {
		ServerSocket socket = null;
		try {
			socket = new ServerSocket(0);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    int port = socket.getLocalPort();
	    try {
			socket.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    RedisServer redisServer = null;
		try {
			redisServer = new RedisServer(port);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    redisServer.start();
	    System.out.println("Redis Server started");
		Jedis jedis = new Jedis();
	    jedis.set("events/city/rome", "32,15,223,828");
	    System.out.println("Stored string in redis: " + jedis.get("events/city/rome"));
	    
	    jedis.flushAll();
	    System.out.println("Data Flushed");
	    System.out.println("Stored string in redis: " + jedis.get("events/city/rome"));
	    
	    redisServer.stop();
	    System.out.println("Redis Server stopped");
	    
	}
}`

> I have been using jedis with embedded redis server with the above implementation suddenly it stopped working throwing error

> Exception in thread "main" redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.Connection.connect(Connection.java:207)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:126)
	at redis.clients.jedis.BinaryClient.set(BinaryClient.java:110)
	at redis.clients.jedis.Client.set(Client.java:47)
	at redis.clients.jedis.Jedis.set(Jedis.java:120)
	at com.flipkart.redis.testredis.main(testredis.java:37)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:184)
	... 6 more

> please help

_Originally posted by @prakashatul1 in https://github.com/xetorthio/jedis/issues/1365#issuecomment-432946965_

**Comment by marcosnils** [comment]
If this has been working for you and it stopped working of all the sudden it might be an embedded-redis  update or something changed in your system. According to the exception seems like embedded redis is no starting or something. 
I'll close this as there's not much we can do from our end and the Jedis exception is pretty clear. If you're still having problems open a new issue with more detail.
