### ISSUE TITLE
jedis eval script error 

### ISSUE THREAD

**Issue by andrew-asa** [xetorthio/jedis#1949]
```
@Test
    public void evalMultiBulkWithBinaryJedis2() {

        Jedis jedis = getJedis();
        String script = "return redis.call('hget', KEYS[1], ARGV[1])";
        Object o = jedis.eval(script.getBytes(), "hash1".getBytes(), "item1".getBytes());
        jedis.close();
    }
```
### shell evl success 
```
127.0.0.1:6379> hget hash1 item1
"2"
127.0.0.1:6379> hget hash1 item1
"2"
127.0.0.1:6379> EVAL "return redis.call('hget', KEYS[1], ARGV[1])" 1 hash1 item1
"2"

```
### redis.clients.jedis.exceptions.JedisDataException:` ERR value is not an integer or out of range

redis.clients.jedis.exceptions.JedisDataException: ERR value is not an integer or out of range

	at redis.clients.jedis.Protocol.processError(Protocol.java:131)
	at redis.clients.jedis.Protocol.process(Protocol.java:165)
	at redis.clients.jedis.Protocol.read(Protocol.java:219)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:309)
	at redis.clients.jedis.Connection.getOne(Connection.java:291)
	at redis.clients.jedis.BinaryJedis.eval(BinaryJedis.java:3306)
	at RedisHashTest.evalMultiBulkWithBinaryJedis2(RedisHashTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by andrew-asa** [comment]
<dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>3.0.0</version>
        </dependency>

**Comment by andrew-asa** [comment]
absent paramert 
String script = "return redis.call('hget', KEYS[1], ARGV[1])";
        Integer integer = 1;
        Object o = jedis.eval(script.getBytes(), 1, "hash1".getBytes(), "item1".getBytes());
