### ISSUE TITLE
Redis cluster upgrade from 3.2 to 4.0 results in java.lang.NumberFormatException: For input string: "6379@16379" 

### ISSUE THREAD

**Issue by ritushri88** [xetorthio/jedis#1958]
### Issue

My current application was using Redis 3.2 cluster with Jedis client 2.8.0 and spring-data-redis-1.7.0.RELEASE.
Now After upgrading to cluster from Redis 3.2 to 4.0 JedisConnectionFactory is giving exception. I think the exception is related to how Redis 4.0 cluster share the cluster-info (ip+port) and Jedis client is unable to parse it.

### Stacktrace

Caused by: java.lang.NumberFormatException: For input string: "6379@16379"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_181]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_181]
	at java.lang.Integer.valueOf(Integer.java:766) ~[?:1.8.0_181]
	at redis.clients.util.ClusterNodeInformationParser.getHostAndPortFromNodeLine(ClusterNodeInformationParser.java:39) ~[jedis-2.8.0.jar:?]
	at redis.clients.util.ClusterNodeInformationParser.parse(ClusterNodeInformationParser.java:14) ~[jedis-2.8.0.jar:?]
	at redis.clients.jedis.JedisClusterInfoCache.discoverClusterNodesAndSlots(JedisClusterInfoCache.java:50) ~[jedis-2.8.0.jar:?]
	at redis.clients.jedis.JedisClusterConnectionHandler.initializeSlotsCache(JedisClusterConnectionHandler.java:39) ~[jedis-2.8.0.jar:?]
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:28) ~[jedis-2.8.0.jar:?]
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(JedisSlotBasedConnectionHandler.java:21) ~[jedis-2.8.0.jar:?]
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(JedisSlotBasedConnectionHandler.java:16) ~[jedis-2.8.0.jar:?]
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:39) ~[jedis-2.8.0.jar:?]
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:45) ~[jedis-2.8.0.jar:?]
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.createCluster(JedisConnectionFactory.java:303) ~[spring-data-redis-1.7.0.RELEASE.jar:?]
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.createCluster(JedisConnectionFactory.java:273) ~[spring-data-redis-1.7.0.RELEASE.jar:?]
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.afterPropertiesSet(JedisConnectionFactory.java:235) ~[spring-data-redis-1.7.0.RELEASE.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.obtainBeanInstanceFromFactory(ConfigurationClassEnhancer.java:389) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at com.expedia.risk.listservice.configuration.CacheConfiguration$$EnhancerBySpringCGLIB$$c3b6360a.getJedisConnectionFactory(<generated>) ~[classes/:?]
	at com.expedia.risk.listservice.configuration.CacheConfiguration.getStringRedisTemplate(CacheConfiguration.java:78) ~[classes/:?]
	at com.expedia.risk.listservice.configuration.CacheConfiguration$$EnhancerBySpringCGLIB$$c3b6360a.CGLIB$getStringRedisTemplate$1(<generated>) ~[classes/:?]
	at com.expedia.risk.listservice.configuration.CacheConfiguration$$EnhancerBySpringCGLIB$$c3b6360a$$FastClassBySpringCGLIB$$5fca4196.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at com.expedia.risk.listservice.configuration.CacheConfiguration$$EnhancerBySpringCGLIB$$c3b6360a.getStringRedisTemplate(<generated>) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]

**Comment by sazzad16** [comment]
@ritushri88 Please upgrade your Jedis. Thanks!
