### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by deepshiv126** [xetorthio/jedis#1977]
Hello 

I'm trying to connect to AWS ElastiCache Redis using Spring Data Redis + **Jedis** combination. [Redis Cluster enabled, so it has Cluster Config endpoint, with 3 shard - each shard has 1 primary node + 2 replica nodes ]

I'm getting Read timed out error.

`Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
`
----------------------------------------------------------------
AWS Redis Server Version : 5.0.3 / Cluster Mode : Enabled / SSL : Enabled / Auth : Enabled ( by password )

Library -- Spring-data-redis : 2.1.6.Release / jedis : 2.9.0

Telnet works to AWS Redis all nodes and cluster config endpoint at 6379 ports.

So, no issues with Redis itself, issue with Spring Data Redis in combination with Jedis.
----------------------------------------------------------------
My Code looks like this -

 ```
       RedisClusterConfiguration redisClusterConfiguration = new RedisClusterConfiguration();
        redisClusterConfiguration.setClusterNodes(listOfRedisNode);
        redisClusterConfiguration.setPassword(passwordString);


        JedisClientConfiguration.JedisClientConfigurationBuilder jedisClientConfiguration = JedisClientConfiguration.builder();
        jedisClientConfiguration.connectTimeout(Duration.ofSeconds(60));
        jedisClientConfiguration.useSsl();
        jedisClientConfiguration.usePooling();


        JedisConnectionFactory jedisConnectionFactory = new JedisConnectionFactory(redisClusterConfiguration, jedisClientConfiguration.build() );
        jedisConnectionFactory.afterPropertiesSet();

        final RedisTemplate<String, Serializable> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(jedisConnectionFactory);
        redisTemplate.setKeySerializer(new JdkSerializationRedisSerializer());
        redisTemplate.setValueSerializer(new JdkSerializationRedisSerializer());
        redisTemplate.afterPropertiesSet();

        System.out.println(redisTemplate.getClientList().size());

        StringRedisConnection stringRedisConnectionlettuce = new DefaultStringRedisConnection(redisTemplate.getConnectionFactory().getConnection());
        final String message2 = stringRedisConnectionlettuce.echo("Hello");
        System.out.println("Hello".equals(message2));
```
----------------------------------------------------------------
Read time out error -
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
    at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
    at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
    at redis.clients.jedis.Protocol.process(Protocol.java:151)
    at redis.clients.jedis.Protocol.read(Protocol.java:215)
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
    at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:239)
    at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:96)
    at redis.clients.jedis.Connection.sendCommand(Connection.java:126)
    at redis.clients.jedis.Connection.sendCommand(Connection.java:117)
    at redis.clients.jedis.BinaryClient.auth(BinaryClient.java:564)
    at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2138)
    at redis.clients.jedis.JedisClusterConnectionHandler.initializeSlotsCache(JedisClusterConnectionHandler.java:36)
    at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:17)
    at redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(JedisSlotBasedConnectionHandler.java:24)
    at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:54)
    at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:93)
    at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.createCluster(JedisConnectionFactory.java:418)
    at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.createCluster(JedisConnectionFactory.java:388)
    at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.afterPropertiesSet(JedisConnectionFactory.java:345)
    at io.github.deepshiv126.springdataredis.example.MySpringBootApplication.main(MySpringBootApplication.java:306)
    ... 8 more
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.net.SocketInputStream.read(SocketInputStream.java:127)
    at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196)
    ... 27 more
```
I looked into Spring Source Code and Jedis Source Code -- My assumption its Jedis not using SSL Connection ;

JedisConnectionFactory - afterPropertiesSet()-- trying to create Cluster -- under that it's trying initializeSlotsCache, which issued AUTH command to Redis Server, with password -- This is where "Read timed out" is occuring;

JedisClusterConnectionHandler - isnt suppose to use Jedis with SSL; 
![image](https://user-images.githubusercontent.com/12883918/56941800-ade6cc00-6acb-11e9-8671-169e4e260ef4.png)

I understand local redis - you can go inside and run auth command to get authenticate. But I guess AWS Redis may not able to do that , its needs to have SSL Connection even before it runs AUTH command - Why Jedis is not using SSL Connection ?
----------------------------------------------------------------
I found another suggestion to use JedisPool - but spring-data-redis' JedisConnectionFactory doesn't accepts JedisPool. Is there any other way to do that ?

`JedisPool jedisPool = new JedisPool("rediss://" + clusterConfigEndPoint + ":6379");`

Another question - other libraries use redis ssl connection as `rediss:// `- how to Jedis Client to use SSL connection??

Any help will be really appreciated!!

**Comment by gregbarkerdcsg** [comment]
Hi @deepshiv126. Have you made any headway solving this issue? I'm experiencing a similar, possibly the same, issue with Azure Redis SSL and Jedis.

**Comment by akrivitzky** [comment]
We've had almost the exact same scenario that @deepshiv126 describes.  Because of deadline pressure, we ended up listing the cluster nodes in the Jedis configuration with SSL disabled, but we'd really like to use the single configuration endpoint.  Did you figure this out?

**Comment by gregbarkerdcsg** [comment]
Nah, chalked it up as a deficiency of Jedis, and moved on to alternatives.

**Comment by marcosnils** [comment]
This is already fixed int he Jedis master version https://github.com/xetorthio/jedis/blob/ef4ab403f9d8fd88bd05092fea96de2e9db0bede/src/main/java/redis/clients/jedis/JedisClusterConnectionHandler.java#L48. Not sure which version of spring-data-redis is using it. @gkorland probably knows.

**Comment by gkorland** [comment]
Starting from 2.1.6 it's using 2.9.3 (https://mvnrepository.com/artifact/org.springframework.data/spring-data-redis/2.1.6.RELEASE)
The 3.x should be based on jedis 3.x

**Comment by deepshiv126** [comment]
hi...
this is my current understanding...

What I was looking out for from Jedis? - AWS ElastiCache Redis - Cluster Mode enabled + Auth + SSL enabled ; 

Jedis supported Cluster Mode + Auth  -- except SSL enabled was recently committed and available in https://github.com/xetorthio/jedis/releases/tag/jedis-3.1.0-m1

Spring Data Redis is not yet consumed Jedis 3.x version; I have opened a ticket asking Spring to updated Spring-Data-Redis. 
 https://jira.spring.io/browse/DATAREDIS-974


Like @gkorland  mentioned, probably Spring-Data-Redis 3.x should be based on Jedis 3.x.

**Comment by yangrubing** [comment]
@deepshiv126 Have you solved that? I am facing exactly the same problem.

**Comment by ethereal-sandeep** [comment]
@deepshiv126  Did you found the solution to this? I am facing similar issue.

**Comment by Yutenzi** [comment]
@deepshiv126 Can you share if you have solved this issue?

**Comment by deepshiv126** [comment]
The solution is upgrading your libraries' version.
