### ISSUE TITLE
NullPointerException - Jedis 2.9.0

### ISSUE THREAD

**Issue by Ramesksasi** [xetorthio/jedis#1982]
### Actual behavior

We are using Jedis ops for has api methods to fetch values from Redis. Which at times returns the value most of time but sometime gives null exception.

### Stack trace capture when error occurs
[2019-05-15 15:32:39,042] ERROR [C4F7EB0B74BE15F348BF988E421CA76D] [http-nio-8443-exec-6][] com.###.###.###.controller.HomeController.dashboard - Exception in com.###.###.###.controller.HomeController Method : handleRequestjava.lang.NullPointerException

java.lang.NullPointerException

        at com.###.###.###.controller.HomeController.getHomePage(HomeController.java:1496)

        at com.###.###.###.controller.HomeController.dashboard(HomeController.java:327)

        at com.###.###.###.controller.HomeController$$FastClassBySpringCGLIB$$386b66f5.invoke(<generated>)

        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)

        at org.springframework.aop.###ectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84)

        at com.###.###.###.###ect.Security###ect.advice(Security###ect.java:157)

        at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:497)

        at org.springframework.aop.###ectj.Abstract###ectJAdvice.invokeAdviceMethodWithGivenArgs(Abstract###ectJAdvice.java:627)

        at org.springframework.aop.###ectj.Abstract###ectJAdvice.invokeAdviceMethod(Abstract###ectJAdvice.java:616)

        at org.springframework.aop.###ectj.###ectJAroundAdvice.invoke(###ectJAroundAdvice.java:70)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)

        at org.springframework.aop.###ectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84)

        at com.###.###.###.###ect.###WebLogging###ect.aroundMethod(###WebLogging###ect.java:62)

        at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:497)

#### Java version:1.8.56

Can this be a bug with Jedis version, kindly advise.

thank you

Rames

**Comment by gkorland** [comment]
@Ramesksasi did you test it with 2.9.3 or 2.10.2?

**Comment by Ramesksasi** [comment]
Hi Guy Korland,

Thank you for the response,

We are testing with 2.9.3 currently and will post results here.

Thanks again

Rames K S

________________________________

**Comment by sazzad16** [comment]
Closed due to inactivity.
