### ISSUE TITLE
Error on Streams with Transactions

### ISSUE THREAD

**Issue by banker** [xetorthio/jedis#1989]
### Expected behavior

You should be able to read and write streams inside a transaction.

### Actual behavior

Error. Here's the stack trace:

```
java.lang.ClassCastException:` class [B cannot be cast to class java.lang.String ([B and        java.lang.String are in module java.base of loader 'bootstrap')
at redis.clients.jedis.BuilderFactory$21.build(BuilderFactory.java:484)
at redis.clients.jedis.BuilderFactory$21.build(BuilderFactory.java:477)
at redis.clients.jedis.Response.build(Response.java:61)
at redis.clients.jedis.Response.get(Response.java:37)
at redis.clients.jedis.Transaction.exec(Transaction.java:53)
```

### Steps to reproduce:

```Java
Transaction t = jedis.multi();
t.xadd(streamKey, StreamEntryID.NEW_ENTRY, Map.of("foo", "bar"));
t.xadd(streamKey, StreamEntryID.NEW_ENTRY, Map.of("foo", "bar"));
Response<List<StreamEntry>> results = t.xrange(streamKey, null, null, 2);
t.exec();
```

### Redis / Jedis Configuration

Connecting to single Redis instance v5.0.4.

#### Jedis version:

3.1.0-m1

#### Redis version:

5.0.4

#### Java version:

1.9

**Comment by sazzad16** [comment]
Resolved by #1992
