### ISSUE TITLE
JedisSentinelPool Exception

### ISSUE THREAD

**Issue by BhargaviBP** [xetorthio/jedis#1993]
I am using JedisSentinelPool connection pool in spark application.  

Getting below exceptions. and frequently getting this exception.

redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
 at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
 at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
 at redis.clients.jedis.Protocol.process(Protocol.java:155)
 at redis.clients.jedis.Protocol.read(Protocol.java:220)
 at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:309)
 at redis.clients.jedis.Connection.getIntegerReply(Connection.java:260)
 at redis.clients.jedis.BinaryJedis.zremrangeByScore(BinaryJedis.java:2603)
 at com.jocata.sparkservice.AggregatedRedisSparkService.lambda$null$4881e509$1(AggregatedRedisSparkService.java:340)
 at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreach$1.apply(JavaRDDLike.scala:351)
 at org.apache.spark.api.java.JavaRDDLike$$anonfun$foreach$1.apply(JavaRDDLike.scala:351)
 at scala.collection.Iterator$class.foreach(Iterator.scala:893)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
 at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:927)
 at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:927)
 at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
 at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
 at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
 at org.apache.spark.scheduler.Task.run(Task.scala:109)
 at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random

**Comment by sazzad16** [comment]
@BhargaviBP You are saying there's exception in `JedisSentinelPool` but stacktrace says exception in `BinaryJedis.zremrangeByScore()`. It's difficult to help or trace issue without valid information.

However, did you try Jedis 3.0.1? It contains [2 bug fixes](https://github.com/xetorthio/jedis/releases/tag/jedis-3.0.1) over 3.0.0.

**Comment by sazzad16** [comment]
Closed due to inactivity.
