### ISSUE TITLE
java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by Louiss** [xetorthio/jedis#202]
java.lang.RuntimeException: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at com.abc.adFront.action.ActivityAction.doGet(ActivityAction.java:89)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:119)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:96)
        at com.caucho.server.dispatch.ServletFilterChain.doFilter(ServletFilterChain.java:109)
        at com.caucho.server.webapp.WebAppFilterChain.doFilter(WebAppFilterChain.java:184)
        at com.caucho.server.dispatch.ServletInvocation.service(ServletInvocation.java:287)
        at com.caucho.server.http.HttpRequest.handleRequest(HttpRequest.java:794)
        at com.caucho.network.listen.TcpSocketLink.dispatchRequest(TcpSocketLink.java:729)
        at com.caucho.network.listen.TcpSocketLink.handleRequest(TcpSocketLink.java:688)
        at com.caucho.network.listen.TcpSocketLink.handleRequestsImpl(TcpSocketLink.java:668)
        at com.caucho.network.listen.TcpSocketLink.handleRequests(TcpSocketLink.java:616)
        at com.caucho.network.listen.AcceptTask.doTask(AcceptTask.java:104)
        at com.caucho.network.listen.ConnectionReadTask.runThread(ConnectionReadTask.java:98)
        at com.caucho.network.listen.ConnectionReadTask.run(ConnectionReadTask.java:81)
        at com.caucho.network.listen.AcceptTask.run(AcceptTask.java:67)
        at com.caucho.env.thread.ResinThread.runTasks(ResinThread.java:164)
        at com.caucho.env.thread.ResinThread.run(ResinThread.java:130)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.util.Pool.getResource(Pool.java:22)
        at com.abc.nosql.RedisDB.getResource(RedisDB.java:64)
        at com.abc.adFront.action.ActivityAction.doGet(ActivityAction.java:74)
        ... 16 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: connect timed out
        at redis.clients.jedis.Connection.connect(Connection.java:124)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:54)
        at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1657)
        at redis.clients.jedis.JedisPool$JedisFactory.makeObject(JedisPool.java:63)
        at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1158)
        at redis.clients.util.Pool.getResource(Pool.java:20)
        ... 18 more
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
        at java.net.Socket.connect(Socket.java:529)
        at redis.clients.jedis.Connection.connect(Connection.java:119)
        ... 23 more

code:

JedisPoolConfig poolConfig = new JedisPoolConfig();
poolConfig.setMaxActive(500);
poolConfig.setMaxIdle(500);
poolConfig.setMaxWait(1000);
poolConfig.setTimeBetweenEvictionRunsMillis(10L_60L_1000L);
poolConfig.setMinEvictableIdleTimeMillis(60L*1000L);
poolConfig.setTestOnBorrow(true);
poolConfig.setTestOnReturn(true);
JedisPool pool = new JedisPool(poolConfig, host, Integer.parseInt(port));

use:
try {
            redis = RedisDB.getInstance().getResource("follow");
            follow = redis.get(uid);
        } catch (Exception e) {
            System.err.println("DATE:"+ new Date()+" "+"follow"+" "+e.getMessage());
            RedisDB.getInstance().getNumActive("follow");
            RedisDB.getInstance().getNumIdle("follow");
//          throw new RuntimeException(e);
        }finally{
            if(redis!=null){
                redis.close();
            }
        }

Started out very well, after some time, will produce this error. 
 I tried to get the current number of active and idle for a few, the results are as follows: 

DATE:Mon Sep 05 22:16:31 CST 2011 Could not get a resource from the pool
follow Active : 391
follow Idle   : 0

 But usually I track when these numbers are small. 

follow Active : 0
follow Idle   : 21

I am very depressed, this problem has troubled me for a few days.

**Comment by yangbo1** [comment]
禁用你的防火墙或者打开的你使用的端口
Close your firewall or allow the port you used
like : sudo ufw allow 6379/tcp

**Comment by 429463267** [comment]
[root@localhost src]# service iptables stop
iptables: Setting chains to policy ACCEPT: filter          [  OK  ]
iptables: Flushing firewall rules:                         [  OK  ]
iptables: Unloading modules:                               [  OK  ]
[root@localhost src]# 

![记得关闭防火墙][1]
[1]: http://p7fcrq2e4.bkt.clouddn.com/201818052319-chrome20180705_231925.png
