### ISSUE TITLE
[again and again]redis.clients.jedis.exceptions.JedisConnectionException: Unknown reply: ﾻ

### ISSUE THREAD

**Issue by sunjian** [xetorthio/jedis#203]
【【【【【【CLOSE】】】】】】】】 THIS problem was nearly 100% caused by calling the same Connection by multi-thread 

I try to use apache ab test like this : ab.exe -c 20 -n 10000

my jedispool config :

```
            config.setMaxActive(512) ;
    config.setMaxIdle(512) ;
    config.setMaxWait(20000);
    config.setTestOnBorrow(true);
    config.setTestWhileIdle(true);
    config.minEvictableIdleTimeMillis = 60000;
    config.timeBetweenEvictionRunsMillis = 30000;
    config.numTestsPerEvictionRun = -1;
```

I have got so many the following exception .

redis.clients.jedis.exceptions.JedisConnectionException: Unknown reply: ﾻ
    at redis.clients.jedis.Protocol.process(Protocol.java:71)
    at redis.clients.jedis.Protocol.processMultiBulkReply(Protocol.java:116)
    at redis.clients.jedis.Protocol.process(Protocol.java:63)
    at redis.clients.jedis.Protocol.read(Protocol.java:122)
    at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:189)
    at redis.clients.jedis.BinaryJedis.zrange(BinaryJedis.java:1465)
    at cn.etouch.ewaimai.ramdata.SupportCityCacher.getProvinceList(SupportCityCacher.java:89)
    at cn.etouch.ewaimai.api.actions.GetSupportCityAction.Do(GetSupportCityAction.java:71)
    at cn.etouch.ewaimai.api.servlet.DevClientServlet.doGet(DevClientServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:304)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at cn.etouch.ewaimai.api.servlet.ParameterValidatorFilter.doFilter(ParameterValidatorFilter.java:96)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at cn.etouch.ewaimai.api.servlet.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:48)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:240)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:164)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:462)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:164)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:563)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:403)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:301)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:162)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:140)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

**Comment by rs10615** [comment]
2019-Jan-16 10:19:07.847 ERROR [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.data.redis.RedisConnectionFailureException: Unknown reply: a; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Unknown reply: a
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:67)
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:181)
	at org.springframework.data.redis.connection.jedis.JedisHashCommands.convertJedisAccessException(JedisHashCommands.java:433)
	at org.springframework.data.redis.connection.jedis.JedisHashCommands.hGetAll(JedisHashCommands.java:196)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.hGetAll(DefaultedRedisConnection.java:862)
	at org.springframework.data.redis.core.DefaultHashOperations.lambda$entries$12(DefaultHashOperations.java:231)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
	at org.springframework.data.redis.core.DefaultHashOperations.entries(DefaultHashOperations.java:231)
	at com.nec.edgedisplay.common.doatier.redis.services.impl.DemographicRedisServiceImpl.findAll(DemographicRedisServiceImpl.java:88)
	at com.nec.edgedisplay.common.doatier.redis.services.impl.DemographicRedisServiceImpl$$FastClassBySpringCGLIB$$5cda2f2d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.nec.edgedisplay.common.doatier.redis.services.impl.DemographicRedisServiceImpl$$EnhancerBySpringCGLIB$$25b48e11.findAll(<generated>)
	at com.nec.edgedisplay.common.biztier.services.impl.DemographicServiceImpl.sendDataToEventHub(DemographicServiceImpl.java:67)
	at com.nec.edgedisplay.da.scheduler.EventHubScheduler.scheduleDemographicCacheTransferToEventHub(EventHubScheduler.java:60)
	at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Unknown reply: a
	at redis.clients.jedis.Protocol.process(Protocol.java:164)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:276)
	at redis.clients.jedis.BinaryJedis.hgetAll(BinaryJedis.java:1028)
	at org.springframework.data.redis.connection.jedis.JedisHashCommands.hGetAll(JedisHashCommands.java:194)
	... 29 common frames omitted

**Comment by rs10615** [comment]
@Configuration
public class RedisConnector {

	private static final Logger LOGGER = LoggerFactory.getLogger(RedisConnector.class);

	/** The host name. */
	@Value("${spring.redis.host}")
	private String hostName;

	/** The port. */
	@Value("${spring.redis.port}")
	private int port;

	/**
	 * Jedis connection factory.
	 *
	 * @return the jedis connection factory
	 */
	@Bean
	JedisConnectionFactory jedisConnectionFactory() {

		JedisConnectionFactory jedisConnectionFactory = null;

		try {
			RedisStandaloneConfiguration redisStandaloneConfiguration = new RedisStandaloneConfiguration(hostName,
					port);
			jedisConnectionFactory = new JedisConnectionFactory(redisStandaloneConfiguration);
			jedisConnectionFactory.getPoolConfig().setMaxTotal(128);
			jedisConnectionFactory.getPoolConfig().setMaxIdle(128);
		} catch (RedisConnectionFailureException e) {
			LOGGER.error("Connection break with redis " + e.getMessage());
		}

		return jedisConnectionFactory;
	}

	/**
	 * Redis template.
	 *
	 * @return the redis template
	 */
	@Bean
	public RedisTemplate<String, Object> redisTemplate() {
		final RedisTemplate<String, Object> template = new RedisTemplate<String, Object>();
		template.setConnectionFactory(jedisConnectionFactory());
		template.setValueSerializer(new GenericToStringSerializer<Object>(Object.class));
		template.setEnableTransactionSupport(true);
		return template;
	}

}

**Comment by rs10615** [comment]
@Repository
public class CrowdCountRedisServiceImpl implements ICrowdCountRedisService {
	
	private static final Logger LOGGER = LoggerFactory.getLogger(CrowdCountRedisServiceImpl.class);

	/** The Constant KEY. */
	private static final String KEY = CrowdCount.class.getName();
	
	/** The redis template. */
	private RedisTemplate<String, Object> redisTemplate;
	
	/** The hash operations. */
	private HashOperations<String, Long, CrowdCount> hashOperations;
	
	

	/**
	 * Instantiates a new crowd count redis service impl.
	 *
	 * @param redisTemplate the redis template
	 */
	@Autowired
	public CrowdCountRedisServiceImpl(RedisTemplate<String, Object> redisTemplate) {
		this.redisTemplate = redisTemplate;
	}

	/**
	 * Inits the rest template.
	 */
	@PostConstruct
    private void init(){
        hashOperations = redisTemplate.opsForHash();
    }
	
	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.ICrowdCountRedisService#save(com.nec.edgedisplay.common.doatier.models.CrowdCount)
	 */
	@Override
	public void save(CrowdCount crowdCount) {
		LOGGER.info("Inside save method of redis for crowd count");
		if(crowdCount != null){
			hashOperations.put(KEY, crowdCount.getDataStoreId(), crowdCount);
			LOGGER.info("CrowdCount object saved in redis is --------- >"+crowdCount.toString());
		}
		else{
			LOGGER.error("CrowdCount object is null");
		}
	}

	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.ICrowdCountRedisService#find(java.lang.Long)
	 */
	@Override
	public CrowdCount find(Long id) {
		if(id != null){
			return hashOperations.get(KEY, id);
		}else{
			LOGGER.error("Id is missing");
			return null;
		}
		
	}

	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.ICrowdCountRedisService#findAll()
	 */
	@Override
	public Map<Long, CrowdCount> findAll() {
		return hashOperations.entries(KEY);
	}

	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.ICrowdCountRedisService#update(com.nec.edgedisplay.common.doatier.models.CrowdCount)
	 */
	@Override
	public void update(CrowdCount crowdCount) {
		if(crowdCount != null){
			hashOperations.put(KEY, crowdCount.getDataStoreId(), crowdCount);
		}else{
			LOGGER.error("Object to be updated can not be null");
		}
		
	}

	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.ICrowdCountRedisService#deleteAll()
	 */
	@Override
	public void deleteAll() {
		hashOperations.delete(KEY);	
		
	}

	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.ICrowdCountRedisService#deleteById(java.lang.Long)
	 */
	@Override
	public void deleteById(Long id) {
		if(id != null){
			hashOperations.delete(KEY, id);	
		}else{
			LOGGER.error("Id can not be null");
		}
	
		
	}

}

**Comment by rs10615** [comment]
@Repository
public class DemographicRedisServiceImpl implements IDemographicRedisService {
	
	private static final Logger LOGGER = LoggerFactory.getLogger(DemographicRedisServiceImpl.class);

	/** The Constant KEY. */
	private static final String KEY = Demographic.class.getName();
	
	/** The redis template. */
	private RedisTemplate<String, Object> redisTemplate;
	
	/** The hash operations. */
	private HashOperations<String, Long, Demographic> hashOperations;
	
	/**
	 * Instantiates a new demographic redis service impl.
	 *
	 * @param redisTemplate the redis template
	 */
	@Autowired
	public DemographicRedisServiceImpl(RedisTemplate<String, Object> redisTemplate) {
		this.redisTemplate = redisTemplate;
	}
	
	/**
	 * Inits the rest template..
	 */
	@PostConstruct
    public void init(){
        hashOperations = redisTemplate.opsForHash();
    }
	
	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.IDemographicRedisService#save(com.nec.edgedisplay.common.doatier.models.Demographic)
	 */
	@Override
	public void save(Demographic demographic) {
		LOGGER.info("Inside save method of redis for demographic");
		if(demographic != null){
			hashOperations.put(KEY, demographic.getDataStoreId(), demographic);
		LOGGER.info("demographic object saved in redis is --------- >"+demographic.toString());
	}
		else{
			LOGGER.error("Demographic object is null");
		}
	}

	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.IDemographicRedisService#find(java.lang.Long)
	 */
	@Override
	public Demographic find(Long id) {
		if(id != null){
			return hashOperations.get(KEY, id);
		}else{
			LOGGER.error("Id is missing");
			return null;
		}
		
	}

	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.IDemographicRedisService#findAll()
	 */
	@Override
	public Map<Long, Demographic> findAll() {
		return hashOperations.entries(KEY);
	}

	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.IDemographicRedisService#update(com.nec.edgedisplay.common.doatier.models.Demographic)
	 */
	@Override
	public void update(Demographic demographic) {
		if(demographic != null){
			hashOperations.put(KEY, demographic.getDataStoreId(), demographic);
		}else{
			LOGGER.error("Object to be updated can not be null");
		}
		
		
	}

	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.IDemographicRedisService#deleteAll()
	 */
	@Override
	public void deleteAll() {
		redisTemplate.delete(KEY);
		
	}

	/* (non-Javadoc)
	 * @see com.nec.edgedisplay.common.doatier.redis.services.IDemographicRedisService#deleteById(java.lang.Long)
	 */
	@Override
	public void deleteById(Long id) {
		if(id != null){
			hashOperations.delete(KEY, id);	
		}else{
			LOGGER.error("Id can not be null");
		}
	
		
	}

}

**Comment by rs10615** [comment]
so above first i have posted the exception then i have posted the code please provide the solution ,i will be greatfull to you. i am facing while long running of our application in production.

**Comment by gkorland** [comment]
#1936
