### ISSUE TITLE
ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context

### ISSUE THREAD

**Issue by madhushreegc** [xetorthio/jedis#2061]
#### Java version: 1.8

When do we get the below error? I have configured jedisPool with JedisPoolConfig
redis.clients.jedis.exceptions.JedisDataException: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context 
               at redis.clients.jedis.Protocol.processError(Protocol.java:127) ~[jedis-2.9.0.jar:?] 
               at redis.clients.jedis.Protocol.process(Protocol.java:161) ~[jedis-2.9.0.jar:?] 
               at redis.clients.jedis.Protocol.read(Protocol.java:215) ~[jedis-2.9.0.jar:?] 
               at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340) ~[jedis-2.9.0.jar:?] 
               at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:259) ~[jedis-2.9.0.jar:?] 
               at redis.clients.jedis.BinaryJedis.get(BinaryJedis.java:244) ~[jedis-2.9.0.jar:?]

**Comment by sazzad16** [comment]
@madhushreegc You are using a (Binary)Jedis which is currently busy in `subscribe`.
