### ISSUE TITLE
java.lang.ClassCastException: [B cannot be cast to java.util.List

### ISSUE THREAD

**Issue by Carry-Kang** [xetorthio/jedis#2125]
#### Java version:1.8

java.lang.ClassCastException: [B cannot be cast to java.util.List
        at redis.clients.jedis.BuilderFactory$7.build(BuilderFactory.java:111) ~[jedis-3.1.0.jar:na]
        at redis.clients.jedis.BuilderFactory$7.build(BuilderFactory.java:107) ~[jedis-3.1.0.jar:na]
        at redis.clients.jedis.Response.build(Response.java:61) ~[jedis-3.1.0.jar:na]
        at redis.clients.jedis.Response.get(Response.java:37) ~[jedis-3.1.0.jar:na]

**Comment by gkorland** [comment]
@kangxiaobai can you please add a recreation code?

**Comment by sazzad16** [comment]
Closed due to inactivity.

**Comment by jacarrichan** [comment]
@Carry-Kang 
maybe you can find  [Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out]  in log file .

if you find.  
you can   reproduce it by    the folllowing  command  :

[sudo iptables -A INPUT   -p tcp --sport 6379 -j DROP]

call  jedis.returnBrokenResource  can solve it.
