### ISSUE TITLE
Jedis MasterListener Sentinel listeners NOAUTH error 

### ISSUE THREAD

**Issue by oblum** [xetorthio/jedis#2153]
JedisSentinelPool  successfully connects to sentinel servers and expect the listeners to attach to Sentinels. 

Once started the Listeners are failing 
356 [main] INFO redis.clients.jedis.JedisSentinelPool  - Redis master running at 10.90.69.81:6379, starting Sentinel listeners...
426 [MasterListener-xxx-master-[server:26379]] ERROR redis.clients.jedis.JedisSentinelPool  - Lost connection to Sentinel at server:26379. Sleeping 5000ms and retrying.

redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.Protocol.processError(Protocol.java:132)
	at redis.clients.jedis.Protocol.process(Protocol.java:166)
	at redis.clients.jedis.Protocol.read(Protocol.java:220)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318)
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:280)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:285)
	at redis.clients.jedis.Jedis.sentinelGetMasterAddrByName(Jedis.java:3042)
	at redis.clients.jedis.JedisSe
 

Write here what happens instead ...
 Created a simple program to create JedisPool.

Create Log4j ConsoleAppender

_log4j.addAppender(new ConsoleAppender(new PatternLayout(PatternLayout.TTCC_CONVERSION_PATTERN)));
Call : new JedisSentinelPool(masterName, sentinels, poolConfig, timeout, timeout, accessKey, database,   
				clientName, timeout, timeout, sentinelAccessKey, sentinelClientName);

Generates 0 [main] INFO redis.clients.jedis.JedisSentinelPool  - Trying to find master from available Sentinels...
22 [main] DEBUG redis.clients.jedis.JedisSentinelPool  - Connecting to Sentinel server:26379
354 [main] DEBUG redis.clients.jedis.JedisSentinelPool  - Found Redis master at 10.90.69.81:6379
356 [main] INFO redis.clients.jedis.JedisSentinelPool  - Redis master running at 10.90.69.81:6379, starting Sentinel listeners...
426 [MasterListener-yte-master-[server]] ERROR redis.clients.jedis.JedisSentinelPool  - Lost connection to Sentinel at server:26379. Sleeping 5000ms and retrying.
redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.Protocol.processError(Protocol.java:132)
	at redis.clients.jedis.Protocol.process(Protocol.java:166)
	at redis.clients.jedis.Protocol.read(Protocol.java:220)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318)
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:280)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:285)
	at redis.clients.jedis.Jedis.sentinelGetMasterAddrByName(Jedis.java:3042)
	at redis.clients.jedis.JedisSentinelPool$MasterListener.run(JedisSentinelPool.java:313)
435 [MasterListener-yte-master-[sever:26379]] ERROR redis.clients.jedis.JedisSentinelPool  - Lost connection to Sentinel at RT55B10097DV00:26379. Sleeping 5000ms and r

Jedis  3.20
java version "1.8.0_241"
Sentinel version 5.1

**Comment by oblum** [comment]
Humbly provide a suggestion for possible  fix. Connection is not passing password nor master name. 
JedisSentinelPool$MasterListener  
Line 304     j = new Jedis(host, port);
add lines
  if (sentinelPassword != null) {
            j.auth(sentinelPassword);
    }
   if (sentinelClientName != null) {
            j.clientSetname(sentinelClientName);
     }

**Comment by timmixell** [comment]
I encountered this same issue: 

```
redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.Protocol.processError(Protocol.java:132)
	at redis.clients.jedis.Protocol.process(Protocol.java:166)
	at redis.clients.jedis.Protocol.read(Protocol.java:220)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318)
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:280)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:285)
	at redis.clients.jedis.Jedis.sentinelGetMasterAddrByName(Jedis.java:3042)
	at redis.clients.jedis.JedisSentinelPool$MasterListener.run(JedisSentinelPool.java:313)
03/04 22:32:31 [MasterListener-dd-redis-cluster-[X.X.X.X:26379]] JEDIS ERROR - Lost connection to Sentinel at X.X.X.X:26379. Sleeping 5000ms and retrying.
```

I've put in a PR, but I could use some direction on writing a supporting test case, since it doesn't look like any of the Sentinel tests work against a password-protected instances.
