### ISSUE TITLE
redis scanoptions is not allowing to set the count

### ISSUE THREAD

**Issue by jinitbansod** [xetorthio/jedis#2162]
### Expected behavior

Should return a list with limit count records ,as the count has been set by using below command
		
**hashOperation.scan(redisKey, ScanOptions.scanOptions().count(2L).match("*"+key+"*").build());**
### Actual behavior

throwing an exception while setting count through scan function as given below :
Caused by: java.lang.NoSuchMethodError: redis.clients.jedis.ScanParams.count(I)Lredis/clients/jedis/ScanParams;
	at org.springframework.data.redis.connection.jedis.JedisConverters.toScanParams(JedisConverters.java:464) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisConnection$5.doScan(JedisConnection.java:3438) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.KeyBoundCursor.doScan(KeyBoundCursor.java:39) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.ScanCursor.scan(ScanCursor.java:86) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.ScanCursor.doOpen(ScanCursor.java:121) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.ScanCursor.open(ScanCursor.java:110) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisConnection.hScan(JedisConnection.java:3443) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisConnection.hScan(JedisConnection.java:3417) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultHashOperations$14.doInRedis(DefaultHashOperations.java:243) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultHashOperations$14.doInRedis(DefaultHashOperations.java:238) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:204) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:166) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:88) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultHashOperations.scan(DefaultHashOperations.java:238) ~[spring-data-redis-1.7.9.RELEASE.jar:na]
	at com.globant.microservice.utils.RedisUtil.getMapMatchingKeyValues(RedisUtil.java:47) ~[bin/:na]

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Set count function using redis 
2. By using command
hashOperation.scan(redisKey, ScanOptions.scanOptions().count(2L).match("*"+key+"*").build());

#### Jedis version:
compile group: 'redis.clients', name: 'jedis', version: '2.9.0'
#### Redis version:
	compile("org.springframework.boot:spring-boot-starter-redis:1.3.3.RELEASE")
 	compile("org.springframework.data:spring-data-redis:1.7.2.RELEASE")

#### Java version:
java 1.8

**Comment by sazzad16** [comment]
Jedis `ScanParams.count(Integer count)` takes `Integer`, not `Long`.
