### ISSUE TITLE
support asynchronous calls to redis

### ISSUE THREAD

**Issue by xetorthio** [xetorthio/jedis#241]

**Comment by Librael** [comment]
Do you have any planing date/month for 3.0.0 ?
Release 3.0.0 will support async feature for sure or is it not completely decided yet?
If yes - it will be a Future result or Callback registration or both?
Thank you!

**Comment by nykolaslima** [comment]
We will support async feature for sure.
We're still studying future vs callback.

I believe we still don't have a schedule date, we want to do it as fast as
possible.

**Comment by sdeleuze** [comment]
Rather than just Async, a Stream based API like MongoDB or CouchBase are developing would be even more powerful. See http://blog.couchbase.com/why-couchbase-chose-rxjava-new-java-sdk for more details ...

**Comment by HeartSaVioR** [comment]
@sdeleuze 
Hello!
Actually I don't have any experiences on stream for Java.
(I know map / filter / reduce cause I'm Python programmer, and studied Scala a bit. ;) )
Since Jedis 3.0.0 should support JDK 7, it would be some kind of pain to implement custom Future (like CompletableFuture) and support it.

Could you give a hand to show some implementations? Thanks in advance!

**Comment by HeartSaVioR** [comment]
@sdeleuze 
I've just take a look at RxJava and it's amazing!
I can see the benefit of supporting 'stream', but since Redis has various operations and its return types are different, so I'm wondering how can I create stream based on Redis response.
One more question, when there're some ERRs inside of stream, we can't use traditional approach - throwing JedisDataException because it would stop whole stream. 
Is it better to have a Option class which can have output or Exception?

**Comment by sdeleuze** [comment]
@HeartSaVioR Glad you like it. In term of API, some possible use cases for streams (`Observable`) are:
 - Return `Observable<?>` where you return `List<?>` in your current API.
 - Use it for Publish/Subscribe

You can see an example of converting Netty data pipeline to RxJava [here](https://github.com/sdeleuze/rxweb/blob/master/src/main/java/rxweb/engine/server/netty/NettyServerCodecHandlerAdapter.java) (using what RxJava call a `Subject` which is also an `Observable`.

**Comment by sdeleuze** [comment]
Exposing just a [Reactive Streams](http://www.reactive-streams.org/) based API, like Mongo is currently doing, could also make sense.

**Comment by ivansanchezvera** [comment]
@HeartSaVioR  is looking at an interesting direction, RxJava is great, couchbase client is using it and performance is great. 
Is easy to use but I thing its kinda tricky to implement.
RxJava is really reactive and saves you the hustle to deal with futures yourself.

**Comment by HeartSaVioR** [comment]
@ivansanchezvera 
Yes. Actually I feel very tricky to implement with RxJava because most of commands returns single value, and there're many kinds of return types.
But I also agree that callback could be hell, and Java Future (under Java 8) is not fully async, so I'll give it a try.

**Comment by msavy** [comment]
I broadly agree with @sdeleuze in that Futures are, unfortunately, largely useless in applications where non-blocking is required as well as asynchronicity. For instance, on a platform such as Vert.x, one cannot block the thread under any circumstances, and polling is drastically suboptimal, so callbacks (with the library itself using async techniques to avoid blocking) is required.

Of course the [Vert.x guys made their own implementation](https://github.com/vert-x/mod-redis), so you could use that for inspiration, but it'd be nice to have a generic client.

**Comment by darkcrawler01** [comment]
can't believe this issue is not resolved for 3 years. 
alternatives suggested ?

**Comment by samhendley** [comment]
This shouldn't be too tricky to do. The hardest part is you need to delegate a thread to consuming the server responses and feeding them into the futures you returned to your clients. 

Here is a snippet that uses an underlying Pipeline client that actually has alot of what we need other than a "pump thread". This isn't quite what we want since the subscribe method here will block waiting for each response. I don't have time to actually implement and test the full fledged version but I could provide guidance on how it can be implemented. (Or possibly if I get real bored one evening it might get done).

```java
public interface RxRedisCommands {
  Observable<Long> append(String key, String value);
  Observable<String> get(String key);
  Observable<Long> incr(String key);
}

class RxJedisClient implements RxRedisCommands {

    private final Pipeline pipeline;

    private volatile boolean keepRunning;
    private final AtomicLong outstandingResponses = new AtomicLong();

    public RxJedisClient(Pipeline client) {
        this.pipeline = client;
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (keepRunning) {
                    try {
                        while (outstandingResponses.get() > 0) {
                            pipeline.sync();
                        }
                        synchronized (outstandingResponses) {
                            while (outstandingResponses.get() == 0) {
                                outstandingResponses.wait();
                            }
                        }
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                }
            }
        });
    }

    public void destroy(){
        keepRunning = false;
        synchronized (outstandingResponses) {
            notify();
        }
    }

    protected <T> Observable<T> getObservable(final Response<T> response) {
        Observable<T> lr = Observable.create(new Observable.OnSubscribe<T>() {
            @Override
            public void call(Subscriber<? super T> subscriber) {
                subscriber.onNext(response.get());
                subscriber.onCompleted();
            }
        });

        outstandingResponses.incrementAndGet();
        synchronized (outstandingResponses) {
            notify();
        }
        return lr;
    }

    public Observable<Long> append(String key, String value) {
        return getObservable(pipeline.append(key, value));
    }

    @Override
    public Observable<String> get(String key) {
        return getObservable(pipeline.get(key));
    }

    @Override
    public Observable<Long> incr(String key) {
        return getObservable(pipeline.incr(key));
    }
}

```

**Comment by HeartSaVioR** [comment]
@samhendley Hey, thanks for guiding!
Actually I thought it could help us when only Observable has two or more responses to treat it stream.
Is there any noticeable overheads when we use Observable for each response?
If it isn't I'll apply RxJava to #713 and try to complete this long discussion. :)

**Comment by samhendley** [comment]
I personally haven't been sold that Observable<List<T>> should be flattened to Observable<T>. In the vast majority of the jedis cases that that wouldn't make so I think it would be confusing to apply it to the few places where it maps well. I would directly copy the PipelineCommands interface and just change Response<X> to Observable<X>. 

I look forward to seeing this applied to that PR.

**Comment by sdeleuze** [comment]
`Observable<List<T>>` is usually a code smell, and indeed using `Observable<T>` is far more better.

Also have a look to this issue (https://github.com/ReactiveX/RxJava/issues/1594) that intend to provide a promise like type in RxJava (a strong need from my POV).

**Comment by wongswoon** [comment]
@xetorthio what's the time dose asyncJedis RELESE ?
https://github.com/xetorthio/jedis-netty-exploration,the demo does not work

**Comment by frankxieke** [comment]
##does it work ansync Jedis client?

**Comment by ordiychen** [comment]
English not my primary language, but i try my best clearly describe  this question.I use vertx build a async mirco service. Vertx throw an “Thread Block" exception. I submit this exception details ，hope to help yours solve this problem.
```
<!-- pom -->
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.9.0</version>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
            <version>3.4.1</version>
        </dependency>
```
the code:
```
    public Future<List<String>> getUd(String rId,String em,String platform){
        Future<List<String>> reFuture = Future.future();
        try {
            String keyPrefix = "i";
            String bucketPrefix = "ib";
            if("a".equals(platform)){
                keyPrefix = "a";
                bucketPrefix = "ab";
            }
            String uids = jedisCluster.getJedisCluster().get(keyPrefix + em);
            if (StringUtils.isBlank(uids)){
                String key = bucketPrefix + em.substring(0,8);
                String filed = em.substring(8);
                uids = jedisCluster.getJedisCluster().hget(key, filed);
            }
            if (StringUtils.isBlank(uids)) {
                reFuture.tryFail(new RuntimeException(" data not found"));
            }else {
                log.info("{} have get uids {} ,will complete future ",rId,uids);
                reFuture.complete(Lists.newArrayList(uids.split(",")));
            }
        } catch (Exception e) {
            reFuture.tryFail(e.getCause());
        }
        return reFuture;
    }
```
log details
```
2017-07-20 15:51:40.534 [vertx-blocked-thread-checker] WARN  io.vertx.core.impl.BlockedThreadChecker:167- Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 2995 ms, time limit is 2000
2017-07-20 15:51:41.535 [vertx-blocked-thread-checker] WARN  io.vertx.core.impl.BlockedThreadChecker:167- Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 3996 ms, time limit is 2000
2017-07-20 15:51:42.535 [vertx-blocked-thread-checker] WARN  io.vertx.core.impl.BlockedThreadChecker:167- Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 4996 ms, time limit is 2000
2017-07-20 15:51:43.537 [vertx-blocked-thread-checker] WARN  io.vertx.core.impl.BlockedThreadChecker:167- Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 5997 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:184)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:836)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:434)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:66)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:141)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:141)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:31)
	at redis.clients.jedis.JedisCluster.get(JedisCluster.java:124)

	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118)
	at io.vertx.ext.web.impl.RouterImpl.accept(RouterImpl.java:79)
	at io.vertx.core.http.impl.ServerConnection.handleRequest(ServerConnection.java:285)
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:429)
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$createConnAndHandle$1(HttpServerImpl.java:763)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler$$Lambda$39/1904759218.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
	at io.vertx.core.impl.ContextImpl$$Lambda$22/214649470.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.createConnAndHandle(HttpServerImpl.java:757)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:621)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:573)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:76)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.http1(HttpServerImpl.java:1064)
	at io.vertx.core.http.impl.HttpServerImpl$Http1xOrHttp2Handler.channelRead(HttpServerImpl.java:1035)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by baiwfg2** [comment]
I also hope async redis would be available soon.

**Comment by marcosnils** [comment]
Let's continue the discussion here: #713
