### ISSUE TITLE
pipeline  Response  NullPointerException

### ISSUE THREAD

**Issue by shijinkui** [xetorthio/jedis#286]
调用的代码：

```
    Pipeline p = jedis.pipelined();
    Response<String> a = p.get(...
    Response<String> b = p.get(...
    Response<Set<String>> c = p.zrevrange(...
    p.sync();
```

报错的地方： jedis  Response.get()的时候，如果pipeline里有null的东西，就报错。

Response should be support null result. 

java.lang.NullPointerException
    at java.lang.String.<init>(String.java:515)
    at redis.clients.util.SafeEncoder.encode(SafeEncoder.java:28)
    at redis.clients.jedis.BuilderFactory$5.build(BuilderFactory.java:55)
    at redis.clients.jedis.BuilderFactory$5.build(BuilderFactory.java:58)
    at redis.clients.jedis.Response.get(Response.java:27)

**Comment by sunqb** [comment]
@ivowiblo thank you 。it is ok when i change the version to 2.1
