### ISSUE TITLE
java.util.NoSuchElementException: Could not create a validated object, cause: ValidateObject failed

### ISSUE THREAD

**Issue by swarupe04** [xetorthio/jedis#307]
jedis v2.1.0

Intermittently our webservice is failing against jedis call with following error:

redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:22)
...
Caused by: java.util.NoSuchElementException: Could not create a validated object, cause: ValidateObject failed
    at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1226)
    at redis.clients.util.Pool.getResource(Pool.java:20)

We're noticing this on read and r+w(master) pool

Config pool settings: 

-- readPool
rJedisPoolConfig.maxActive=200
rJedisPoolConfig.testOnBorrow=true
rJedisPoolConfig.minIdle=5
rJedisPoolConfig.maxIdle=10
rJedisPoolConfig.testWhileIdle=true
rJedisPoolConfig.numTestsPerEvictionRun=10
rJedisPoolConfig.timeBetweenEvictionRunsMillis=300000
# public static final byte WHEN_EXHAUSTED_GROW   = 2;

rJedisPoolConfig.whenExhaustedAction=2

-- writePool
rwJedisPoolConfig.maxActive=200
rwJedisPoolConfig.testOnBorrow=true
rwJedisPoolConfig.minIdle=5
rwJedisPoolConfig.maxIdle=10
rwJedisPoolConfig.testWhileIdle=true
rwJedisPoolConfig.numTestsPerEvictionRun=10
rwJedisPoolConfig.timeBetweenEvictionRunsMillis=300000
# public static final byte WHEN_EXHAUSTED_BLOCK  = 1;

rwJedisPoolConfig.whenExhaustedAction=1
rwJedisPoolConfig.maxWait=-1

**Comment by ankusht28** [comment]
i have slimier issue  when connect apache drill by below code 

Class.forName("mondrian.olap4j.MondrianOlap4jDriver");

		String cnxURL ="jdbc:mondrian:Jdbc=jdbc:drill:drillbit=127.0.0.1;JdbcDrivers=org.apache.drill.jdbc.Driver;Catalog='/home/ist/Downloads/testjson.xml';connectionPooling=false;";
        System.out.println(cnxURL);
        OlapConnection connection =
                (OlapConnection) DriverManager.getConnection(cnxURL);


Error:


Exception in thread "main" mondrian.olap.MondrianException: Mondrian Error:Internal error: Error while creating SQL connection: Jdbc=jdbc:drill:drillbit=127.0.0.1
	at mondrian.resource.MondrianResource$_Def0.ex(MondrianResource.java:992)
	at mondrian.olap.Util.newInternal(Util.java:2543)
	at mondrian.olap.Util.newError(Util.java:2559)
	at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:239)
	at mondrian.rolap.RolapSchema.<init>(RolapSchema.java:191)
	at mondrian.rolap.RolapSchemaLoader.loadStage1(RolapSchemaLoader.java:313)
	at mondrian.rolap.RolapSchemaLoader.loadStage0(RolapSchemaLoader.java:272)
	at mondrian.rolap.RolapSchemaLoader.createSchema(RolapSchemaLoader.java:4305)
	at mondrian.rolap.RolapSchemaPool.get(RolapSchemaPool.java:210)
	at mondrian.rolap.RolapSchemaPool.get(RolapSchemaPool.java:62)
	at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:160)
	at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:84)
	at mondrian.olap.DriverManager.getConnection(DriverManager.java:112)
	at mondrian.olap.DriverManager.getConnection(DriverManager.java:68)
	at mondrian.olap4j.MondrianOlap4jConnection.<init>(MondrianOlap4jConnection.java:153)
	at mondrian.olap4j.FactoryJdbc4Plus$AbstractConnection.<init>(FactoryJdbc4Plus.java:323)
	at mondrian.olap4j.FactoryJdbc41Impl$MondrianOlap4jConnectionJdbc41.<init>(FactoryJdbc41Impl.java:118)
	at mondrian.olap4j.FactoryJdbc41Impl.newConnection(FactoryJdbc41Impl.java:32)
	at mondrian.olap4j.MondrianOlap4jDriver.connect(MondrianOlap4jDriver.java:139)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.saiku.web.rest.util.MondrainJdbc.main(MondrainJdbc.java:27)
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, pool error Could not create a validated object, cause: null
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:114)
	at mondrian.rolap.RolapConnection.<init>(RolapConnection.java:212)
	... 18 more
Caused by: java.util.NoSuchElementException: Could not create a validated object, cause: null
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1008)
	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
	... 19 more

**Comment by ankusht28** [comment]
my error is something different from other errors it gives org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, pool error Could not create a validated object, cause: null when connect to apache drill;

**Comment by Bloodythirsty** [comment]
> I got the similar issue. In my scenario that is because of new JedisPool/3 timeout (default is 2000) so change to JedisPool/4 (with timeout) to solve the problem. I need a longer timeout because of several complex queries. BTW, my getResource() inside method by default.
> 
> the psudo processes are:
> 
> 1. getResource()
> 2. GenericObjectPool.borrowObject()
> 3. Jedis.ping() --> timeout
> 4. JedisPool$JedisFactory.validateObject() --> failed because obj NOT instanceof Jedis inside JedisPool.validateObject(final Object obj)
> 5. java.util.NoSuchElementException: Could not create a validated object, cause: ValidateObject failed
>    at org.apache.commons.pool.impl.GenericObjectPool.borrowObject
>    at redis.clients.util.Pool.getResource
> 
> hope this helps

hello, what's mean '/3'  of JedisPool/3 ?
