### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 8194

### ISSUE THREAD

**Issue by joeltheukranian** [xetorthio/jedis#332]
Hi,

We see the following error using Jedis 2.0.0. With Atmosphere and Jersey. (See exception at bottom)

We're using atmosphere-redis-1.0.0.beta1. (beta 5 has the same issue...just takes longer)

My first thought was making the following change at line 35 of RedisOutputStream

    public void write(final byte b) throws IOException {
==> if (count == buf.length) {
            flushBuffer();
        }
        buf[count++] = b;
    }:

Because other parts of RedisOutputStream flush first, this method does not.

Then I saw other forum posts saying setTestOnBorrow(true) in the pool. Which I don't see how it's related. Unless
it's somehow indirectly related to some multithreading issue.

Question: Is there any validity to my suggestion above?

Jul 30, 2012 8:34:09 PM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.ArrayIndexOutOfBoundsException: 8194
	at redis.clients.util.RedisOutputStream.write(RedisOutputStream.java:35)
	at redis.clients.jedis.Protocol.sendCommand(Protocol.java:34)
	at redis.clients.jedis.Protocol.sendCommand(Protocol.java:28)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:78)
	at redis.clients.jedis.BinaryClient.publish(BinaryClient.java:475)
	at redis.clients.jedis.Client.publish(Client.java:556)
	at redis.clients.jedis.Jedis.publish(Jedis.java:1980)
	at org.atmosphere.plugin.redis.RedisBroadcaster.outgoingBroadcast(RedisBroadcaster.java:233)
	at org.atmosphere.util.AbstractBroadcasterProxy.broadcast(AbstractBroadcasterProxy.java:143)
	at com.smarttech.pubsub.PubSub.publish(PubSub.java:42)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$VoidOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:167)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.atmosphere.util.AtmosphereFilterChain.doFilter(AtmosphereFilterChain.java:170)
	at org.atmosphere.util.AtmosphereFilterChain.invokeFilterChain(AtmosphereFilterChain.java:131)
	at org.atmosphere.handler.ReflectorServletProcessor$FilterChainServletWrapper.service(ReflectorServletProcessor.java:310)
	at org.atmosphere.handler.ReflectorServletProcessor.onRequest(ReflectorServletProcessor.java:168)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:241)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166)
	at org.atmosphere.container.JettyWebSocketUtil.doService(JettyWebSocketUtil.java:57)
	at org.atmosphere.container.JettyAsyncSupportWithWebSocket.service(JettyAsyncSupportWithWebSocket.java:66)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1208)
	at org.atmosphere.websocket.WebSocketProcessor.dispatch(WebSocketProcessor.java:181)
	at org.atmosphere.websocket.WebSocketProcessor$2.run(WebSocketProcessor.java:156)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.WebSocketProcessor.dispatch(WebSocketProcessor.java:151)
	at org.atmosphere.websocket.WebSocketProcessor.invokeWebSocketProtocol(WebSocketProcessor.java:139)
	at org.atmosphere.container.JettyWebSocketHandler.onMessage(JettyWebSocketHandler.java:110)
	at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455$WSFrameHandler.onFrame(WebSocketConnectionRFC6455.java:845)
	at org.eclipse.jetty.websocket.WebSocketParserRFC6455.parseNext(WebSocketParserRFC6455.java:359)
	at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455.handle(WebSocketConnectionRFC6455.java:235)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
	at java.lang.Thread.run(Unknown Source)

Thanks,
Joel

**Comment by marcosnils** [comment]
This has been fixed already
