### ISSUE TITLE
ClassCastException in 2.1.0 (getBinaryBulkReply)

### ISSUE THREAD

**Issue by ex-nerd** [xetorthio/jedis#359]
Sorry, my logs truncated this.

java.lang.ClassCastException: java.lang.Long cannot be cast to [B
at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:182)
at redis.clients.jedis.Connection.getBulkReply(Connection.java:171)
at redis.clients.jedis.Jedis.get(Jedis.java:67)

I'm using a connection pool, and noticed that there was an earlier exception:

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
at redis.clients.jedis.Protocol.process(Protocol.java:79)
at redis.clients.jedis.Protocol.read(Protocol.java:131)
at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:182)
at redis.clients.jedis.Connection.getBulkReply(Connection.java:171)
at redis.clients.jedis.Jedis.get(Jedis.java:67)

It looks like my code was not calling returnBrokenResource() on the broken resource, and returning it to the pool as normal.  However, Jedis should probably still do something to catch that class cast exception.

**Comment by EdwardLee03** [comment]
If Jedis operation happens Exception, it must be calling returnBrokenResource() on the broken resource, that the broken resouce will be destroyed.

**Comment by marcosnils** [comment]
@idyedov @joeyzhu0422 you should never use a Jedis instance in a multi-threaded environment. That's why JedisPool exists. Have you checked out the part of the wiki that mentions it? (https://github.com/xetorthio/jedis/wiki/Getting-started#using-jedis-in-a-multithreaded-environment) 

Are you still getting this error in a non-multithread env?
