### ISSUE TITLE
brpop(String arg) not availible

### ISSUE THREAD

**Issue by looly** [xetorthio/jedis#457]
The method public List<String> brpop(String arg)  provide only one parameter,but I found that command BLPOP need at least 2 parameter, and Jedis not give the default timeout.

**Comment by JensRantil** [comment]
Somewhat related; I am getting
```
ERROR [2015-05-06 13:26:52,953] se.tink.backend.common.workers.transaction.global.BillionDollarCounter: Something went wrong when processing.
! redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'brpop' command
! at redis.clients.jedis.Protocol.processError(Protocol.java:113) ~[jedis-2.6.2.jar:na]
! at redis.clients.jedis.Protocol.process(Protocol.java:138) ~[jedis-2.6.2.jar:na]
! at redis.clients.jedis.Protocol.read(Protocol.java:192) ~[jedis-2.6.2.jar:na]
! at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282) ~[jedis-2.6.2.jar:na]
! at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:218) ~[jedis-2.6.2.jar:na]
! at redis.clients.jedis.BinaryJedis.brpop(BinaryJedis.java:1909) ~[jedis-2.6.2.jar:na]
! at redis.clients.jedis.BinaryJedis.brpop(BinaryJedis.java:1890) ~[jedis-2.6.2.jar:na]
```
when executing
```java
final byte[] QUEUE_NAME = "my-queue-name".getBytes(Charsets.UTF_8);
redis.brpop(QUEUE_NAME);
```

**Comment by JensRantil** [comment]
Regarding https://github.com/xetorthio/jedis/issues/457#issuecomment-99465016, I'd love to hear if there are any workaround for it.

**Comment by HeartSaVioR** [comment]
@JensRantil 
We deprecated blpop / brpop() with singular parameter (since it doesn't make sense), and it will be removed to 3.0.0.
Please specify timeout when you use brpop(). Thanks!
