### ISSUE TITLE
jeids 2.2.1, JedisConnectionException( "Could not get a resource from the pool")

### ISSUE THREAD

**Issue by mittalnanu** [xetorthio/jedis#649]
Hi,
I have around 4.5K Connected clients to the redis server, I have started seeing this error intermittently, when trying to get a resource from the pool. It is because of socket timed out
StackTrace
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: connect timed out
! at redis.clients.jedis.Connection.connect(Connection.java:137) 

Increasing the timeout may help, but is it well established that getting a resource from pool may take time as the number of connected clients increase on the server?

**Comment by yamucd** [comment]
hi giridharkannan,
I too have a similar issue when i conduct a fail-over test .I have master & slave configuration setup.I conducted a fail-over test in which i make the master redis go down forcefully & monitor the switch (the slave gets promoted to master) but the issue is that my java based web application is not able to reconnect to the new master.

The following exception is observed in the application logs:

[#|2015-01-27T11:38:11.582+0530|SEVERE|glassfish3.1.2|com.gsm.GSMJedisWrapper|_ThreadID=45;_ThreadName=Thread-2;|Executing redis operation
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.util.Pool.getResource(Pool.java:42)
        at com.gsm.nosql.redis.MyJedisPool.getResource(MyJedisPool.java:156)
        at com.gsm.nosql.redis.JedisStorageAddress.giveMePipeline(JedisStorageAddress.java:46)
        at com.gsm.nosql.redis.GSMJedisWrapper$ExecutorDatabaseInfo.pipeline(GSMJedisWrapper.java:1052)
        at com.gsm.nosql.redis.GSMJedisWrapper$4.exec(GSMJedisWrapper.java:283)
        at com.gsm.nosql.redis.GSMJedisWrapper$4.exec(GSMJedisWrapper.java:266)
        at com.gsm.nosql.redis.GSMJedisWrapper.execInRedis(GSMJedisWrapper.java:955)
        at com.gsm.nosql.redis.GSMJedisWrapper.getMappedId(GSMJedisWrapper.java:303)
        at com.gsm.pe.util.ReportQueue.workOnElement(ReportQueue.java:905)
        at com.gsm.pe.util.ReportQueue.commitItem(ReportQueue.java:845)
        at com.gsm.pe.util.ReportQueue.process(ReportQueue.java:352)
        at com.gsm.lib.BatchRunner.processElements(BatchRunner.java:286)
        at com.gsm.lib.BatchRunner.flushBatch(BatchRunner.java:164)
        at com.gsm.lib.BatchRunner.run(BatchRunner.java:80)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused
        at redis.clients.jedis.Connection.connect(Connection.java:150)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:71)
        at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1783)
        at com.gsm.nosql.redis.MyJedisPool$MyJedisFactory.create(MyJedisPool.java:96)
        at com.gsm.nosql.redis.MyJedisPool$MyJedisFactory.create(MyJedisPool.java:57)
        at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:57)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
        at redis.clients.util.Pool.getResource(Pool.java:40)
        ... 13 more
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
        at java.net.Socket.connect(Socket.java:529)
        at redis.clients.jedis.Connection.connect(Connection.java:144)
        ... 22 more
Output of  info of the slave redis(promoted to master)
# Server
redis_version:2.8.12
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:64aab4accb88e464
redis_mode:standalone
os:Linux 2.6.32-431.5.1.el6.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.4.7
process_id:23474
run_id:ba98cedb708e9b16d81a694453e0d6ba1b2977f4
tcp_port:6379
uptime_in_seconds:7
uptime_in_days:0
hz:10
lru_clock:13074796
config_file:/etc/redis/6379.conf

# Clients
connected_clients:8
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:1938128
used_memory_human:1.85M
used_memory_rss:8495104
used_memory_peak:3360168
used_memory_peak_human:3.20M
used_memory_lua:33792
mem_fragmentation_ratio:4.38
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1422360933
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:202
total_commands_processed:13109
instantaneous_ops_per_sec:5401
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:4333
keyspace_misses:2847
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:0

# Replication
role:master
connected_slaves:0
min_slaves_good_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.21
used_cpu_user:0.09
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Keyspace
db0:keys=2396,expires=0,avg_ttl=0
db1:keys=1,expires=0,avg_ttl=0

Please advise

**Comment by yamucd** [comment]
also observed 

[#|2015-01-27T14:27:40.934+0530|SEVERE|glassfish3.1.2|com.gsm.Queue(com.gsm.nsca.Alerter$IncidentFlusher)|_ThreadID=54;_ThreadName=Thread-2;|Failed to flush incidentcom.gsm.nsca.IncidentRecord@1c89a54
java.lang.RuntimeException: com.mongodb.MongoInternalException: DBObject of size 146490322 is over Max BSON size 16777216
        at com.gsm.nsca.IncidentRecord.flush(IncidentRecord.java:171)
        at com.gsm.nsca.Alerter$IncidentFlusher.process(Alerter.java:675)
        at com.gsm.lib.BatchRunner.processElements(BatchRunner.java:286)
        at com.gsm.lib.BatchRunner.flushBatch(BatchRunner.java:164)
        at com.gsm.lib.BatchRunner.run(BatchRunner.java:80)
Caused by: com.mongodb.MongoInternalException: DBObject of size 146490322 is over Max BSON size 16777216
        at com.mongodb.OutMessage.putObject(OutMessage.java:291)
        at com.mongodb.OutMessage.writeUpdate(OutMessage.java:180)
        at com.mongodb.OutMessage.update(OutMessage.java:60)
        at com.mongodb.DBCollectionImpl.update(DBCollectionImpl.java:275)
        at com.mongodb.DBCollection.update(DBCollection.java:191)
        at com.mongodb.DBCollection.update(DBCollection.java:224)
        at com.mongodb.DBCollection.update(DBCollection.java:239)
        at com.gsm.nsca.IncidentRecord.flush(IncidentRecord.java:146)

**Comment by marcosnils** [comment]
@yamucd updates about this?

**Comment by Suvitruf** [comment]
Got same error yesterday. Don't know what to do. I tried ti restart master and sentinel. Didn't help.

ulimit is unlimited

redis-cli
127.0.0.1:6379> info
# Server
redis_version:3.0.4
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:47b0fba1c819f80c
redis_mode:standalone
os:Linux 3.13.0-55-generic x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.8.4
process_id:2177
run_id:1ea2afd7eb6f3db1434f467ad465687eef68cc3c
tcp_port:6379
uptime_in_seconds:1477594
uptime_in_days:17
hz:10
lru_clock:4994250
config_file:/etc/redis/redis.conf

# Clients
connected_clients:2
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:848976
used_memory_human:829.08K
used_memory_rss:2199552
used_memory_peak:848976
used_memory_peak_human:829.08K
used_memory_lua:36864
mem_fragmentation_ratio:2.59
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:798
rdb_bgsave_in_progress:0
rdb_last_save_time:1446357232
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:3
total_commands_processed:1244
instantaneous_ops_per_sec:0
total_net_input_bytes:110167
total_net_output_bytes:54602
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:359
keyspace_misses:7
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:646.91
used_cpu_user:239.66
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=8,expires=0,avg_ttl=0
