### ISSUE TITLE
Exception in thread "main" redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?

### ISSUE THREAD

**Issue by feidaodalian** [xetorthio/jedis#650]
hi：
   I have a question,my redis- cluster: 
master：10.16.15.174:8000 10.16.15.174:8001  10.16.15.184:7001  10.16.15.184:7002  
slave：   10.16.15.184:7000   10.16.15.174:8002

my java code: 

   public static void main(String[] args) {

        Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
      jedisClusterNodes.add(new HostAndPort("10.16.15.184", 7001));
      jedisClusterNodes.add(new HostAndPort("10.16.15.184", 7002));
      JedisCluster jc = new JedisCluster(jedisClusterNodes);
      for(int i=1;i<=10000;i++){
          jc.set("test5-"+i, "str"+i);
          System.out.println("------------------"+i+"------------");
      }
      System.out.println("finsh!");
    }

but ,when i is 93 ,it throws exception .

Exception in thread "main" redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?

The jedis version is  2.5
Please help me.

**Comment by maxthomas** [comment]
Just adding some data to this if it helps: I'm also getting this error. 3 node cluster, all masters, redis version 3.0.0, jedis version 3.0-SNAPSHOT, commit: 08a22fa7f049eea4a12a25cb7d6e22ca5beed99e

Stack trace:
```sh
Caused by: redis.clients.jedis.exceptions.JedisClusterMaxRedirectionsException: Too many Cluster redirections?
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:97) ~[pipeline-core-4.4.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:127) ~[pipeline-core-4.4.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:140) ~[pipeline-core-4.4.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:127) ~[pipeline-core-4.4.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:140) ~[pipeline-core-4.4.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:127) ~[pipeline-core-4.4.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:59) ~[pipeline-core-4.4.5-SNAPSHOT-jar-with-dependencies.jar:?]
        at redis.clients.jedis.BinaryJedisCluster.rpush(BinaryJedisCluster.java:465) ~[pipeline-core-4.4.5-SNAPSHOT-jar-with-dependencies.jar:?]
```

**Comment by marcosnils** [comment]
@maxthomas this issue is way too old and describes a specific scenario with an older version of Jedis.

Please open another issue describing your cluster configuration, and a snippet (if possible) to reproduce the error.
