### ISSUE TITLE
Could not get a resource from the pool when use try-with-resources

### ISSUE THREAD

**Issue by lipiji** [xetorthio/jedis#661]
Hi,

I a multi-thread application, I add data like this:

```
public void add(data) {
        try (ShardedJedis shardedJedis = shardedJedisPool.getResource()) {
            shardedJedis.zadd(KEY, data);
        }
    }
```

However,  I catch the exception again:

```

redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:42)
    at redis.clients.jedis.ShardedJedisPool.getResource(ShardedJedisPool.java:37)

Caused by: java.util.NoSuchElementException: Unable to validate object
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:497)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
    at redis.clients.util.Pool.getResource(Pool.java:40)
    ... 8 more
```

It runs well when use version 2.4.2 without try-with-resources.

**Comment by srirama-rayaprolu** [comment]
In production setup, am getting the same error,
```
redis.clients.jedis.exceptions.JedisExhaustedPoolException: Could not get a resource since the pool is exhausted
	at redis.clients.jedis.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288)
        ...
        ...
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: Unable to validate object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:506)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 6 common frames omitted

```

The Jedis version is 3.3.0 and Redis version is 4.0.9

I have increased the connection timeout to 50 sec but still getting the same problem.

Any other pointers here to be checked?

**Comment by LuisEC2016** [comment]
How did you solve it?
