### ISSUE TITLE
pipelined eval return type needs to be changed

### ISSUE THREAD

**Issue by raghavam** [xetorthio/jedis#690]
I am using Jedis 2.5.1. All pipeline eval forms return String and this might lead to ClassCastException if the return value from the Lua script cannot be cast to a String. For example, in my case I return an array of strings and this cannot be cast to a String. I get the following exception

Exception in thread "main" java.lang.ClassCastException: java.util.ArrayList cannot be cast to [B
	at redis.clients.jedis.BuilderFactory$5.build(BuilderFactory.java:56)
	at redis.clients.jedis.BuilderFactory$5.build(BuilderFactory.java:54)
	at redis.clients.jedis.Response.build(Response.java:51)
	at redis.clients.jedis.Response.get(Response.java:36)

I think it is better if the return type of pipeline eval is Object i.e., Response<Object> as in non-pipelined versions.

Sample script which generates the ClassCastException,

```
String script = "local t = {} " +
	"t[1] = 'a' " +
	"t[2] = 'b' " +
	"return t ";

**Comment by nykolaslima** [comment]
@HeartSaVioR @marcosnils since #607 was merged, can we close this issue?
