### ISSUE TITLE
Getting Exception while trying to do a jedis.get() command - ClassCastException

### ISSUE THREAD

**Issue by jiminoc** [xetorthio/jedis#72]
I have pasted the Exception that I'm getting below using version 1.5.0. I'm attempting to use the pool to pull jedis objects out of to use:

jedisPool = new JedisPool(new GenericObjectPool.Config(), "cache01");

and here is the thread code that I'm using to check the cache:
http://pastebin.com/icTDwFNH

it happens intermittently but when it does it floods the logs with these error messages. Any ideas?

SEVERE: java.lang.ClassCastException: [B cannot be cast to java.lang.Long ::--> om.mysite.something.getCache updateCache
java.lang.ClassCastException: java.lang.Long cannot be cast to [B
    at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:163)
    at redis.clients.jedis.Connection.getBulkReply(Connection.java:153)
    at redis.clients.jedis.Jedis.get(Jedis.java:68)
    at com.mysite.something.getCache(Cache.java:19)

**Comment by deepakpol** [comment]
Hi,

I am getting into this issue while using Jedis with spring data redis integration. I am setting the configuration to use pool, testOnBorrow as well as testOnReturn true.

I am using Jedis pool, and have verified that spring ensures the resources are returned to the pool, by calling returnResource() and returnBrokenResource in case of exceptions. Still facing this issue. I have a heavily multi-threaded environment.

Error stack - 

Thread 1:
[ERROR] [03/01/2015 07:05:32.044] [events-system-akka.actor.default-dispatcher-2281] [akka://events-system/user/$YN/$b/$b/$b] java.lang.Long cannot be cast to java.util.List
java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.List
    at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:230)
    at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:236)
    at redis.clients.jedis.BinaryJedis.zscan(BinaryJedis.java:3608)
    at org.springframework.data.redis.connection.jedis.JedisConnection$3.doScan(JedisConnection.java:2998)
    at org.springframework.data.redis.core.KeyBoundCursor.doScan(KeyBoundCursor.java:39)
    at org.springframework.data.redis.core.ScanCursor.scan(ScanCursor.java:85)
    at org.springframework.data.redis.core.ScanCursor.hasNext(ScanCursor.java:168)
    at org.springframework.data.redis.core.ConvertingCursor.hasNext(ConvertingCursor.java:56)
    ...
    application specific stack trace
    ...

Thread 2:    
[ERROR] [03/01/2015 07:03:07.295] [events-system-akka.actor.default-dispatcher-2273] [akka://events-system/user/$VN/$b/$b/$b] Unknown redis exception; nested exception is java.lang.ClassCastException: [B cannot be cast to java.lang.Long
org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is java.lang.ClassCastException: [B cannot be cast to java.lang.Long
    at org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:48)
    at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:38)
    at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:195)
    at org.springframework.data.redis.connection.jedis.JedisConnection.zRem(JedisConnection.java:2321)
    at org.springframework.data.redis.core.DefaultZSetOperations$19.doInRedis(DefaultZSetOperations.java:283)
    at org.springframework.data.redis.core.DefaultZSetOperations$19.doInRedis(DefaultZSetOperations.java:280)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:190)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:152)
    at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:85)
    at org.springframework.data.redis.core.DefaultZSetOperations.remove(DefaultZSetOperations.java:280)
    ...
    application specific stack trace
    ...
Caused by: java.lang.ClassCastException: [B cannot be cast to java.lang.Long
    at redis.clients.jedis.Connection.getIntegerReply(Connection.java:210)
    at redis.clients.jedis.BinaryJedis.zrem(BinaryJedis.java:1624)
    at org.springframework.data.redis.connection.jedis.JedisConnection.zRem(JedisConnection.java:2319)
    ... 21 more

**Comment by HeartSaVioR** [comment]
@deepakpol Could you please post an new issue? Please describe Jedis version and Spring data redis version, too. :)

**Comment by deepakpol** [comment]
Created a new issue https://github.com/xetorthio/jedis/issues/918
