### ISSUE TITLE
Cant connect to Redis using Jedis after JedisConnectionException.

### ISSUE THREAD

**Issue by jijojose1691** [xetorthio/jedis#882]
Hi,
In my application(code given below), one thread will always push the data to the Redis using Jedis with help of Jedispool. The real problem is it will not reconnect automatically to the server after any network outreach, . It throws JedisConnectionException if my server is down. In the try-catch block, I handle this using returnBrokenResource() .But I got another exception while using retrunbrokensource() method. Please correct me anything wrong? 

JedisFactory.java
================================================================================
package com.mySample;

import redis.clients.jedis.JedisPool;
import redis.clients.jedis.JedisPoolConfig;

class JedisFactory {
	private static JedisPool jedisPool;
	private static JedisFactory instance = null;

	public JedisFactory() {

		JedisPoolConfig poolConfig = new JedisPoolConfig();
		poolConfig.setTestOnBorrow(true);
		jedisPool = new JedisPool(poolConfig, REDIS_HOST, 6379);

	}

	public JedisPool getJedisPool() {
		return jedisPool;
	}

	public static JedisFactory getInstance() {
		if (instance == null) {
			instance = new JedisFactory();
		}
		return instance;
	}
}

TestJedis.java
===============================================================================

package com.mySample;

import org.apache.log4j.Logger;

import redis.clients.jedis.Jedis;
import redis.clients.jedis.exceptions.JedisConnectionException;

public class TestJedis {

	private static final Logger LOGGER = Logger.getLogger(TestJedis.class);
	private Jedis jedis = null;
	JedisFactory jedisFactory = null;

	public TestJedis() {
		this.jedis = JedisFactory.getInstance().getJedisPool().getResource();
	}

	public void push() {

		try {

			LOGGER.info("Server is running: " + jedis.ping());
			if (jedis.isConnected()) {
				LOGGER.info("connected");
			}
			jedis.set("test", "set");

		} catch (JedisConnectionException jex) {
			LOGGER.info("Got jedis conncetion exception ", jex);
			try {
				JedisFactory.getInstance().getJedisPool().returnBrokenResource(jedis);
			} catch (Exception e) {
				LOGGER.info("jedis returnBrokenResource Exception**********", e);
			}

		} finally {
			try{
				if(null != jedis)
				JedisFactory.getInstance().getJedisPool().returnResource(jedis);
			} catch (Exception e) {
				LOGGER.info("jedis  returnResource Exception**********", e);
			}
	
		}
	}
}

JedisThread.java
=========================================================================================
package com.mySample;

public class JedisThread {

	public static void main(String args[]) {
		new ThreadTest().start();
	}
}

class ThreadTest extends Thread {
	public ThreadTest() {
		super();
	}

	public void run() {
		TestJedis jedis = new TestJedis();
		while (true) {
			try {
				jedis.push();
			} catch (Exception e) {
				System.out.println("Got exception");
			}
		}

	}
}

While I executing the code, (Redis server is running), I got following error:

INFO : com.mySample.TestJedis - Server is running: PONG
INFO : com.mySample.TestJedis - connected
INFO : com.mySample.TestJedis - jedis  returnResource Exception**********
redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnResourceObject(Pool.java:54)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:91)
	at com.mySample.TestJedis.push(TestJedis.java:39)
	at com.mySample.ThreadTest.run(JedisThread.java:19)
Caused by: java.lang.IllegalStateException: Object has already been retured to this pool or is invalid
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:582)
	at redis.clients.util.Pool.returnResourceObject(Pool.java:52)
	... 3 more

Suppose if I stop the redis server, then error is:

INFO : com.mySample.TestJedis - jedis  returnResource Exception**********
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Socket closed
	at redis.clients.jedis.Connection.flush(Connection.java:70)
	at redis.clients.jedis.Connection.getAll(Connection.java:243)
	at redis.clients.jedis.Connection.getAll(Connection.java:238)
	at redis.clients.jedis.BinaryJedis.resetState(BinaryJedis.java:1733)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:90)
	at com.mySample.TestJedis.push(TestJedis.java:39)
	at com.mySample.ThreadTest.run(JedisThread.java:19)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at redis.clients.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:31)
	at redis.clients.util.RedisOutputStream.flush(RedisOutputStream.java:223)
	at redis.clients.jedis.Connection.flush(Connection.java:68)
	... 6 more

**Comment by marcosnils** [comment]
@jijojose1691 I don't see that you're getting an error when trying to return the broken resource into the pool. From the stack that you provided I can't see that `jedis returnBrokenResource Exception**********` is actually appearing
Are you entirely sure that you're getting an exception when trying to return the broken resource?

**Comment by jijojose1691** [comment]
Hi ,
I am extremely sorry to provide the stack trace. When Redis server is down, I got below exception:

INFO : com.mySample.TestJedis - Got jedis conncetion exception 
redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused: connect
	at redis.clients.jedis.Connection.connect(Connection.java:142)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:75)
	at redis.clients.jedis.Connection.sendCommand(Connection.java:90)
	at redis.clients.jedis.BinaryClient.ping(BinaryClient.java:88)
	at redis.clients.jedis.BinaryJedis.ping(BinaryJedis.java:64)
	at com.mySample.TestJedis.push(TestJedis.java:22)
	at com.mySample.ThreadTest.run(JedisThread.java:19)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:69)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:157)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391)
	at java.net.Socket.connect(Socket.java:579)
	at redis.clients.jedis.Connection.connect(Connection.java:137)
	... 6 more
INFO : com.mySample.TestJedis - jedis returnBrokenResource Exception**********
redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:79)
	at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:84)
	at com.mySample.TestJedis.push(TestJedis.java:31)
	at com.mySample.ThreadTest.run(JedisThread.java:19)
Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:620)
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:77)
	... 3 more

**Comment by marcosnils** [comment]
@jijojose1691 I've found a problem in your example. The `TestJedis` class is always using the same instance of Jedis as it's being retrieved in the class constructor. That's why you're receiving exceptions when trying to return the broken resource because that Jedis instance was already returned before. 

You need put the following line ` this.jedis = JedisFactory.getInstance().getJedisPool().getResource();` inside your push method so you get a new jedis instance each time the method is called. 

Give it a try and let us know the results.

**Comment by jijojose1691** [comment]
@marcosnils Thanks Macros. Its working now.

**Comment by henry20100102** [comment]
@marcosnils  I met a similar problem:
redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:85)
	at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:98)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:113)
	at redis.clients.jedis.JedisClusterConnectionHandler.returnConnection(JedisClusterConnectionHandler.java:20)
	at redis.clients.jedis.JedisClusterCommand.releaseConnection(JedisClusterCommand.java:95)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:85)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:29)
	at redis.clients.jedis.JedisCluster.hincrBy(JedisCluster.java:381)
.........................
Caused by: java.lang.IllegalStateException: Invalidated object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:643)
	at redis.clients.util.Pool.returnBrokenResourceObject(Pool.java:83)
	... 16 more

**Comment by WangXijue** [comment]
@marcosnils @henry20100102 @jijojose1691 
Because the "finally" was executed before "catch", and the resource had been return to pool in "finally" block.

**Comment by javadev** [comment]
+
