### ISSUE TITLE
JedisPool "Could not return the resource to the pool" exception 

### ISSUE THREAD

**Issue by benkris1** [xetorthio/jedis#895]
Getting "Could not return the resource to the pool" Exception while calling JedisPool.returnResource()

this.pool = new JedisPool(poolConfig, ip, port);// in constructor

 public Set<String> zrevrange(String key, long start, long stop) throws RedisException {
        Set<String> result = null;
        try {
            if (key == null) return result;
            Jedis jedis = pool.getResource();
            try {
                result = jedis.zrevrange(key, start, stop);
            } catch (Exception e) {
                returnBrokenResource(jedis);
                throw e;
            } finally {
                if (null != jedis) {
                    pool.returnResource(jedis);
                }

            }
        } catch (Exception e) {
            throw new RedisException("UnShardingRedisProxy zrevrange(key,start,stop) exception, key is :" + key + ", start is : " + start + ", stop is : " + stop, e);
        }
        return result;
    }
com.zcloud.sun.cache.jedis.RedisException: UnShardingRedisProxy zrevrange(key,start,stop) exception, key is :push.agent.slaver1-push.msg.group.queue, start is : 0, stop is : 0
	at com.zcloud.sun.cache.jedis.UnShardingRedisProxy.zrevrange(UnShardingRedisProxy.java:1512)
	at com.zcloud.sun.cache.jedis.RedisCache.zPop(RedisCache.java:208)
	at com.zcloud.vtx.module.push.channel.message.DispatcherMsgGroup$1.run(DispatcherMsgGroup.java:71)
Caused by: redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
	at redis.clients.util.Pool.returnResourceObject(Pool.java:65)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:113)
	at com.zcloud.sun.cache.jedis.UnShardingRedisProxy.zrevrange(UnShardingRedisProxy.java:1507)
	... 2 more
Caused by: java.lang.IllegalStateException: Returned object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:534)
	at redis.clients.util.Pool.returnResourceObject(Pool.java:63)
	... 4 more

**Comment by HeartSaVioR** [comment]
You're returning Jedis object twice when there's a Exception occurs on it, which one is using returnBrokenResource(), and other one is using returnResource().

If you use JDK7 or higher, you can avoid mistake by try-with-resources, or you can simply jedis.close() on finally statement.

See https://github.com/xetorthio/jedis/wiki/Getting-started#using-jedis-in-a-multithreaded-environment for more details.

**Comment by HeartSaVioR** [comment]
@qiansj Could you please check you're having issue with same reason? Thanks!

**Comment by benkris1** [comment]
@HeartSaVioR  Thank you!

**Comment by qiansj** [comment]
@HeartSaVioR redis operation, command must with key or value parameter, e.g: set a 123,
if the command has only "set " without any parameter, it occured error. THen, in my java code, release jedis resource occured error "Could not return the resource to the pool", 
but it has "finally" code block, so, it also contains another error “Could not return the resource to the current  pool” , just for ref. , that's my problem.
