### ISSUE TITLE
redis.clients.jedis.JedisException: java.net.SocketException: Bad file descriptor

### ISSUE THREAD

**Issue by johanhaleby** [xetorthio/jedis#91]
Hi, 

We frequently run into a "Bad file descriptor" when working with Jedis under moderate load. We're using the JedisPool and have configured testOnBorrow to true. Stack trace may look like:

redis.clients.jedis.JedisException: java.net.SocketException: Bad file descriptor
    at redis.clients.jedis.Protocol.sendCommand(Protocol.java:47)
    at redis.clients.jedis.Protocol.sendCommand(Protocol.java:26)
    at redis.clients.jedis.Connection.sendCommand(Connection.java:83)
    at redis.clients.jedis.BinaryClient.flushAll(BinaryClient.java:116)
    at redis.clients.jedis.Jedis.flushAll(Jedis.java:373)
..
Caused by: java.net.SocketException: Bad file descriptor
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
    at redis.clients.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:29)
    at redis.clients.util.RedisOutputStream.flush(RedisOutputStream.java:227)
    at redis.clients.jedis.Protocol.sendCommand(Protocol.java:45)
    ... 32 more

We're using Jedis 1.5.1. Do you have any idea what may be causing this?

/Johan

**Comment by danmaina** [comment]
Try and remove any jedis.close() or jedis.disconnect() if you are using a connection pool.

**Comment by Force-King** [comment]
I also ran into this problem, reporting the following error after setTestOnBorrow(true)：

```
redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:51)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at io.codis.jodis.RoundRobinJedisPool.getResource(RoundRobinJedisPool.java:218)
	at com.br.hermes.center.service.impl.IndexServiceV3Impl.initLimitProductMap(IndexServiceV3Impl.java:2780)
	at com.br.hermes.center.quartz.SendMailQuartz.refreshFlowControllConfig(SendMailQuartz.java:608)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: Unable to validate object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:506)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	... 19 more
15:40:01.399 INFO  
```

**Comment by vercorro** [comment]
> I also had this problem, setting TestOnBorrow to true still had an error :

Did you fixed it? 
I have the same issue. Please help as I dont find anything related to this problem.
