### ISSUE TITLE
Intermittent "ERR Wrong CLUSTER subcommand..." error on 2.6.2 

### ISSUE THREAD

**Issue by DerekOverlock** [xetorthio/jedis#922]
I noticed weird behavior with version 2.6.2 that I have not seen at all on 2.4.2. Sometimes when I do a `get` or `set` I receive the following error: 

    redis.clients.jedis.exceptions.JedisDataException: ERR Wrong CLUSTER subcommand or number of arguments

I tried adding breakpoints and debugging in Eclipse, and sometimes the issue will resolve itself. I can confirm that the Redis cluster is online. The version of Redis is 3.0-beta2.

Please note that these same set of commands work fine with 2.4.2.

Thanks!

**Comment by marcosnils** [comment]
@DerekOverlock is there a way you can share a small use case (some code) where you're observing this issue?. I've used Jedis Cluster extensively and I've never experienced the issue you're seeing. 

Thanks

**Comment by DerekOverlock** [comment]
@marcosnils Sure. I set this up in a unit test:

    JedisClient jc = new JedisClient();
    String test= "[{\"siteId\":-1,\"name\":\"name\",\"latitude\":1,\"longitude\":1}]";
    jc.set("scv-sites", test);

And received the following exception:

    RedisRuntimeException: redis.clients.jedis.exceptions.JedisDataException: ERR Wrong CLUSTER subcommand or number of arguments
        at c.h.i.jedis.JedisClient.retry(JedisClient.java:111)
	at c.h.i.jedis.JedisClient.set(JedisClient.java:61)
	at c.h.i.scv.mobile.rest.RestTest.test1(RestTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
    Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Wrong CLUSTER subcommand or number of arguments
	at redis.clients.jedis.Protocol.processError(Protocol.java:113)
	at redis.clients.jedis.Protocol.process(Protocol.java:138)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282)
	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:227)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:233)
	at redis.clients.jedis.Jedis.clusterSlots(Jedis.java:3173)
	at redis.clients.jedis.JedisClusterInfoCache.discoverClusterSlots(JedisClusterInfoCache.java:58)
	at redis.clients.jedis.JedisClusterConnectionHandler.renewSlotCache(JedisClusterConnectionHandler.java:71)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:78)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:32)
	at redis.clients.jedis.JedisCluster.set(JedisCluster.java:71)
	at c.h.i.jedis.JedisClient.set(JedisClient.java:58)
	... 26 more

`JedisClient` is just a wrapper utility class we have that reads a properties file and sets up a `JedisCluster` object. `JedisClient` will forward `JedisCluster` commands like so:

     public String get(final String key) throws RedisRuntimeException {
          int attempt = 0;
      //Loop until we either return or throw and exception
      while (true) {
         try {
            return jc.get(key);
         } catch (Exception e) { //NOPMD
            retry(attempt, e);
            attempt++;
         }
      }
    }

**Comment by HeartSaVioR** [comment]
CLUSTER SLOTS was introduced from 3.0.0-beta7, and now Redis's latest test version is 3.0.0-rc4.
You should upgrade your Redis version.
If it doesn't resolve your issue, please reopen this issue. Thanks! :)

**Comment by DerekOverlock** [comment]
Finally upgraded to Redis 3.0.0 (stable), still seeing this error while using Jedis 2.6.2, will try downgrading to Jedis 2.4 again to see if that fixes the issue.

**Comment by marcosnils** [comment]
@DerekOverlock I'll give it a try with Redis 3.0 stable and let u know my results

**Comment by DerekOverlock** [comment]
It appears some of the nodes were still using the old redis properties file, and was connecting to the old unstable 3.0b2 cluster, I'll test with 2.6.2 again and see if I find any more 'ERR Wrong Number' messages!

**Comment by marcosnils** [comment]
amazing @DerekOverlock I've just run 2.6.2 cluster tests against 3.0 stable and everything went fine, you shouldn't experience any problems.
