### ISSUE TITLE
Cannot instantiate BinaryJedisCluster in jedis-3.0.0

### ISSUE THREAD

**Issue by vlebedev** [xetorthio/jedis#957]
When I tried to instantiate BinaryJedisCluster via:

`BinaryJedisCluster jcb = new BinaryJedisCluster(jedisClusterNodes);`

I got the following exception:

`Exception in thread "main" java.lang.NoSuchMethodError: redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(Ljava/util/Set;Lorg/apache/commons/pool2/impl/GenericObjectPoolConfig;I)V
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:36)
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:27)
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:31)`

I'm using jedis-3.0.0 from cluster-revised branch. 

The reason why I'm trying to use BinaryJedisCluster instead of JedisCluster because there is no `Set<byte[]> zrange(...)` method signature available in JedisCluster, only `Set<String> zrange(...)`.

**Comment by marcosnils** [comment]
@vlebedev you shouldn't instantiate BinaryJedisCluster. You should instantiate `JedisCluster` (which extends BinaryJedisCluster and use the methods from there. 

We can do BinaryJedisCluster protected so we don't encounter these errors.

**Comment by vlebedev** [comment]
@marcosnils thanks for the comment! Though JedisCluster does not contain Set<byte[]> zrange() signature in spite of the fact that Jedis has it. Are you going to fix it?

**Comment by marcosnils** [comment]
@vlebedev `JedisCluster` in cluster-revised branch contains both signatures `zrange(String, Long, Long)` and `zrange(byte[], long, long)`

Which method can't you find?

**Comment by vlebedev** [comment]
I'm getting the following runtime exception:

<pre>
java.lang.NoSuchMethodError: redis.clients.jedis.JedisCluster.zrange([BJJ)Ljava/util/Set;
	at com.cybertonica.pipeline.web.RestApi.lambda$main$0(RestApi.java:55)
	at com.cybertonica.pipeline.web.RestApi$$Lambda$1/474675244.handle(Unknown Source)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:154)
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:60)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:451)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
	at java.lang.Thread.run(Thread.java:745)
</pre>

Here is the piece of code from ResApi.java which causes it:

<pre>
            String historyKey = "v:{" + id + "}";
            Set<byte[]> history = jc.zrange(historyKey.getBytes(), 0, -1);
</pre>

**Comment by marcosnils** [comment]
@vlebedev you're using the Jedis Source directly or you've built your own jar?

**Comment by vlebedev** [comment]
@marcosnils I've built my own jar and put it in local maven repo

**Comment by marcosnils** [comment]
@vlebedev can you make sure your Jar is well built from the proper branch?. I've just tried the zrange(byte[]) using JedisCluster from the cluster-revised branch and it works without problems

**Comment by marcosnils** [comment]
@vlebedev also make sure your application is using the custom built jar propertly

**Comment by vlebedev** [comment]
@marcosnils may be I can use your 3.0.0-SNAPSHOT jar instead? do you have your maven repository which I can use (it is not in global maven repo yet, as I understood).

**Comment by marcosnils** [comment]
@vlebedev we don't have a 3.0 snapshot yet. I've built the jar locally in my computer form the cluster-revised branch.

Do you necessarily need it to be in a maven repo?

**Comment by vlebedev** [comment]
@marcosnils sorry, I found the problem - I did not clean target directory and old jedis-2.6.0 jar was on the path. I got rid of ClassNotFound exception. Many thanks for your help!

**Comment by marcosnils** [comment]
@vlebedev glad to help. We'll be merging cluster-revised branch today probably, keep it in mind so you can use the master branch Jar.
