### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: ERR Protocol error: expected '$', got ' '

### ISSUE THREAD

**Issue by Dreampie** [xetorthio/jedis#960]
```java
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe
	at redis.clients.jedis.Connection.flush(Connection.java:276) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:199) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.BinaryJedis.get(BinaryJedis.java:127) ~[jedis-2.6.2.jar:na]
	at cn.dreampie.cache.redis.RedisManager.getCache(RedisManager.java:120) ~[resty-cache-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.cache.SessionCache.get(SessionCache.java:62) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.credential.Credentials.findByUsername(Credentials.java:135) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.SessionBuilder.build(SessionBuilder.java:164) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.SessionBuilder.in(SessionBuilder.java:56) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.interceptor.security.SecurityInterceptor.intercept(SecurityInterceptor.java:56) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:61) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteHandler.handle(RouteHandler.java:62) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.handler.cors.CORSHandler.handle(CORSHandler.java:102) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.RestyFilter.doFilter(RestyFilter.java:85) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) [druid-1.0.13.jar:1.0.13]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.7.0_71]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113) ~[na:1.7.0_71]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159) ~[na:1.7.0_71]
	at redis.clients.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:31) ~[jedis-2.6.2.jar:na]
	at redis.clients.util.RedisOutputStream.flush(RedisOutputStream.java:213) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Connection.flush(Connection.java:273) ~[jedis-2.6.2.jar:na]
	... 31 common frames omitted
15-04-26 01:44:50.989 [http-bio-8083-exec-5] ERROR cn.dreampie.route.RestyFilter - /api/v1.0/sales/monthlys
redis.clients.jedis.exceptions.JedisDataException: ERR Protocol error: expected '$', got ' '
	at redis.clients.jedis.Protocol.processError(Protocol.java:113) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:138) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:192) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:201) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.BinaryJedis.get(BinaryJedis.java:127) ~[jedis-2.6.2.jar:na]
	at cn.dreampie.cache.redis.RedisManager.getCache(RedisManager.java:120) ~[resty-cache-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.cache.SessionCache.get(SessionCache.java:62) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.Sessions.getSessions(Sessions.java:181) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.SessionBuilder.build(SessionBuilder.java:160) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.SessionBuilder.in(SessionBuilder.java:56) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.interceptor.security.SecurityInterceptor.intercept(SecurityInterceptor.java:56) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:61) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteHandler.handle(RouteHandler.java:62) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.handler.cors.CORSHandler.handle(CORSHandler.java:102) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.RestyFilter.doFilter(RestyFilter.java:85) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) [druid-1.0.13.jar:1.0.13]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
15-04-26 01:44:50.989 [http-bio-8083-exec-6] ERROR cn.dreampie.route.RestyFilter - /api/v1.0/stores/monthlys
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:198) ~[jedis-2.6.2.jar:na]
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:128) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:192) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:201) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.BinaryJedis.get(BinaryJedis.java:127) ~[jedis-2.6.2.jar:na]
	at cn.dreampie.cache.redis.RedisManager.getCache(RedisManager.java:120) ~[resty-cache-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.cache.SessionCache.get(SessionCache.java:62) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.Sessions.getSessions(Sessions.java:181) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.SessionBuilder.build(SessionBuilder.java:160) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.SessionBuilder.in(SessionBuilder.java:56) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.interceptor.security.SecurityInterceptor.intercept(SecurityInterceptor.java:56) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:61) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteHandler.handle(RouteHandler.java:62) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.handler.cors.CORSHandler.handle(CORSHandler.java:102) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.RestyFilter.doFilter(RestyFilter.java:85) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) [druid-1.0.13.jar:1.0.13]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
15-04-26 01:44:50.989 [http-bio-8083-exec-3] ERROR cn.dreampie.route.RestyFilter - /api/v1.0/sales/dailys
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:198) ~[jedis-2.6.2.jar:na]
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:128) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:192) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:201) ~[jedis-2.6.2.jar:na]
	at redis.clients.jedis.BinaryJedis.get(BinaryJedis.java:127) ~[jedis-2.6.2.jar:na]
	at cn.dreampie.cache.redis.RedisManager.getCache(RedisManager.java:120) ~[resty-cache-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.cache.SessionCache.get(SessionCache.java:62) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.credential.Credentials.findByUsername(Credentials.java:135) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.SessionBuilder.build(SessionBuilder.java:164) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.security.SessionBuilder.in(SessionBuilder.java:56) ~[resty-security-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.interceptor.security.SecurityInterceptor.intercept(SecurityInterceptor.java:56) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:61) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.core.RouteHandler.handle(RouteHandler.java:62) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.handler.cors.CORSHandler.handle(CORSHandler.java:102) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at cn.dreampie.route.RestyFilter.doFilter(RestyFilter.java:85) ~[resty-route-1.0-SNAPSHOT.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) [druid-1.0.13.jar:1.0.13]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-embed-core-7.0.47.jar:7.0.47]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
```

**Comment by marcosnils** [comment]
@Dreampie seems like there was some sort of communication error and then Jedis complained that it couldn't parse the response correctly (possibly because of a malformed stream). I don't understand what's the problem here, in that case you should get a new Jedis instance and retry the operation.
