### ISSUE TITLE
Getting a JedisDataException with executing varargs in the following way for zrem through JedisCluster

### ISSUE THREAD

**Issue by asterp** [xetorthio/jedis#994]
I have a function like below. 
    public boolean batchDeleteSessionExpiryTimestamp(final Set<String> keys) {
      final long successfulDeletes = jedisCluster.zrem("to_be_expired", keys.toArray(new String[keys.size()]));
        return (successfulDeletes > 0);
    }

When I try to call this I'm getting an error with the stack trace below

Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'zrem' command
	at redis.clients.jedis.Protocol.processError(Protocol.java:117)
	at redis.clients.jedis.Protocol.process(Protocol.java:142)
	at redis.clients.jedis.Protocol.read(Protocol.java:196)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:256)
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:207)
	at redis.clients.jedis.Jedis.zrem(Jedis.java:1356)
	at redis.clients.jedis.JedisCluster$62.execute(JedisCluster.java:684)
	at redis.clients.jedis.JedisCluster$62.execute(JedisCluster.java:681)
	at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:56)
	at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:29)
	at redis.clients.jedis.JedisCluster.zrem(JedisCluster.java:686)

What am I doing wrong? How can I pass the varargs here?

**Comment by marcosnils** [comment]
@asterp which jedis version are you using?

**Comment by marcosnils** [comment]
@asterp just tried this in jedis 2.6.0 and works perfectly
```java
	@Test
	  public void testJedisClusterZrem() {
		Set<HostAndPort> jedisClusterNode = new HashSet<HostAndPort>();
		jedisClusterNode.add(new HostAndPort(nodeInfo1.getHost(), nodeInfo1.getPort()));
		JedisCluster jc = new JedisCluster(jedisClusterNode, 4000);

		Set<String> keys = new HashSet<String>();
		keys.add("test1");
		keys.add("test2");
		keys.add("test3");
		keys.add("test4");

		jc.zrem("somekey", keys.toArray(new String[keys.size()]));
	}
```

Can you provide a snippet to reproduce the error?

**Comment by asterp** [comment]
Does it work for you with RedisCluster 3.0 version? I am using Jedis 2.6.2

**Comment by marcosnils** [comment]
@asterp Yes, It works with Redis Cluster 3.0.

Can you please try creating a Main Class and testing my code?. If it works then it must be something from your side.

**Comment by marcosnils** [comment]
@asterp could you test my code?

**Comment by marcosnils** [comment]
Close due to inactivity

**Comment by sazzad16** [comment]
May not be an issue considering #958 #1137 

Removing tag.
